(() => {
"use strict";
const PARTS=["payload-parts/part-00.txt","payload-parts/part-01.txt","payload-parts/part-02.txt","payload-parts/part-03.txt","payload-parts/part-04.txt"];
const S1="\n/*__CCG_PAYLOAD_CSS_7C2F__*/\n",S2="\n/*__CCG_PAYLOAD_CORE_19A4__*/\n",S3="\n/*__CCG_PAYLOAD_GAME_37B1__*/\n",S4="\n/*__CCG_PAYLOAD_MOBILE_8E5C__*/\n";
async function load(){const texts=[];for(const file of PARTS){const r=await fetch(file,{cache:"force-cache"});if(!r.ok)throw new Error(`Unable to load ${file} (${r.status})`);texts.push(await r.text())}const binary=atob(texts.join(""));const bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);if(typeof DecompressionStream!=="function")throw new Error("Please use a current Chrome, Edge, Firefox or Safari browser.");const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream("gzip"));return new Response(stream).text()}
function exec(code,label){const s=document.createElement("script");s.dataset.ccgQuestBundle=label;s.textContent=`${code}\n//# sourceURL=ccg-quest-${label}.js`;document.body.appendChild(s)}
function fail(e){console.error("[CCG QUEST] Public payload failed",e);document.body.innerHTML=`<main style="min-height:100vh;display:grid;place-items:center;background:#050307;color:#eee;font:14px monospace;padding:24px"><div><h1 style="color:#ffd85a">GAME FILES COULD NOT LOAD</h1><p>${String(e?.message||e)}</p><p>Please refresh the page. If this continues, report it through the CCG website.</p></div></main>`}
load().then(text=>{const a=text.indexOf(S1),b=text.indexOf(S2),c=text.indexOf(S3),d=text.indexOf(S4);if([a,b,c,d].some(x=>x<0))throw new Error("Public game payload is incomplete.");const html=text.slice(0,a),css=text.slice(a+S1.length,b),core=text.slice(b+S2.length,c),game=text.slice(c+S3.length,d),mobile=text.slice(d+S4.length);document.body.innerHTML=html;const st=document.createElement("style");st.textContent=css;document.head.appendChild(st);exec(core,"core");exec(game,"game");exec(mobile,"mobile")}).catch(fail);
})();
