begin;

create table if not exists profile_favourites (
  id uuid primary key default gen_random_uuid(),
  profile_id text not null references ccg_users(user_id) on delete cascade,
  game_slug text not null,
  created_at timestamptz not null default now(),
  unique (profile_id, game_slug)
);

create table if not exists profile_game_library (
  id uuid primary key default gen_random_uuid(),
  profile_id text not null references ccg_profiles(user_id) on delete cascade,
  game_slug text not null,
  title text,
  system text,
  release_year text,
  lists text[] not null default '{}'::text[],
  custom_lists text[] not null default '{}'::text[],
  rating smallint,
  note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  unique (profile_id, game_slug),
  check (lists <@ array['played'::text, 'want'::text, 'owned'::text, 'still'::text]),
  check (rating is null or rating between 1 and 10)
);

create index if not exists profile_game_library_profile_updated_idx
  on profile_game_library(profile_id, updated_at desc);
create index if not exists profile_game_library_profile_deleted_idx
  on profile_game_library(profile_id, deleted_at desc)
  where deleted_at is not null;

create table if not exists profile_top_picks (
  id uuid primary key default gen_random_uuid(),
  profile_id text not null references ccg_users(user_id) on delete cascade,
  game_slug text not null,
  created_at timestamptz not null default now(),
  unique (profile_id, game_slug)
);

create table if not exists user_badges (
  id bigint generated by default as identity primary key,
  user_id text references ccg_profiles(user_id) on delete cascade,
  badge_code text not null,
  awarded_at timestamptz default now(),
  unique (user_id, badge_code)
);

create table if not exists user_roles (
  user_id text primary key references ccg_users(user_id) on delete cascade,
  role text not null,
  updated_at timestamptz not null default now()
);

create table if not exists email_subscriptions (
  profile_id text primary key references ccg_profiles(user_id) on delete cascade,
  email text not null,
  status text not null,
  unsubscribe_token text not null unique,
  updated_at timestamptz not null default now(),
  check (status in ('subscribed', 'unsubscribed'))
);

create table if not exists comments (
  id uuid primary key default gen_random_uuid(),
  user_id text references ccg_users(user_id) on delete cascade,
  game_key text not null,
  body text not null,
  created_at timestamptz default now(),
  deleted boolean default false,
  updated_at timestamptz default now(),
  page_type text,
  page_id text
);

create table if not exists ccq_weekly_attempts (
  id uuid primary key default gen_random_uuid(),
  week_start date not null,
  user_id text not null references ccg_users(user_id) on delete cascade,
  player_name text not null,
  seed text not null,
  status text not null default 'started',
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  score integer,
  deepest_floor smallint,
  duration_ms integer,
  level smallint,
  completed boolean not null default false,
  stats jsonb not null default '{}'::jsonb,
  ghost_path jsonb not null default '[]'::jsonb,
  unique (week_start, user_id),
  check (status in ('started', 'finished')),
  check (char_length(player_name) between 1 and 64),
  check (char_length(seed) between 8 and 80),
  check (score is null or score between 0 and 99999999),
  check (deepest_floor is null or deepest_floor between 1 and 5),
  check (duration_ms is null or duration_ms between 0 and 86400000),
  check (level is null or level between 1 and 99),
  check (jsonb_typeof(ghost_path) = 'array')
);

create index if not exists ccq_weekly_attempts_week_score_idx
  on ccq_weekly_attempts(week_start, score desc nulls last, deepest_floor desc nulls last);

comment on table profile_favourites is
  'Source-compatible CCG-owned profile favourite state. Initial migration preserves Supabase user IDs as CCG user IDs.';
comment on table profile_game_library is
  'Source-compatible CCG-owned game-library/list state, including soft-delete timestamps and list membership.';
comment on table profile_top_picks is
  'Source-compatible CCG-owned public top-pick state.';
comment on table user_badges is
  'Source-compatible CCG-owned profile badge assignments. Existing source bigint IDs may be imported explicitly.';
comment on table user_roles is
  'Source-compatible CCG-owned account role state used after authentication moves away from Supabase.';
comment on table email_subscriptions is
  'Source-compatible CCG-owned subscription state. Unsubscribe tokens are migration-sensitive bearer values and must not be logged.';
comment on table comments is
  'Source-compatible account-owned legacy comment state retained so account migration does not discard existing user content.';
comment on table ccq_weekly_attempts is
  'Source-compatible Weekly Vault attempt state. Prefer this table over the provisional lost_sizzler_weekly_vault placeholder when implementing the migrated Weekly Vault API.';

commit;
