begin;

create table if not exists ccq_weekly_leaderboard (
  attempt_id uuid primary key references ccq_weekly_attempts(id) on delete cascade,
  week_start date not null,
  player_name text not null,
  score integer not null check (score between 0 and 99999999),
  deepest_floor smallint not null check (deepest_floor between 1 and 5),
  duration_ms integer not null check (duration_ms between 0 and 86400000),
  level smallint not null check (level between 1 and 99),
  completed boolean not null default false,
  recorded_at timestamptz not null default now(),
  check (char_length(player_name) between 1 and 64)
);

create index if not exists ccq_weekly_leaderboard_week_rank_idx
  on ccq_weekly_leaderboard(week_start, score desc, deepest_floor desc, duration_ms asc);

create table if not exists ccq_weekly_result_deliveries (
  week_start date primary key,
  status text not null default 'processing',
  emailed integer not null default 0 check (emailed >= 0),
  email_failed integer not null default 0 check (email_failed >= 0),
  discord_sent boolean not null default false,
  error_detail text,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists game_feedback (
  id bigint generated by default as identity primary key,
  game_slug text not null default 'the-lost-sizzler',
  feedback_type text not null,
  message text not null check (char_length(message) between 10 and 3000),
  contact_email text,
  page_url text,
  build text,
  user_agent text,
  created_at timestamptz not null default now(),
  email_status text not null default 'pending',
  email_error text,
  feedback_status text not null default 'open',
  last_replied_at timestamptz,
  check (feedback_type in ('bug', 'suggestion'))
);

create index if not exists game_feedback_created_idx
  on game_feedback(created_at desc);

create table if not exists game_feedback_replies (
  id bigint generated by default as identity primary key,
  feedback_id bigint not null references game_feedback(id) on delete cascade,
  admin_user_id text references ccg_users(user_id) on delete set null,
  reply_text text not null,
  recipient_email text,
  email_status text not null default 'pending',
  email_error text,
  created_at timestamptz not null default now()
);

create index if not exists game_feedback_replies_feedback_idx
  on game_feedback_replies(feedback_id, created_at asc);

create table if not exists game_play_events (
  id bigint generated by default as identity primary key,
  game_slug text not null default 'the-lost-sizzler',
  event_type text not null,
  player_name text,
  play_mode text,
  device_type text not null default 'unknown',
  rating smallint,
  session_token text,
  auth_user_id text references ccg_users(user_id) on delete set null,
  build text,
  page_url text,
  user_agent text,
  created_at timestamptz not null default now(),
  metadata jsonb,
  check (rating is null or rating between 1 and 5)
);

create index if not exists game_play_events_game_event_idx
  on game_play_events(game_slug, event_type, created_at desc);
create index if not exists game_play_events_auth_rating_idx
  on game_play_events(auth_user_id, event_type)
  where auth_user_id is not null;

create table if not exists lost_sizzler_request_buckets (
  bucket_key text primary key,
  window_started_at timestamptz not null default now(),
  request_count integer not null default 0 check (request_count >= 0),
  updated_at timestamptz not null default now(),
  check (char_length(bucket_key) between 1 and 160)
);

comment on table ccq_weekly_leaderboard is
  'Source-compatible public Weekly Vault score projection. Account ownership remains in ccq_weekly_attempts.';
comment on table ccq_weekly_result_deliveries is
  'Source-compatible Weekly Vault result-delivery history. Delivery credentials are deployment secrets and are never stored here.';
comment on table game_feedback is
  'Source-compatible Lost Sizzler feedback history retained for verified Supabase retirement.';
comment on table game_feedback_replies is
  'Source-compatible admin feedback reply history; current Supabase source contains zero rows.';
comment on table game_play_events is
  'Source-compatible Lost Sizzler telemetry/rating history. This data is not required for offline gameplay or account login.';
comment on table lost_sizzler_request_buckets is
  'Operational one-way request-budget state. Bucket keys must never contain raw IP addresses.';

commit;
