#!/usr/bin/env node
"use strict";

import fs from "node:fs";
import path from "node:path";
import assert from "node:assert";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, "..");
const read = (rel) => fs.readFileSync(path.join(root, rel), "utf8");

const html = read("emulator/c64/index.html");
const css = read("resources/css/ccg-c64-emulator.css");
const app = read("js/ccg-c64/app.js");
const cia = read("js/ccg-c64/core/cia.js");
const audioWorklet = read("js/ccg-c64/core/sid/sid-worklet.js");
const sidWasmBlob = read("js/ccg-c64/core/sid/sid-wasm-blob.js");
const webglPresenter = read("js/ccg-c64/core/webgl-presenter.js");
const crtParams = read("js/ccg-c64/core/crt-params.js");
const sidFilter = read("js/ccg-c64/core/sid/sid-filter.js");
const g64 = read("js/ccg-c64/core/media/g64.js");
const gameVault = read("js/ccg-c64/game-vault.js");
const t64 = read("js/ccg-c64/t64.js");
const vault = read("js/ccg-c64/rom-vault.js");
const headers = read("_headers");
const emulation = read("emulation.html");
const onlineLibrary = JSON.parse(read("emulator/c64/library.json"));
const coiBootstrap = read("js/ccg-c64/coi-bootstrap.js");
const coiWorker = read("emulator/c64/coi-service-worker.js");

assert(html.includes("CCG BROWSER C64") || html.includes("CCG C64"), "CCG identity is required");
assert(!/C64 READY\.?/i.test(html), "Upstream product branding must not appear in the CCG emulator UI");
assert(html.includes('width="384" height="272"'), "Native C64 canvas dimensions must be reserved");
assert(!html.includes("webkitdirectory"), "The emulator must not force a VICE-folder scan");
assert(html.includes('id="ccg-rom-set"') && html.includes("multiple"), "Direct multi-file system ROM selection must exist");
assert(html.includes("data-load-any-media"), "A file-first C64 media loader must exist");
assert(html.includes("data-media-dropzone"), "Drag-and-drop media loading must exist");
assert(html.includes("data-online-library-select"), "The CCG Online Library selector must exist");
assert(!/<iframe\b/i.test(html), "Stage 1 must not introduce eager third-party frames");
assert(!/<script[^>]+https?:/i.test(html), "Emulator shell must not load third-party scripts");
assert(html.includes('src="/js/ccg-c64/coi-bootstrap.js"'), "Emulator shell must start through the COI bootstrap");
assert(!html.includes('src="/js/ccg-c64/app.js"'), "The C64 app must not start before cross-origin isolation is ready");
assert(coiBootstrap.includes('navigator.serviceWorker.register(WORKER_URL'), "COI bootstrap must register the route-scoped worker");
assert(coiBootstrap.includes('window.crossOriginIsolated === true'), "COI bootstrap must verify browser isolation before importing the emulator");
assert(coiBootstrap.includes('await import("/js/ccg-c64/app.js")'), "COI bootstrap must import the emulator only after isolation");
assert(coiBootstrap.includes('location.reload()'), "COI bootstrap must reload once under the isolated document response");
assert(coiWorker.includes('Cross-Origin-Opener-Policy'), "COI worker must stamp COOP on emulator navigation responses");
assert(coiWorker.includes('Cross-Origin-Embedder-Policy'), "COI worker must stamp COEP on emulator navigation responses");
assert(coiWorker.includes('request.mode !== "navigate"'), "COI worker must remain scoped to document navigations");
assert(coiWorker.includes('url.pathname.startsWith(EMULATOR_SCOPE)'), "COI worker must not rewrite unrelated CCG routes");
assert(css.includes(".ccg-c64-control-stack"), "Compact modular control-deck layout must be present");
assert(css.includes(".ccg-c64-screen-stage"), "Large emulator display stage must be present");
assert(css.includes("@media (max-width: 760px)"), "Mobile command-deck layout is required");
assert(vault.includes("ccg.emulator.c64.rom.kernal"), "CCG-local ROM namespace is required");
assert(vault.includes("export function pickRomFiles"), "Generic ROM-set matching must replace VICE-only discovery");
assert(vault.includes("async installFiles(files)"), "ROM vault must support installing a selected ROM set");
assert(vault.includes("sizes: [8192]"), "KERNAL/BASIC size validation is required");
assert(vault.includes("sizes: [4096]"), "CHARGEN size validation is required");
assert(vault.includes("sizes: [16384, 16386]"), "1541 size validation is required");
assert(app.includes("vault.restore()"), "Cached ROM restoration must be wired");
assert(!app.includes("if (!initial.allRequiredReady) showSetup()"), "First visit must not force the firmware setup modal");
assert(app.includes("pendingMedia"), "Media selected before system ROM setup must be queued");
assert(app.includes("queueMediaFile"), "File-first media routing must be wired");
assert(app.includes("initialiseOnlineLibrary"), "Online Library manifest loading must be wired");
assert(app.includes('fetch("/emulator/c64/library.json"'), "Online Library must load from the CCG manifest");
assert(app.includes('import { C64Machine } from "./core/machine.js"'), "Machine core must be wired into the CCG app");
assert(app.includes("machine.runFrame()"), "PAL frame execution must be wired");
assert(app.includes("machine.loadPRG(bytes)"), "Stage 2 quick PRG loading must be wired");
assert(app.includes('import { KEY_MAP, CHAR_MAP } from "./core/cia.js"'), "C64 keyboard matrix maps must be wired");
assert(app.includes("machine.cia1.setKey"), "Physical keyboard input must reach the CIA1 matrix");
assert(app.includes("machine.setRestoreNmiLine"), "RESTORE/NMI keyboard handling must be wired");
assert(app.includes("navigator.getGamepads"), "Gamepad polling must be wired");
assert(app.includes("gamepadJoyByte = byte"), "Gamepad input must feed the shared Port 2 merger");
assert(app.includes("touchHeldMask |= mask"), "Touch controls must feed joystick Port 2");
assert(app.includes('event.code || `key:${event.key}`'), "Held keyboard identity must survive Shift changes");
assert(cia.includes("'*': { col: 6, row: 1, shift: false }"), "C64 asterisk must remain the unshifted matrix key");
assert(app.includes("else if (!charBinding.shift && shiftDown)"), "Symbol mapping must suppress host Shift when the C64 symbol is unshifted");
assert(app.includes("releasedLeftShift") && app.includes("releasedRightShift"), "Symbol mapping must restore either physical Shift key after a host-layout override");
assert(app.includes('event.getModifierState?.("AltGraph")'), "AltGr must not leak a phantom C64 CTRL modifier");
assert(app.includes('event.code === "ArrowLeft"') && app.includes('event.code === "ArrowUp"'), "VICE-style shifted cursor mapping must be retained");
assert(app.includes('F2: "F1"') && app.includes('F8: "F7"'), "VICE-style shifted function-key mapping must be retained");
assert(app.includes('import { D64, d64Variant } from "./core/media/d64.js"'), "D64 parser must be wired into the media bay");
assert(app.includes("machine.setD64(disk)"), "Drive 8 disk mounting must reach the machine core");
assert(app.includes("machine.injectLoadAndRun()"), "The first D64 quick-load route must queue LOAD/RUN");
assert(app.includes('let driveMode = "fast"'), "Each emulator visit must start in Fast Load so ordinary disk images auto-start");
assert(app.includes("firstSupportedDroppedFile"), "Screen drop loading must choose a supported C64 media file");
assert(app.includes('mediaDropzone?.addEventListener("drop"'), "The C64 screen stage must accept dropped game media");
assert(app.includes("await queueMediaFile(file, { freshBoot: true })"), "Dropped media must use the same clean automatic boot/load route as primary file selection");
assert(html.includes("LOAD &amp; AUTO START"), "Primary file loader must advertise automatic game start");
assert(app.includes("function basicReady()"), "Auto-start must wait for a real BASIC READY prompt");
assert(app.includes("function queueAutoStart(steps)"), "Auto-start must use a staged load sequence");
assert(app.includes("function serviceAutoStart()"), "Auto-start sequence must advance from the emulation loop");
assert(app.includes("machine.bufferKeyboardText(autoStartTypeRest)"), "Long LOAD commands must be chunk-fed through the C64 keyboard buffer");
assert(app.includes("{ loadDone: true }"), "Disk/tape auto-start must wait for loading to finish before RUN");
assert(app.includes("prepareFreshGameSession()"), "Primary file loading must be able to start a clean C64 session");
assert(app.includes("queueMediaFile(file, { freshBoot: true })"), "Primary file and drop routes must request a clean auto-start session");
assert(app.includes("{ type: 'LOAD\"*\",8,1\\r' }"), "Disk auto-start must enter LOAD wildcard on device 8");
assert(app.includes('{ type: "RUN\\r" }'), "Disk/tape auto-start must enter RUN after loading");
assert(html.includes("AUTO LOAD"), "The emulator UI must advertise screen drop auto-loading");
assert(html.includes("data-load-disk"), "The CCG media bay must expose its disk load control");
assert(html.includes('accept=".d64,.d71,.d81,.g64"'), "Disk bay must expose D64/D71/D81/G64 workflows");
assert(app.includes("new G64(bytes)"), "G64 raw-track media must be wired");
assert(g64.includes("GCR-1541"), "G64 parser must validate the raw-track signature");
assert(html.includes("data-drive-mode"), "Disk bay must expose Fast Load / True 1541 switching");
assert(html.includes("data-load-tape"), "Datasette bay must expose TAP/T64 loading");
assert(html.includes("data-load-cartridge"), "Cartridge bay must expose CRT loading");
assert(html.includes('accept=".prg,.d64,.d71,.d81,.g64,.tap,.t64,.crt"'), "Unified loader must advertise every supported user-media format");
assert(html.includes("data-vault-save"), "Game Vault must expose save controls");
assert(html.includes("data-joy-mask"), "Mobile touch joystick controls must exist");
assert(app.includes('machine.loadTap(bytes)'), "TAP media must reach the datasette");
assert(app.includes("extractFirstT64Program(bytes)"), "T64 quick-load path must be wired");
assert(app.includes("machine.loadCartridge(bytes)"), "CRT media must reach the cartridge hardware path");
assert(app.includes("machine.serializeState()"), "Game Vault must capture restorable machine state");
assert(app.includes("restored.restoreState(payload.state)"), "Game Vault must restore machine state");
assert(gameVault.includes('indexedDB.open(DB_NAME, DB_VERSION)'), "Game Vault must use browser-local IndexedDB");
assert(t64.includes("extractFirstT64Program"), "T64 parser must be present");
assert(html.includes("data-input-status"), "The command deck must expose live input state");
assert(html.includes("data-audio-status"), "The command deck must expose SID audio state");
assert(html.includes("data-audio-toggle"), "The command deck must expose SID mute control");
assert(html.includes("data-crt-toggle"), "The deck must expose CRT preset switching");
assert(html.includes("data-size-toggle"), "The deck must expose fit/2x display switching");
assert(html.includes("data-warp-load"), "The deck must expose Warp Load");
assert(app.includes("const WARP_LOAD_FACTOR = 4"), "Warp Load must use the qualified 4x multiplier");
assert(app.includes("delta * (warpLoadActive ? WARP_LOAD_FACTOR : 1)"), "Warp Load must accelerate emulated time without changing the machine core");
assert(app.includes("WARP SILENT"), "Warp Load must silence SID output while accelerated");
assert(app.includes("sidNode?.port.postMessage({ type: \"resync\" })"), "SID resync must remain available when Warp Load returns to 1x");
assert(app.includes("audioWorklet.addModule(SID_WORKLET_URL)"), "SID AudioWorklet module must be loaded");
assert(app.includes('SID_WORKLET_URL = "/js/ccg-c64/core/sid/sid-worklet.js"'), "The upstream-quality SID worklet path must be active");
assert(app.includes("shared: machine.sidShared"), "SID worklet must receive the machine SharedArrayBuffer");
assert(app.includes('engine: "wasm"'), "The upstream reSID WASM engine must be requested");
assert(app.includes('new AudioWorkletNode(audioContext, "sid-processor"'), "The upstream SID processor name must be used");
assert(audioWorklet.includes("registerProcessor('sid-processor'"), "Upstream SID processor must be registered");
assert(audioWorklet.includes("EVENT_LOOKAHEAD_CYCLES"), "SID timing/lookahead transport must be retained");
assert(audioWorklet.includes("SIDFilter"), "SID worklet must use the reSID-derived filter/mixer stage");
assert(audioWorklet.includes("SIDExternalFilter"), "SID worklet must use the C64 external RC output stage");
assert(audioWorklet.includes("sidWasmBytes"), "SID worklet must wire the embedded WASM engine");
assert(sidWasmBlob.includes("export function sidWasmBytes"), "Compiled SID WASM payload must be present");
assert(sidFilter.includes("filter8580new"), "Retained SID filter source must identify its reSID lineage");
assert(webglPresenter.includes("export class WebGLPresenter"), "Upstream WebGL presenter must be bundled");
assert(app.includes("WebGLPresenter.create"), "WebGL presenter must be the primary display path");
assert(app.includes("presentationBuffer()"), "Presented VIC-II buffer must feed WebGL");
assert(crtParams.includes("CRT_PRESETS"), "CRT preset definitions must be bundled");
assert(app.includes("presetParams(crtMode)"), "CRT presets must reach the presenter");
assert(!app.includes("frames < 3"), "The old three-frame catch-up cap must not throttle emulation after a stall");
assert(app.includes('type: "resync"'), "SID must resync after host-side pauses and display transitions");
assert(headers.includes("/emulator/c64/*"), "Emulator-specific headers are required");
assert(headers.includes("Cross-Origin-Embedder-Policy: require-corp"), "COEP must be scoped for SharedArrayBuffer");
assert(emulation.includes('href="/emulator/c64/"'), "Emulation hub must link to the CCG browser emulator");
assert.equal(onlineLibrary.version, 1, "Online Library manifest version must be pinned");
assert(Array.isArray(onlineLibrary.entries) && onlineLibrary.entries.length >= 1, "Online Library must contain at least one authorised test entry");
assert(onlineLibrary.entries.every((entry) => entry.license && (entry.url || entry.dataBase64)), "Every Online Library entry must carry redistribution context and media data");

console.log("CCG browser C64 Stage 1 contract passed.");
