import { ensureRole, startAccessMonitor } from './guard.js';
import { initAdminNav } from './admin-nav.js';
const BUCKET='ccg-arcade-assets';
const SCENES=['bedroom','beads','budget','fighter','invaders','christmas','maze','amiga','guru'];
const LABELS={bedroom:'Bedroom',beads:'Electric Bead Run',budget:'Budget Rack',fighter:'36% Bout',invaders:'Alien Formation',christmas:'Christmas Morning',maze:'Dot-Maze',amiga:'Amiga Upgrade',guru:'Guru Meditation'};
const LOST_SIZZLER_MUSIC=[
 ['music','lostSizzlerExploration','Lost Sizzler — General Exploration'],
 ['music','lostSizzlerDanger','Lost Sizzler — Danger / Combat Rooms'],
 ['music','lostSizzlerSanctuary','Lost Sizzler — Sanctuary / Safe Rooms'],
 ['music','lostSizzlerNamed','Lost Sizzler — Named Enemy Encounter'],
 ['music','lostSizzlerStalker','Lost Sizzler — Death Stalker / Count Loadula'],
 ['music','lostSizzlerRoomArchive','Lost Sizzler Room — C64 Archive'],
 ['music','lostSizzlerRoomWorkshop','Lost Sizzler Room — Workshop'],
 ['music','lostSizzlerRoomBudget','Lost Sizzler Room — Budget Rack'],
 ['music','lostSizzlerRoomDemo','Lost Sizzler Room — Demo Scene'],
 ['music','lostSizzlerRoomArmoury','Lost Sizzler Room — Armoury'],
 ['music','lostSizzlerRoomKitchen','Lost Sizzler Room — Kitchen'],
 ['music','lostSizzlerRoomReactor','Lost Sizzler Room — Reactor'],
 ['music','lostSizzlerRoomWarp','Lost Sizzler Room — Warp Room'],
 ['music','lostSizzlerRoomLibrary','Lost Sizzler Room — Library'],
 ['music','lostSizzlerRoomTape','Lost Sizzler Room — Tape Vault'],
 ['music','lostSizzlerRoomCartridge','Lost Sizzler Room — Cartridge Room'],
 ['music','lostSizzlerRoomCracked','Lost Sizzler Room — Cracked Archive'],
 ['music','lostSizzlerRoomFoundry','Lost Sizzler Room — Foundry'],
 ['music','lostSizzlerRoomModem','Lost Sizzler Room — Modem Room'],
 ['music','lostSizzlerRoomCrypt','Lost Sizzler Room — Crypt'],
 ['music','lostSizzlerRoomCrt','Lost Sizzler Room — CRT Chamber'],
 ['music','lostSizzlerRoomVault','Lost Sizzler Room — Vault']
];
const SLOT_GROUPS=[
 ['Main Backgrounds',SCENES.map(s=>['backgrounds',s,`${LABELS[s]} Background`])],
 ['Lost Sizzler Music',LOST_SIZZLER_MUSIC],
 ['Sound Effects',[['sfx','jump','Jump'],['sfx','pickup','Collect / Pickup'],['sfx','hit','Player / Enemy Hit'],['sfx','shot','Player / Boss Shot'],['sfx','bosswarn','Boss Warning'],['sfx','shield','Action Replay Shield'],['sfx','shieldlow','Shield Low Warning'],['sfx','unlock','Achievement Unlock'],['sfx','punch','Punch'],['sfx','kick','Kick']]],
 ['Commodore Quest Scene Music',[['music','title','Title Music'],['music','bedroom','Bedroom Music'],['music','bedroomBoss','Bedroom Boss Music'],['music','beads','Electric Bead Music'],['music','budget','Budget Rack Music'],['music','budgetBoss','Budget Boss Music'],['music','fighter','36% Bout Music'],['music','invaders','Alien Formation Music'],['music','christmas','Christmas Music'],['music','christmasBoss','Christmas Boss Music'],['music','maze','Dot-Maze Music'],['music','amiga','Amiga Music'],['music','amigaBoss','Amiga Boss Music'],['music','guru','Guru Music'],['music','guruBoss','Guru Boss Music']]]
];
const slotMap=new Map();for(const[,items]of SLOT_GROUPS)for(const[group,key,label]of items)slotMap.set(`${group}:${key}`,{group,key,label});
const $=s=>document.querySelector(s);let supabase=null;
function status(t,state='info'){const e=$('#arcade-status');if(e){e.textContent=t;e.dataset.state=state;}}
function safeName(n){return String(n||'asset').replace(/[^a-z0-9._-]+/gi,'-').replace(/-+/g,'-').slice(0,100);}
function isAudio(g){return g==='music'||g==='sfx';}
function valid(g,f){if(!f)return false;return isAudio(g)?/^audio\/(mpeg|ogg|wav|x-wav)$/i.test(f.type):/^image\/(png|jpeg|webp|gif|svg\+xml)$/i.test(f.type);}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function bytes(n){n=Number(n||0);return n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;}
function slots(){const s=$('#arcade-slot');s.textContent='';for(const[label,items]of SLOT_GROUPS){const g=document.createElement('optgroup');g.label=label;for(const[a,b,c]of items){const o=document.createElement('option');o.value=`${a}:${b}`;o.textContent=c;g.appendChild(o);}s.appendChild(g);}slotUi();}
function slotUi(){const s=slotMap.get($('#arcade-slot').value);if(!s)return;$('#arcade-file').accept=isAudio(s.group)?'.mp3,.ogg,.wav,audio/mpeg,audio/ogg,audio/wav':'.png,.jpg,.jpeg,.webp,.gif,.svg,image/png,image/jpeg,image/webp,image/gif,image/svg+xml';}
function preview(){const f=$('#arcade-file').files?.[0],s=slotMap.get($('#arcade-slot').value),h=$('#arcade-preview');h.textContent='';if(!f||!s){h.textContent='Select a file to preview it.';return;}if(!valid(s.group,f)){h.textContent='This file type is not valid for the selected slot.';return;}const u=URL.createObjectURL(f),e=document.createElement(isAudio(s.group)?'audio':'img');if(isAudio(s.group))e.controls=true;else e.alt='Selected background preview';e.src=u;e.addEventListener(isAudio(s.group)?'loadeddata':'load',()=>URL.revokeObjectURL(u),{once:true});h.appendChild(e);}
async function client(){if(!window.ccgSupabase?.getClient)throw new Error('Supabase bootstrap unavailable.');return window.ccgSupabase.getClient();}
async function loadAssets(){const h=$('#arcade-library');h.innerHTML='<p class="arcade-muted">Loading backgrounds and audio…</p>';const{data,error}=await supabase.from('arcade_assets').select('*').in('asset_group',['backgrounds','music','sfx']).order('asset_group').order('asset_key');if(error){h.innerHTML=`<p class="arcade-status" data-state="error">${esc(error.message)}</p>`;return;}if(!data?.length){h.innerHTML='<p class="arcade-muted">No background or audio overrides uploaded yet. The game is using its bundled fallbacks.</p>';return;}h.textContent='';for(const r of data){const s=slotMap.get(`${r.asset_group}:${r.asset_key}`);if(!s)continue;const c=document.createElement('article');c.className='arcade-asset-card';const pv=isAudio(r.asset_group)?`<audio controls preload="none" src="${esc(r.public_url)}"></audio>`:`<img loading="lazy" src="${esc(r.public_url)}" alt="${esc(s.label)} preview">`;c.innerHTML=`<div class="arcade-asset-card__preview">${pv}</div><div class="arcade-asset-card__body"><div class="arcade-asset-card__title"><strong>${esc(s.label)}</strong><span class="arcade-pill ${r.enabled?'':'is-off'}">${r.enabled?'ACTIVE':'DISABLED'}</span></div><p class="arcade-asset-card__meta">${esc(r.mime_type||'unknown')} · ${bytes(r.size_bytes)}<br>${esc(r.file_path||'')}</p>${r.notes?`<p>${esc(r.notes)}</p>`:''}<div class="arcade-asset-card__actions"><button class="arcade-mini" data-action="toggle" data-group="${esc(r.asset_group)}" data-key="${esc(r.asset_key)}" data-enabled="${r.enabled?'1':'0'}">${r.enabled?'Disable':'Enable'}</button><button class="arcade-mini danger" data-action="delete" data-group="${esc(r.asset_group)}" data-key="${esc(r.asset_key)}" data-path="${esc(r.file_path)}">Delete</button></div></div>`;h.appendChild(c);}}
async function upload(ev){ev.preventDefault();const s=slotMap.get($('#arcade-slot').value),f=$('#arcade-file').files?.[0];if(!s||!f)return status('Choose a slot and file.','error');if(!valid(s.group,f))return status(isAudio(s.group)?'Audio slots accept MP3, OGG or WAV.':'Background slots accept PNG, JPG, WebP, GIF or SVG.','error');if(f.size>25*1024*1024)return status('Maximum upload size is 25 MB.','error');const b=$('#arcade-upload');b.disabled=true;try{const{data:old}=await supabase.from('arcade_assets').select('file_path').eq('asset_group',s.group).eq('asset_key',s.key).maybeSingle();const ext=(f.name.split('.').pop()||'bin').toLowerCase(),path=`${s.group}/${s.key}/${Date.now()}-${safeName(f.name.replace(/\.[^.]+$/,''))}.${ext}`;let x=await supabase.storage.from(BUCKET).upload(path,f,{cacheControl:'3600',upsert:false,contentType:f.type});if(x.error)throw x.error;const publicUrl=supabase.storage.from(BUCKET).getPublicUrl(path).data?.publicUrl;if(!publicUrl)throw new Error('Unable to resolve uploaded asset URL.');x=await supabase.from('arcade_assets').upsert({asset_group:s.group,asset_key:s.key,file_path:path,public_url:publicUrl,mime_type:f.type,size_bytes:f.size,enabled:$('#arcade-enabled').checked,notes:$('#arcade-notes').value.trim()||null,asset_meta:{},updated_at:new Date().toISOString()},{onConflict:'asset_group,asset_key'});if(x.error){await supabase.storage.from(BUCKET).remove([path]);throw x.error;}if(old?.file_path&&old.file_path!==path)await supabase.storage.from(BUCKET).remove([old.file_path]);status(`${s.label} updated. Reload the game to use it.`,'success');ev.target.reset();$('#arcade-enabled').checked=true;slots();preview();await loadAssets();}catch(e){console.error('[arcade-admin]',e);status(e?.message||'Upload failed.','error');}finally{b.disabled=false;}}
async function library(ev){const b=ev.target.closest('button[data-action]');if(!b)return;const g=b.dataset.group,k=b.dataset.key;if(!slotMap.has(`${g}:${k}`))return;if(b.dataset.action==='toggle'){const enabled=b.dataset.enabled!=='1',x=await supabase.from('arcade_assets').update({enabled,updated_at:new Date().toISOString()}).eq('asset_group',g).eq('asset_key',k);if(x.error)status(x.error.message,'error');else{status(`${g}:${k} ${enabled?'enabled':'disabled'}.`,'success');await loadAssets();}}else if(b.dataset.action==='delete'){if(!confirm(`Delete the custom asset for ${g}:${k}?`))return;const path=b.dataset.path;if(path)await supabase.storage.from(BUCKET).remove([path]);const x=await supabase.from('arcade_assets').delete().eq('asset_group',g).eq('asset_key',k);if(x.error)status(x.error.message,'error');else{status(`${g}:${k} removed.`,'success');await loadAssets();}}}
async function init(){if(!await ensureRole(['admin','superadmin']))return;await initAdminNav({pageLabel:'Arcade Asset Manager',active:'arcade'});await startAccessMonitor();supabase=await client();slots();$('#arcade-slot').addEventListener('change',()=>{slotUi();preview();});$('#arcade-file').addEventListener('change',preview);$('#arcade-asset-form').addEventListener('submit',upload);$('#arcade-library').addEventListener('click',library);$('#arcade-refresh').addEventListener('click',loadAssets);status('Admin access confirmed. Ready to upload.','success');await loadAssets();}
init().catch(e=>{console.error('[arcade-admin] init failed',e);status(e?.message||'Unable to initialise Arcade Asset Manager.','error');});