window.CCGAI=(()=>{
  "use strict";
  const C=window.CCG_CONFIG,W=window.CCGWorld,DIRS=[[1,0],[-1,0],[0,1],[0,-1]];
  const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),man=(a,b)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y),kind=e=>e.follower?.kind||e.kind,memory=e=>C.enemy.alertMemory[kind(e)]||C.enemy.alertMemory.scout;
  function lineOfSight(map,a,b,maxRange=C.enemy.lineOfSightRange,host=null){if(!a||!b||dist(a,b)>maxRange)return false;let x0=Math.round(a.x),y0=Math.round(a.y),x1=Math.round(b.x),y1=Math.round(b.y),dx=Math.abs(x1-x0),sx=x0<x1?1:-1,dy=-Math.abs(y1-y0),sy=y0<y1?1:-1,err=dx+dy;while(true){if(!(x0===a.x&&y0===a.y)&&!(x0===b.x&&y0===b.y)){if(map[y0]?.[x0]!==0||W.doorAt(host,x0,y0)?.locked)return false}if(x0===x1&&y0===y1)break;const e2=2*err;if(e2>=dy){err+=dy;x0+=sx}if(e2<=dx){err+=dx;y0+=sy}}return true}
  function inCone(e,p){const d=dist(e,p);if(d<=2.1||e.aiState==="chase"||p.torchMs>0)return true;const f=e.facing||{x:1,y:0},vx=p.x-e.x,vy=p.y-e.y,len=Math.hypot(vx,vy)||1;return (vx/len)*f.x+(vy/len)*f.y>=.05}
  function visibleTarget(e,map,players,host){let best=null,bestD=Infinity;for(const p of players.filter(p=>p&&p.health>0)){const range=p.torchMs>0?C.enemy.torchSightRange:C.enemy.lineOfSightRange,d=dist(e,p);if(d<bestD&&inCone(e,p)&&lineOfSight(map,e,p,range,host)){best=p;bestD=d}}return best?[best,bestD]:[null,Infinity]}
  function occupied(host,x,y,except){return host.enemies.some(o=>o!==except&&o.alive&&o.x===x&&o.y===y)}
  function randomStep(e,host,map){const a=DIRS.map(([dx,dy])=>({x:e.x+dx,y:e.y+dy,dx,dy})).filter(p=>W.walkable(map,p.x,p.y,host)&&!occupied(host,p.x,p.y,e));if(!a.length||Math.random()<.22)return false;a.sort((a,b)=>((a.dx===e.facing?.x&&a.dy===e.facing?.y)?-1:0)-((b.dx===e.facing?.x&&b.dy===e.facing?.y)?-1:0)+(Math.random()-.5)*1.3);const p=a[0];e.x=p.x;e.y=p.y;e.facing={x:p.dx,y:p.dy};return true}
  function nextStep(e,host,map,target){if(!target)return null;const start=`${e.x},${e.y}`,goal=`${target.x},${target.y}`;if(start===goal)return null;const open=[{x:e.x,y:e.y,g:0,f:man(e,target)}],best=new Map([[start,0]]),came=new Map();let guard=0;while(open.length&&guard++<900){open.sort((a,b)=>a.f-b.f);const cur=open.shift(),ck=`${cur.x},${cur.y}`;if(ck===goal){let c=goal,p=came.get(c);while(p&&p!==start){c=p;p=came.get(c)}const [x,y]=c.split(",").map(Number);return{x,y}}for(const [dx,dy] of DIRS){const x=cur.x+dx,y=cur.y+dy,nk=`${x},${y}`;if(!W.walkable(map,x,y,host)||occupied(host,x,y,e)&&nk!==goal)continue;const ng=cur.g+1;if(ng>=(best.get(nk)??Infinity))continue;best.set(nk,ng);came.set(nk,ck);open.push({x,y,g:ng,f:ng+Math.abs(x-target.x)+Math.abs(y-target.y)})}}return null}
  function moveToward(e,host,map,target){const p=nextStep(e,host,map,target);if(!p)return false;e.facing={x:Math.sign(p.x-e.x),y:Math.sign(p.y-e.y)};e.x=p.x;e.y=p.y;return true}
  function predicted(p,map,steps=3){const d=p?.dir||{x:0,y:0};let x=p.x,y=p.y;for(let i=0;i<steps;i++){const nx=x+d.x,ny=y+d.y;if(map[ny]?.[nx]!==0)break;x=nx;y=ny}return{x,y}}
  function idleInterval(){return C.enemy.idleStepMin+Math.random()*(C.enemy.idleStepMax-C.enemy.idleStepMin)}
  function chaseInterval(e){return C.enemy.chaseStep[kind(e)]||950}
  function shootAt(e,p,style,power,ttl,hooks){const ax=p.x-e.x,ay=p.y-e.y;let dx=0,dy=0;if(Math.abs(ax)>=Math.abs(ay))dx=Math.sign(ax);else dy=Math.sign(ay);e.facing={x:dx,y:dy};hooks.shoot?.({x:e.x,y:e.y,dx,dy,power,style,ttl,source:e.follower?.name||e.kind})}
  function attack(e,map,p,range,host,hooks){if(!p||e.attackCooldown>0||!lineOfSight(map,e,p,p.torchMs>0?C.enemy.torchSightRange:C.enemy.lineOfSightRange,host))return false;const k=kind(e);if(["scout","hunter","ambusher","charger","ghost"].includes(k)&&range<=1.45){e.attackCooldown=k==="charger"?1100:1450;hooks.melee?.(e,p,k==="hunter"?2:1);return true}if(k==="ranger"&&range<=9){shootAt(e,p,"normal",1,11,hooks);e.attackCooldown=2050;return true}if(k==="root"&&range<=8){shootAt(e,p,"root",1,9,hooks);e.attackCooldown=2300;return true}if(k==="cook"&&range<=8){shootAt(e,p,"food",2,8,hooks);e.attackCooldown=2700;return true}if(k==="guard"&&range<=9){shootAt(e,p,"normal",1,10,hooks);e.attackCooldown=2300;return true}if(k==="firebreather"&&range<=3.6){shootAt(e,p,"fire",2,3,hooks);e.attackCooldown=2900;hooks.notice?.("<strong>YOSHI YOSHI BREATHES FIRE.</strong> Short range, nasty temper. Back up.","flame");return true}return false}
  function support(e,host,dt,hooks){if(kind(e)!=="cook")return false;e.healCooldown-=dt;if(e.healCooldown>0)return false;let n=0;for(const a of host.enemies){if(a===e||!a.alive||a.hp>=a.maxHp||man(a,e)>4)continue;a.hp=Math.min(a.maxHp,a.hp+1);a.flash=120;n++}e.healCooldown=7200;if(n){hooks.notice?.("<strong>CPU SERVES DINNER.</strong> Nearby enemies regain health. Stop the chef.","heal");return true}return false}
  function stepOne(e,host,map,players,dt,hooks){if(!e.alive)return false;e.attackCooldown-=dt;e.moveCooldown-=dt;if(e.flash>0)e.flash=Math.max(0,e.flash-dt);let changed=support(e,host,dt,hooks);const [seen,range]=visibleTarget(e,map,players,host);if(seen){const was=e.aiState;e.aiState="chase";e.lastSeen={x:seen.x,y:seen.y};e.memoryMs=memory(e);e.searchMs=0;if(was!=="chase")hooks.alert?.(e,"alert")}else if(e.aiState==="chase"){e.memoryMs-=dt;if(e.memoryMs<=0){e.aiState="search";e.searchMs=C.enemy.searchTime;hooks.alert?.(e,"search")}}else if(e.aiState==="search"){e.searchMs-=dt;if(e.searchMs<=0){e.aiState="idle";e.lastSeen=null;e.moveCooldown=Math.max(e.moveCooldown,idleInterval());hooks.alert?.(e,"idle")}}if(seen)changed=attack(e,map,seen,range,host,hooks)||changed;if(kind(e)==="guard"||e.moveCooldown>0)return changed;let moved=false,k=kind(e);if(seen){if(["ranger","root","cook"].includes(k)){if(range<4){const away={x:e.x+Math.sign(e.x-seen.x)*2,y:e.y+Math.sign(e.y-seen.y)*2};moved=W.walkable(map,away.x,away.y,host)?moveToward(e,host,map,away):randomStep(e,host,map)}else if(range>6)moved=moveToward(e,host,map,seen)}else if(k==="firebreather"){if(range>3)moved=moveToward(e,host,map,seen)}else if(k==="ambusher")moved=moveToward(e,host,map,predicted(seen,map,3));else if(k==="charger"&&range<=7){moved=moveToward(e,host,map,seen);if(range>3)moved=moveToward(e,host,map,seen)||moved}else moved=moveToward(e,host,map,seen)}else if(e.aiState==="chase"&&e.lastSeen){moved=moveToward(e,host,map,e.lastSeen);if(e.x===e.lastSeen.x&&e.y===e.lastSeen.y){e.aiState="search";e.searchMs=C.enemy.searchTime;hooks.alert?.(e,"search")}}else moved=randomStep(e,host,map);e.moveCooldown=e.aiState==="chase"?chaseInterval(e):e.aiState==="search"?1450+Math.random()*400:idleInterval();return moved||changed}
  function stepEnemies(host,map,players,dt,hooks={}){if(!host?.enemies)return;let changed=false;for(const e of host.enemies)changed=stepOne(e,host,map,players,dt,hooks)||changed;if(changed)host.revision++}
  function alertEnemy(e,x,y){if(!e?.alive)return;e.aiState="chase";e.lastSeen={x,y};e.memoryMs=memory(e);e.searchMs=0}
  return{lineOfSight,visibleTarget,nextStepAStar:nextStep,stepEnemies,alertEnemy,kindOf:kind};
})();
