(()=>{
"use strict";
const C=window.CCG_CONFIG,W=window.CCGWorld,A=window.CCGAI,S=window.CCGSound,$=id=>document.getElementById(id);
const canvas=$("game"),ctx=canvas.getContext("2d");ctx.imageSmoothingEnabled=false;
const UI={health:$("hud-health"),mana:$("hud-mana"),keys:$("hud-keys"),score:$("hud-score"),room:$("hud-room"),players:$("hud-players"),mission:$("mission-text"),net:$("net-status"),sound:$("sound-btn"),message:$("message"),list:$("player-list"),menu:$("menu"),pause:$("pause"),end:$("end"),endTitle:$("end-title"),endText:$("end-text"),name:$("player-name"),roomCode:$("room-code"),note:$("menu-note")};
const logo=new Image();logo.onerror=()=>{if(!logo.src.endsWith(C.logoFallback))logo.src=C.logoFallback};logo.src=C.logoAsset;
const avatars=new Map();for(const f of C.followerElites){const im=new Image();im.src=f.avatar.startsWith("embedded:")?(window.CCG_AVATAR_DATA?.[f.avatar.slice(9)]||""):f.avatar;avatars.set(f.name,im)}
const P={floorA:"#111018",floorB:"#17131f",wall:"#493d90",wallHi:"#7b70d0",purple:"#b978ff",gold:"#ffd85a",cyan:"#6cecff",green:"#72ff9b",pink:"#ff5bae",red:"#ff6868",orange:"#ff9950",white:"#faf4ff",blue:"#6aa9ff",brown:"#9b6134"};
const keys=new Set(),remote=new Map(),bullets=[],enemyBullets=[],particles=[],rings=[],floaters=[],hazards=[],visuals=new Map();
let mode="menu",world=null,host=null,player=null,score=0,last=0,moveCD=0,fireCD=0,enemyCD=0,shotCD=0,sendCD=0,worldCD=0,camera={x:0,y:0},shake=0,damageFlash=0,dangerCD=0,lowHealthCD=0;
let camp={anchorX:0,anchorY:0,room:-1,elapsed:0,active:false,nextBlast:0};
const net=new window.CCGNetwork.RoomNetwork({onMembers,onPacket});
const esc=v=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const pad=n=>String(Math.max(0,Math.floor(n))).padStart(6,"0");
const md=(a,b)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
function say(h){UI.message.innerHTML=h}
function name(){return String(UI.name.value||"CCG Player").trim().slice(0,18)||"CCG Player"}
function sync(){if(!player||!host)return;UI.health.textContent=`${player.health}/${C.player.maxHealth}`;UI.mana.textContent=`${player.mana}/${C.player.maxMana}`;UI.keys.textContent=`${host.keysCollected}/${C.keyTarget}`;UI.score.textContent=pad(score);UI.room.textContent=net.mode==="coop"?net.roomCode:"SOLO";UI.players.textContent=Math.max(1,net.getMembers().length);UI.net.textContent=net.mode==="coop"?(net.transport==="supabase"?(net.isHost?"ONLINE • HOST":"ONLINE • CO-OP"):(net.isHost?"LOCAL • HOST":"LOCAL • CO-OP")):"SOLO";UI.net.classList.toggle("online",net.mode==="coop"&&net.connected);UI.mission.textContent=host.exitOpen?"Vault open — reach the purple exit.":`Find three keys (${host.keysCollected}/${C.keyTarget}). Break line-of-sight to lose enemies.`;UI.sound.textContent=S.isEnabled()?"SOUND ON":"SOUND OFF"}
function startWorld(seed){world=W.generate(seed);host=W.createHostState(world);player={id:net.sessionId,name:name(),x:world.start.x,y:world.start.y,rx:world.start.x,ry:world.start.y,health:C.player.maxHealth,mana:C.player.maxMana,dir:{x:1,y:0},invuln:0,sensorMs:0};score=0;remote.clear();bullets.length=enemyBullets.length=particles.length=rings.length=floaters.length=hazards.length=0;visuals.clear();camp={anchorX:player.x,anchorY:player.y,room:W.roomAt(world,player.x,player.y),elapsed:0,active:false,nextBlast:0};camera={x:0,y:0};sync()}
async function startSolo(){await S.start();S.startMusic();net.setSolo(name());startWorld("SOLO-CCG");mode="playing";UI.menu.classList.add("hidden");S.sfx("join");say("<strong>SOLO MODE.</strong> Three keys, one exit and several subscribers having a very strange day.")}
async function createRoom(){await S.start();S.startMusic();const c=net.createCode();UI.note.textContent="Creating room…";try{startWorld(c);const r=await net.join(c,name());mode="playing";UI.roomCode.value=c;UI.menu.classList.add("hidden");S.sfx("join");say(`<strong>ROOM ${c}</strong> created using ${r.transport==="supabase"?"internet":"local"} co-op.`);if(net.isHost)broadcastWorld()}catch(e){UI.note.textContent=e.message}}
async function joinRoom(){await S.start();S.startMusic();const c=window.CCGNetwork.cleanCode(UI.roomCode.value);if(c.length<4){UI.note.textContent="Enter the host room code.";return}try{startWorld(c);const r=await net.join(c,name());mode="playing";UI.menu.classList.add("hidden");S.sfx("join");say(`<strong>JOINED ${c}</strong> using ${r.transport==="supabase"?"internet":"local"} co-op.`)}catch(e){UI.note.textContent=e.message}}
function onMembers(m,isHost,changed){UI.list.innerHTML=(m.length?m:[{name:name()}]).map((x,i)=>`${esc(x.name)}${i===0?" ★":""}`).join("<br>");if(changed&&isHost&&mode==="playing"){say("<strong>HOST MIGRATION.</strong> You now control the dungeon. Try not to become drunk with power.");broadcastWorld()}sync()}
function onPacket(ev,p){if(ev==="player")onPlayer(p);else if(ev==="shot")spawnBullet(p,true);else if(ev==="enemy_shot")spawnEnemyShot(p);else if(ev==="hit"&&net.isHost){const e=host.enemies.find(x=>x.id===p?.enemyId&&x.alive);if(e)damageEnemy(e,Math.max(1,Math.min(3,p.power||1)))}else if(ev==="collect"&&net.isHost)collectRequest(p);else if(ev==="collected")collected(p);else if(ev==="world"&&!net.isHost)applyWorld(p);else if(ev==="notice")say(p?.html||"");else if(ev==="complete")finish(p?.by||"the team")}
function onPlayer(p){if(!p||p.id===net.sessionId)return;const old=remote.get(p.id);remote.set(p.id,{...p,rx:old?.rx??p.x,ry:old?.ry??p.y,lastSeen:performance.now()})}
function sendPlayer(){net.send("player",{id:net.sessionId,name:player.name,x:player.x,y:player.y,health:player.health,dir:player.dir})}
function serialWorld(){return{revision:host.revision,keysCollected:host.keysCollected,exitOpen:host.exitOpen,enemies:host.enemies,items:host.items}}
function broadcastWorld(){if(net.mode==="coop"&&net.connected&&net.isHost)net.send("world",serialWorld())}
function applyWorld(s){if(!s||!host||Number(s.revision)<Number(host.revision))return;host={revision:Number(s.revision||0),keysCollected:Number(s.keysCollected||0),exitOpen:Boolean(s.exitOpen),enemies:Array.isArray(s.enemies)?s.enemies:[],items:Array.isArray(s.items)?s.items:[]};sync()}
function livePlayers(){const a=[player],now=performance.now();for(const p of remote.values())if(now-p.lastSeen<2600)a.push(p);return a}
function enemyStep(dt){if(!net.isHost)return;A.stepEnemies(host,world.map,livePlayers(),dt,{shoot:s=>{spawnEnemyShot(s);net.send("enemy_shot",s)},notice:(html,sound)=>{say(html);if(sound)S.sfx(sound);net.send("notice",{html})},alert:(e,state)=>{if(state==="alert"){S.sfx("alert");floatText(e.x,e.y,"!",P.red)}if(state==="search")S.sfx("search")}})}
function setDir(code){const d={ArrowLeft:{x:-1,y:0},KeyA:{x:-1,y:0},ArrowRight:{x:1,y:0},KeyD:{x:1,y:0},ArrowUp:{x:0,y:-1},KeyW:{x:0,y:-1},ArrowDown:{x:0,y:1},KeyS:{x:0,y:1}}[code];if(d&&player)player.dir=d}
function held(){if(keys.has("ArrowLeft")||keys.has("KeyA"))return{x:-1,y:0};if(keys.has("ArrowRight")||keys.has("KeyD"))return{x:1,y:0};if(keys.has("ArrowUp")||keys.has("KeyW"))return{x:0,y:-1};if(keys.has("ArrowDown")||keys.has("KeyS"))return{x:0,y:1};return null}
function move(dx,dy,dash=false){if(!player)return;player.dir={x:dx,y:dy};const n=dash?2:1;for(let i=0;i<n;i++){const warp=W.tunnelDestination(world,player.x,player.y,dx,dy);if(warp){player.x=player.rx=warp.x;player.y=player.ry=warp.y;S.sfx("warp");burst(player.x,player.y,P.cyan,18);continue}const x=player.x+dx,y=player.y+dy;if(!W.walkable(world.map,x,y)){if(i===0)S.sfx("wall");break}player.x=x;player.y=y;collectLocal();const e=host.enemies.find(e=>e.alive&&e.x===x&&e.y===y);if(e)hurt(e.follower?2:1);if(host.exitOpen&&x===world.exit.x&&y===world.exit.y)finish(player.name)}sendPlayer()}
function fire(){if(mode!=="playing"||fireCD>0||bullets.length>=C.player.maxProjectiles)return;if(player.mana<=0){S.sfx("empty");fireCD=280;return}const d=held()||player.dir;player.dir=d;player.mana--;const b={id:`${net.sessionId}-${Date.now()}`,x:player.x,y:player.y,dx:d.x,dy:d.y,power:1,ttl:13,owner:net.sessionId};spawnBullet(b,false);net.send("shot",b);S.sfx("fire");fireCD=C.player.fireDelay;burst(player.x,player.y,P.orange,5);sync()}
function dash(){if(mode!=="playing"||player.mana<2)return;const d=held()||player.dir;player.mana-=2;S.sfx("dash");move(d.x,d.y,true);moveCD=C.player.dashDelay;sync()}
function spawnBullet(b,remoteShot){if(!b)return;bullets.push({...b,remote:remoteShot})}
function spawnEnemyShot(b){if(!b)return;enemyBullets.push({...b});S.sfx(b.style==="fire"?"flame":b.style==="food"?"food":"enemy")}
function damageEnemy(e,n){e.hp-=n;e.flash=150;S.sfx("hit");burst(e.x,e.y,P.orange,8);ring(e.x,e.y,P.orange,20);if(e.hp>0)return; e.alive=false;host.revision++;score+=e.follower?700:120;S.sfx(e.follower?"elite":"death");burst(e.x,e.y,e.follower?P.gold:P.pink,e.follower?28:18);if(e.follower){const html=`<strong>${esc(e.follower.name)} FREED.</strong> The Score Goblin's influence has worn off.`;say(html);net.send("notice",{html})}broadcastWorld()}
function updateShots(){for(const b of bullets){const nx=b.x+b.dx,ny=b.y+b.dy;if(!W.walkable(world.map,nx,ny)){b.ttl=0;continue}b.x=nx;b.y=ny;b.ttl--;const e=host.enemies.find(e=>e.alive&&e.x===b.x&&e.y===b.y);if(e){b.ttl=0;if(net.isHost)damageEnemy(e,b.power);else net.send("hit",{enemyId:e.id,power:b.power})}}for(const b of enemyBullets){const nx=b.x+b.dx,ny=b.y+b.dy;if(!W.walkable(world.map,nx,ny)){b.ttl=0;continue}b.x=nx;b.y=ny;b.ttl--;if(b.x===player.x&&b.y===player.y){b.ttl=0;hurt(b.power||1)}}for(let i=bullets.length-1;i>=0;i--)if(bullets[i].ttl<=0)bullets.splice(i,1);for(let i=enemyBullets.length-1;i>=0;i--)if(enemyBullets[i].ttl<=0)enemyBullets.splice(i,1)}
function hurt(n=1){if(player.invuln>0)return;player.health-=n;player.invuln=900;shake=10;damageFlash=.9;S.sfx("hurt");resetCamp();if(player.health<=0){player.health=C.player.maxHealth;player.mana=C.player.maxMana;player.x=player.rx=world.start.x;player.y=player.ry=world.start.y;score=Math.max(0,score-500);S.sfx("respawn");say("<strong>RESPAWN.</strong> Consider that the browser equivalent of finding the trainer menu.")}sync()}
function collectLocal(){for(const i of host.items)if(i.active&&i.x===player.x&&i.y===player.y){if(net.isHost)collectItem(i,player.id);else net.send("collect",{id:i.id,playerId:player.id})}}
function collectRequest(p){const i=host.items.find(x=>x.id===p?.id&&x.active);if(i)collectItem(i,p.playerId)}
function collectItem(i,who){i.active=false;host.revision++;if(i.kind==="key"){host.keysCollected++;if(host.keysCollected>=C.keyTarget){host.exitOpen=true;S.sfx("open");say("<strong>VAULT OPEN.</strong> The purple exit is active.")}}const p={id:i.id,kind:i.kind,title:i.title,who};collected(p);net.send("collected",p);broadcastWorld()}
function collected(p){if(p.who!==player.id)return;if(p.kind==="health")player.health=Math.min(C.player.maxHealth,player.health+2);else if(p.kind==="mana")player.mana=Math.min(C.player.maxMana,player.mana+4);else if(p.kind==="sensor")player.sensorMs=10000;else if(p.kind==="credits")score+=100;else if(p.kind==="game")score+=250;S.sfx(p.kind==="key"?"key":"pickup");say(p.kind==="game"?`<strong>C64 RESCUED: ${esc(p.title||"CLASSIC")}</strong> — back on the shelf where it belongs.`:p.kind==="sensor"?"<strong>RADAR BOOST.</strong> Hidden threats appear on the minimap for ten seconds.":"Pickup collected.");sync()}
function resetCamp(){camp={anchorX:player.x,anchorY:player.y,room:W.roomAt(world,player.x,player.y),elapsed:0,active:false,nextBlast:0}}
function updateCamping(dt){const room=W.roomAt(world,player.x,player.y);if(room!==camp.room||Math.hypot(player.x-camp.anchorX,player.y-camp.anchorY)>=C.camping.resetDistance){resetCamp();return}camp.elapsed+=dt;if(camp.elapsed<C.camping.graceMs)return;if(!camp.active){camp.active=true;camp.nextBlast=100;S.sfx("campwarn");say("<strong>TOO COMFORTABLE.</strong> Mini explosions are starting. Time to move.")}camp.nextBlast-=dt;if(camp.nextBlast<=0){const opts=[];for(let y=-C.camping.zoneRadius;y<=C.camping.zoneRadius;y++)for(let x=-C.camping.zoneRadius;x<=C.camping.zoneRadius;x++){const tx=camp.anchorX+x,ty=camp.anchorY+y;if(W.walkable(world.map,tx,ty)&&Math.hypot(x,y)<=C.camping.zoneRadius+.2)opts.push({x:tx,y:ty})}if(opts.length){const p=opts[Math.floor(Math.random()*opts.length)];hazards.push({...p,life:C.camping.warningMs,max:C.camping.warningMs})}camp.nextBlast=C.camping.blastIntervalMs}}
function updateHazards(dt){for(let i=hazards.length-1;i>=0;i--){const h=hazards[i];h.life-=dt;if(h.life>0)continue;hazards.splice(i,1);S.sfx("explosion");shake=9;burst(h.x,h.y,P.orange,24);ring(h.x,h.y,P.red,36);if(Math.hypot(player.x-h.x,player.y-h.y)<=C.camping.blastRadius+.2)hurt(1)}}
function finish(by){if(mode==="ended")return;mode="ended";S.sfx("win");UI.endTitle.textContent="Vault Cleared";UI.endText.textContent=`${by} escaped with ${host.keysCollected} keys. Score: ${pad(score)}.`;UI.end.classList.remove("hidden");if(net.mode==="coop")net.send("complete",{by})}
function burst(x,y,col,n=10){for(let i=0;i<n;i++)particles.push({x:x*C.tile+C.tile/2,y:y*C.tile+C.tile/2,vx:(Math.random()-.5)*3,vy:(Math.random()-.5)*3,life:300+Math.random()*350,col,size:2+Math.random()*3})}
function ring(x,y,col,max=30){rings.push({x:x*C.tile+C.tile/2,y:y*C.tile+C.tile/2,r:3,max,life:330,col})}
function floatText(x,y,text,col){floaters.push({x:x*C.tile+C.tile/2,y:y*C.tile,text,col,life:700})}
function update(dt){if(mode!=="playing")return;moveCD-=dt;fireCD-=dt;enemyCD-=dt;shotCD-=dt;sendCD-=dt;worldCD-=dt;dangerCD-=dt;lowHealthCD-=dt;if(player.invuln>0)player.invuln-=dt;if(player.sensorMs>0)player.sensorMs-=dt;if(damageFlash>0)damageFlash=Math.max(0,damageFlash-dt/500);if(keys.has("Space")&&fireCD<=0)fire();if(moveCD<=0){const d=held();if(d){move(d.x,d.y);moveCD=C.player.moveDelay}}if(shotCD<=0){updateShots();shotCD=70}if(enemyCD<=0){enemyStep(C.enemy.thinkDelay);enemyCD=C.enemy.thinkDelay}if(sendCD<=0){sendPlayer();sendCD=180}if(worldCD<=0){broadcastWorld();worldCD=500}player.rx+=(player.x-player.rx)*.28;player.ry+=(player.y-player.ry)*.28;for(const p of remote.values()){p.rx+=(p.x-p.rx)*.22;p.ry+=(p.y-p.ry)*.22}updateCamping(dt);updateHazards(dt);if(player.health<=2&&lowHealthCD<=0){S.sfx("lowhealth");lowHealthCD=2600}if(dangerCD<=0){let n=0;for(const e of host.enemies)if(e.alive&&A.lineOfSight(world.map,e,player,C.enemy.lineOfSightRange))n++;S.setDanger(Math.min(1,n/3));dangerCD=350}sync()}
function ws(x,y){return{x:x*C.tile-camera.x,y:y*C.tile-camera.y}}
function updateCamera(){const tx=Math.max(0,Math.min(C.worldWidth*C.tile-canvas.width,player.rx*C.tile+C.tile/2-canvas.width/2)),ty=Math.max(0,Math.min(C.worldHeight*C.tile-canvas.height,player.ry*C.tile+C.tile/2-canvas.height/2));camera.x+=(tx-camera.x)*.12;camera.y+=(ty-camera.y)*.12}
function drawTile(x,y){const s=ws(x,y);if(world.map[y][x]===0){ctx.fillStyle=(x+y)%2?P.floorA:P.floorB;ctx.fillRect(s.x,s.y,C.tile,C.tile);ctx.fillStyle="rgba(255,255,255,.025)";ctx.fillRect(s.x+6,s.y+7,2,2)}else{ctx.fillStyle="#282054";ctx.fillRect(s.x,s.y,C.tile,C.tile);ctx.fillStyle=P.wall;ctx.fillRect(s.x+2,s.y+2,C.tile-4,C.tile-4);ctx.fillStyle=P.wallHi;ctx.fillRect(s.x+3,s.y+3,C.tile-6,4);ctx.fillStyle="rgba(0,0,0,.25)";ctx.fillRect(s.x+C.tile-4,s.y+5,4,C.tile-5);ctx.fillRect(s.x+5,s.y+C.tile-4,C.tile-5,4)}}
function label(t,s,col=P.white){ctx.save();ctx.font='bold 7px "Courier New"';const w=Math.min(96,ctx.measureText(t).width+6);ctx.fillStyle="rgba(5,3,8,.85)";ctx.fillRect(s.x+15-w/2,s.y-8,w,9);ctx.fillStyle=col;ctx.textAlign="center";ctx.fillText(t,s.x+15,s.y-1);ctx.restore()}
function drawExit(){const s=ws(world.exit.x,world.exit.y),on=host.exitOpen,p=2+Math.sin(performance.now()/160)*2;ctx.save();ctx.strokeStyle=on?P.purple:"#66586e";ctx.lineWidth=3;ctx.shadowColor=on?P.purple:"transparent";ctx.shadowBlur=on?12:0;ctx.strokeRect(s.x+7-p/2,s.y+5-p/2,16+p,20+p);ctx.restore()}
function drawItem(i){if(!i.active)return;const s=ws(i.x,i.y),col=i.kind==="key"?P.gold:i.kind==="health"?P.green:i.kind==="mana"?P.cyan:i.kind==="sensor"?P.blue:P.orange;ctx.save();ctx.shadowColor=col;ctx.shadowBlur=8;ctx.fillStyle=col;ctx.fillRect(s.x+9,s.y+9,12,12);ctx.restore()}
function drawEnemy(e){if(!e.alive)return;if(e.kind==="ghost"&&player.sensorMs<=0&&e.aiState==="idle")return;let v=visuals.get(e.id);if(!v){v={x:e.x,y:e.y};visuals.set(e.id,v)}v.x+=(e.x-v.x)*.15;v.y+=(e.y-v.y)*.15;const s=ws(v.x,v.y),f=e.follower,img=f?avatars.get(f.name):null;ctx.fillStyle="rgba(0,0,0,.35)";ctx.beginPath();ctx.ellipse(s.x+15,s.y+25,11,4,0,0,Math.PI*2);ctx.fill();if(img?.complete&&img.naturalWidth){ctx.save();ctx.beginPath();ctx.arc(s.x+15,s.y+15,12,0,Math.PI*2);ctx.clip();ctx.drawImage(img,s.x+3,s.y+3,24,24);ctx.restore();ctx.strokeStyle=P.gold;ctx.strokeRect(s.x+3,s.y+3,24,24)}else{ctx.fillStyle=f?P.gold:e.kind==="ghost"?P.red:P.pink;ctx.fillRect(s.x+6,s.y+6,18,20)}label(f?.name||e.kind,s,f?P.gold:P.white);if(e.aiState==="chase"||e.aiState==="search"){ctx.fillStyle=e.aiState==="chase"?P.red:P.gold;ctx.font='bold 14px "Courier New"';ctx.textAlign="center";ctx.fillText(e.aiState==="chase"?"!":"?",s.x+15,s.y-12)}}
function drawPlayer(p,local=true){const s=ws(p.rx??p.x,p.ry??p.y),col=local?P.gold:P.cyan;ctx.fillStyle="rgba(0,0,0,.36)";ctx.beginPath();ctx.ellipse(s.x+15,s.y+26,12,4,0,0,Math.PI*2);ctx.fill();ctx.save();ctx.translate(s.x+15,s.y+15);ctx.strokeStyle=col;ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,18,0,Math.PI*2);ctx.stroke();if(logo.complete&&logo.naturalWidth){const r=logo.naturalWidth/logo.naturalHeight;let w=40,h=w/r;if(h>24){h=24;w=h*r}ctx.drawImage(logo,-w/2,-h/2,w,h)}else{ctx.fillStyle=P.gold;ctx.font='bold 10px "Courier New"';ctx.textAlign="center";ctx.fillText("CCG",0,3)}ctx.restore();label(p.name,{x:s.x,y:s.y-2},col)}
function drawShots(){ctx.save();ctx.lineCap="round";for(const b of bullets){const s=ws(b.x,b.y);ctx.strokeStyle=P.orange;ctx.shadowColor=P.orange;ctx.shadowBlur=9;ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(s.x+15-b.dx*10,s.y+15-b.dy*10);ctx.lineTo(s.x+15,s.y+15);ctx.stroke()}for(const b of enemyBullets){const s=ws(b.x,b.y),col=b.style==="root"?P.green:b.style==="food"?P.orange:b.style==="fire"?P.gold:P.red;ctx.strokeStyle=col;ctx.lineWidth=b.style==="fire"?7:4;ctx.beginPath();ctx.moveTo(s.x+15-b.dx*10,s.y+15-b.dy*10);ctx.lineTo(s.x+15,s.y+15);ctx.stroke()}ctx.restore()}
function drawHazards(){for(const h of hazards){const s=ws(h.x,h.y),t=1-h.life/h.max;ctx.strokeStyle=P.red;ctx.lineWidth=2;ctx.globalAlpha=.4+.5*Math.abs(Math.sin(performance.now()/80));ctx.beginPath();ctx.arc(s.x+15,s.y+15,8+t*8,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1}}
function drawFX(dt){for(const q of particles){q.x+=q.vx;q.y+=q.vy;q.life-=dt;ctx.globalAlpha=Math.max(0,q.life/400);ctx.fillStyle=q.col;ctx.fillRect(q.x-camera.x,q.y-camera.y,q.size,q.size)}ctx.globalAlpha=1;for(let i=particles.length-1;i>=0;i--)if(particles[i].life<=0)particles.splice(i,1);for(const r of rings){r.life-=dt;r.r+=(r.max-r.r)*.12;ctx.globalAlpha=Math.max(0,r.life/330);ctx.strokeStyle=r.col;ctx.beginPath();ctx.arc(r.x-camera.x,r.y-camera.y,r.r,0,Math.PI*2);ctx.stroke()}ctx.globalAlpha=1;for(let i=rings.length-1;i>=0;i--)if(rings[i].life<=0)rings.splice(i,1)}
function minimap(){const sc=1.5,ox=canvas.width-C.worldWidth*sc-8,oy=8;ctx.fillStyle="rgba(5,3,8,.82)";ctx.fillRect(ox-4,oy-4,C.worldWidth*sc+8,C.worldHeight*sc+8);for(let y=0;y<C.worldHeight;y++)for(let x=0;x<C.worldWidth;x++){ctx.fillStyle=world.map[y][x]?"#51456b":"#21182b";ctx.fillRect(ox+x*sc,oy+y*sc,sc,sc)}for(const e of host.enemies)if(e.alive&&(e.kind==="ghost"||player.sensorMs>0)){ctx.fillStyle=e.kind==="ghost"?P.red:P.orange;ctx.fillRect(ox+e.x*sc,oy+e.y*sc,2,2)}ctx.fillStyle=P.gold;ctx.fillRect(ox+player.x*sc,oy+player.y*sc,3,3)}
function render(dt=16){if(!world||!player)return;updateCamera();ctx.save();if(shake>0){ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.84}ctx.fillStyle="#030205";ctx.fillRect(0,0,canvas.width,canvas.height);const x0=Math.max(0,Math.floor(camera.x/C.tile)-1),x1=Math.min(C.worldWidth-1,Math.ceil((camera.x+canvas.width)/C.tile)+1),y0=Math.max(0,Math.floor(camera.y/C.tile)-1),y1=Math.min(C.worldHeight-1,Math.ceil((camera.y+canvas.height)/C.tile)+1);for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++)drawTile(x,y);drawExit();drawHazards();host.items.forEach(drawItem);host.enemies.forEach(drawEnemy);drawShots();for(const p of remote.values())if(performance.now()-p.lastSeen<2600)drawPlayer(p,false);drawPlayer(player,true);drawFX(dt);minimap();const ps=ws(player.rx,player.ry),g=ctx.createRadialGradient(ps.x+15,ps.y+15,90,ps.x+15,ps.y+15,580);g.addColorStop(0,"rgba(0,0,0,0)");g.addColorStop(.65,"rgba(0,0,0,.12)");g.addColorStop(1,"rgba(0,0,0,.6)");ctx.fillStyle=g;ctx.fillRect(0,0,canvas.width,canvas.height);if(damageFlash>0){ctx.fillStyle=`rgba(255,45,65,${Math.min(.22,damageFlash)})`;ctx.fillRect(0,0,canvas.width,canvas.height)}ctx.restore()}
function loop(t){const dt=Math.min(45,t-last||16);last=t;update(dt);render(dt);requestAnimationFrame(loop)}
function pause(force=false){if(mode==="playing"&&!force){mode="paused";UI.pause.classList.remove("hidden")}else if(mode==="paused"){mode="playing";UI.pause.classList.add("hidden");keys.clear()}}
function toggleSound(){S.toggle();sync()}
$("solo-btn").addEventListener("click",startSolo);$("create-btn").addEventListener("click",createRoom);$("join-btn").addEventListener("click",joinRoom);$("resume-btn").addEventListener("click",()=>pause(true));$("again-btn").addEventListener("click",async()=>{UI.end.classList.add("hidden");await net.leave();UI.menu.classList.remove("hidden");mode="menu"});UI.sound.addEventListener("click",toggleSound);
addEventListener("keydown",e=>{if(["ArrowUp","ArrowDown","ArrowLeft","ArrowRight","Space"].includes(e.code))e.preventDefault();if(e.code==="KeyP"&&(mode==="playing"||mode==="paused")){pause();return}if(e.code==="KeyM"){toggleSound();return}setDir(e.code);keys.add(e.code);if(e.code==="Space"&&!e.repeat)fire();if((e.code==="ShiftLeft"||e.code==="ShiftRight")&&!e.repeat)dash()},{passive:false});addEventListener("keyup",e=>keys.delete(e.code));addEventListener("blur",()=>keys.clear());
startWorld("TITLE");mode="menu";requestAnimationFrame(loop);
})();
