(()=>{
"use strict";
const C=window.CCG_CONFIG,W=window.CCGWorld,A=window.CCGAI,S=window.CCGSound,$=id=>document.getElementById(id);
const canvas=$("game"),ctx=canvas.getContext("2d");ctx.imageSmoothingEnabled=false;
const UI={health:$("hud-health"),p2:$("hud-p2"),mana:$("hud-mana"),keys:$("hud-keys"),bronze:$("hud-bronze"),weapon:$("hud-weapon"),score:$("hud-score"),room:$("hud-room"),mission:$("mission-text"),net:$("net-status"),sound:$("sound-btn"),message:$("message"),list:$("player-list"),quests:$("quest-list"),loadout:$("loadout"),surroundings:$("surroundings"),menu:$("menu"),pause:$("pause"),end:$("end"),endTitle:$("end-title"),endText:$("end-text"),name:$("player-name"),roomCode:$("room-code"),note:$("menu-note"),toast:$("pickup-toast"),toastTitle:$("pickup-title"),toastText:$("pickup-text")};
const logo=new Image();logo.onerror=()=>{if(!logo.src.endsWith(C.logoFallback))logo.src=C.logoFallback};logo.src=C.logoAsset;
const avatarImages=new Map();for(const f of C.followerElites)if(f.avatar){const im=new Image();im.src=f.avatar.startsWith("embedded:")?(window.CCG_AVATAR_DATA?.[f.avatar.slice(9)]||""):f.avatar;avatarImages.set(f.name,im)}
const P={purple:"#b978ff",gold:"#ffd85a",cyan:"#6cecff",green:"#72ff9b",pink:"#ff5bae",red:"#ff6868",orange:"#ff9950",white:"#faf4ff",blue:"#6aa9ff",brown:"#9b6134",black:"#030205"};
const input=new Set(),remote=new Map(),bullets=[],enemyBullets=[],particles=[],rings=[],floaters=[],hazards=[],pendingItems=new Set(),enemyVisuals=new Map(),cameras=new Map(),explored=new Map(),campStates=new Map();
let mode="menu",playMode="solo",world=null,host=null,p1=null,p2=null,score=0,last=0,enemyCD=0,projectileCD=0,sendCD=0,worldCD=0,surroundCD=0,move1=0,move2=0,fire1=0,fire2=0,won=false,shake=0,damageFlash=0,renderShake={x:0,y:0},toastTimer=0,lowHealthCD=0;
let view={x:0,y:0,w:canvas.width,h:canvas.height},focus=null,cam={x:0,y:0};
const stats={games:0,elites:0,doors:0,weapons:0},questDone=new Set();
const net=new window.CCGNetwork.RoomNetwork({onMembers,onPacket});
const esc=v=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const pad=n=>String(Math.max(0,Math.floor(n))).padStart(6,"0"),md=(a,b)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
const localPlayers=()=>[p1,p2].filter(Boolean), findLocal=id=>localPlayers().find(p=>p.id===id)||null;
const allPlayers=()=>{const a=[...localPlayers()],now=performance.now();for(const p of remote.values())if(now-p.lastSeen<2600)a.push(p);return a};
function say(s){UI.message.innerHTML=s}
function showToast(title,text,tone="gold"){UI.toast.className=`pickup-toast ${tone}`;UI.toastTitle.textContent=title;UI.toastText.textContent=text;requestAnimationFrame(()=>UI.toast.classList.add("show"));toastTimer=2300}
function playerName(){return String(UI.name.value||"CCG Player").trim().slice(0,18)||"CCG Player"}
function makePlayer(id,name,x,y){return{id,name,x,y,rx:x,ry:y,health:C.player.maxHealth,maxHealth:C.player.maxHealth,mana:C.player.maxMana,maxMana:C.player.maxMana,armor:0,bronzeKeys:0,potions:0,weaponLevel:1,dir:{x:1,y:0},invuln:0,sensorMs:0,torchMs:0,rapidMs:0,lastRoom:-99}}
function nearbyOpen(x,y,avoid=[]){for(let r=1;r<7;r++)for(let dy=-r;dy<=r;dy++)for(let dx=-r;dx<=r;dx++){const nx=x+dx,ny=y+dy;if(W.walkable(world.map,nx,ny,host)&&!avoid.some(p=>p.x===nx&&p.y===ny))return{x:nx,y:ny}}return{x,y}}
function resetCamp(p){campStates.set(p.id,{anchorX:p.x,anchorY:p.y,room:W.roomAt(world,p.x,p.y),elapsed:0,active:false,nextBlast:0})}
function reveal(p){let ex=explored.get(p.id);if(!ex){ex=new Set();explored.set(p.id,ex)}const r=p.torchMs>0?C.player.torchRadius:C.player.sightRadius;for(let y=Math.max(0,p.y-r);y<=Math.min(C.worldHeight-1,p.y+r);y++)for(let x=Math.max(0,p.x-r);x<=Math.min(C.worldWidth-1,p.x+r);x++)if(Math.hypot(x-p.x,y-p.y)<=r+.2&&A.lineOfSight(world.map,p,{x,y},r,host))ex.add(`${x},${y}`)}
function startWorld(seed,split=false){world=W.generate(seed);host=W.createHostState(world);p1=makePlayer(net.sessionId,playerName(),world.start.x,world.start.y);p2=null;if(split){const q=nearbyOpen(world.start.x+2,world.start.y,[p1]);p2=makePlayer("LOCAL-P2","PLAYER 2",q.x,q.y)}score=0;won=false;remote.clear();enemyVisuals.clear();bullets.length=enemyBullets.length=particles.length=rings.length=floaters.length=hazards.length=0;pendingItems.clear();cameras.clear();explored.clear();campStates.clear();questDone.clear();stats.games=stats.elites=stats.doors=stats.weapons=0;shake=damageFlash=0;move1=move2=fire1=fire2=0;for(const p of localPlayers()){resetCamp(p);reveal(p);updateRoomMessage(p,true)}sync()}
async function startSolo(){await S.start();S.startMusic();net.setSolo(playerName());playMode="solo";startWorld("SOLO-ADVENTURE",false);mode="playing";UI.menu.classList.add("hidden");S.sfx("join");say("<strong>SOLO MODE.</strong> Three main keys, optional treasure vaults and rather too many eyes in the dark.")}
async function startSplit(){await S.start();S.startMusic();net.setSolo(`${playerName()} + P2`);playMode="split";startWorld("LOCAL-SPLIT-ADVENTURE",true);mode="playing";UI.menu.classList.add("hidden");S.sfx("join");showToast("2 PLAYER SPLIT SCREEN","Friendly fire is ON. Try to remain friends.","cyan");say("<strong>LOCAL CO-OP.</strong> Two players, one dungeon, and absolutely no guarantee you won't shoot each other.")}
async function createRoom(){await S.start();S.startMusic();const c=net.createCode();UI.note.textContent="Creating room…";try{playMode="online";startWorld(c,false);const r=await net.join(c,playerName());mode="playing";UI.roomCode.value=c;UI.menu.classList.add("hidden");S.sfx("join");say(`<strong>ROOM ${c}</strong> created using ${r.transport==="supabase"?"internet":"local"} co-op. Friendly fire is enabled.`);if(net.isHost)broadcastWorld();sync()}catch(e){mode="menu";UI.note.textContent=e.message}}
async function joinRoom(){await S.start();S.startMusic();const c=window.CCGNetwork.cleanCode(UI.roomCode.value);if(c.length<4){UI.note.textContent="Enter the room code from the host.";return}try{playMode="online";startWorld(c,false);const r=await net.join(c,playerName());mode="playing";UI.menu.classList.add("hidden");S.sfx("join");say(`<strong>JOINED ${c}</strong> using ${r.transport==="supabase"?"internet":"local"} co-op. Watch your fire.`);sync()}catch(e){mode="menu";UI.note.textContent=e.message}}
function sync(){if(!p1||!host)return;UI.health.textContent=`${p1.health}/${p1.maxHealth}`;UI.p2.textContent=p2?`${p2.health}/${p2.maxHealth}`:`ARM ${p1.armor}`;UI.mana.textContent=`${p1.mana}/${p1.maxMana}`;UI.keys.textContent=`${host.keysCollected}/${C.keyTarget}`;UI.bronze.textContent=p1.bronzeKeys+(p2?` + ${p2.bronzeKeys}`:"");UI.weapon.textContent=`LV${p1.weaponLevel}${p2?` / ${p2.weaponLevel}`:""}`;UI.score.textContent=pad(score);UI.room.textContent=playMode==="online"?net.roomCode:playMode==="split"?"SPLIT":"SOLO";UI.net.textContent=playMode==="online"?(net.transport==="supabase"?(net.isHost?"ONLINE • HOST":"ONLINE • CO-OP"):(net.isHost?"LOCAL ROOM • HOST":"LOCAL ROOM • CO-OP")):playMode==="split"?"LOCAL SPLIT":"SOLO";UI.net.classList.toggle("online",playMode==="online"&&net.connected);UI.mission.textContent=host.exitOpen?"Main vault open — reach the pulsing purple exit.":`Find the three main vault keys (${host.keysCollected}/${C.keyTarget}). Bronze keys only open optional treasure rooms.`;UI.sound.textContent=S.isEnabled()?"SOUND ON":"SOUND OFF";UI.loadout.innerHTML=`P1: Weapon LV${p1.weaponLevel} • Armour ${p1.armor} • Potions ${p1.potions} • ${p1.torchMs>0?"TORCH ACTIVE":"No torch"}${p2?`<br>P2: Weapon LV${p2.weaponLevel} • Armour ${p2.armor} • Potions ${p2.potions} • ${p2.torchMs>0?"TORCH ACTIVE":"No torch"}`:""}`;const rows=net.getMembers();UI.list.innerHTML=playMode==="split"?"P1 + PLAYER 2":(rows.length?rows.map((m,i)=>`${esc(m.name)}${i===0?" ★":""}`).join("<br>"):"");updateQuests()}
function updateQuests(){const q=[{id:"games",label:"Rescue 3 C64 games",v:stats.games,t:3},{id:"elites",label:"Free 2 named followers",v:stats.elites,t:2},{id:"doors",label:"Open 1 bronze treasure door",v:stats.doors,t:1},{id:"weapons",label:"Find a weapon upgrade",v:stats.weapons,t:1}];for(const x of q)if(x.v>=x.t&&!questDone.has(x.id)){questDone.add(x.id);score+=350;showToast("SIDE QUEST COMPLETE",`${x.label} — 350 bonus points.`,"green");S.sfx("key")}UI.quests.innerHTML=q.map(x=>`<div class="${x.v>=x.t?"quest-done":""}">${x.v>=x.t?"✓ ":""}${x.label} <b>${Math.min(x.v,x.t)}/${x.t}</b></div>`).join("")}
function onMembers(members,isHost,changed){if(changed&&isHost&&mode==="playing"){say("<strong>HOST MIGRATION.</strong> You're now running the dungeon simulation.");broadcastWorld()}sync()}
function onPacket(event,p){if(event==="player")onPlayer(p);else if(event==="shot")spawnBullet(p,true);else if(event==="enemy_shot")spawnEnemyShot(p);else if(event==="hit")onHit(p);else if(event==="player_hit"&&p?.target===p1?.id)hurtPlayer(p1,p.power||1,true,p.source||"another player");else if(event==="collect")onCollectRequest(p);else if(event==="collected")onCollected(p);else if(event==="world")onWorld(p);else if(event==="hello"&&net.isHost)broadcastWorld();else if(event==="notice")say(p?.html||"");else if(event==="fx")onFX(p);else if(event==="complete")finish(p?.by||"the team")}
function onPlayer(p){if(!p||p.id===net.sessionId)return;const old=remote.get(p.id);remote.set(p.id,{...p,rx:old?.rx??p.x,ry:old?.ry??p.y,lastSeen:performance.now()})}
function sendPlayer(){if(playMode!=="online")return;net.send("player",{id:p1.id,name:p1.name,x:p1.x,y:p1.y,health:p1.health,dir:p1.dir,torchMs:p1.torchMs,armor:p1.armor})}
function serialWorld(){return{revision:host.revision,keysCollected:host.keysCollected,exitOpen:host.exitOpen,doors:host.doors.map(d=>({...d})),enemies:host.enemies.map(e=>({...e,lastSeen:e.lastSeen?{...e.lastSeen}:null,follower:e.follower||null})),items:host.items.map(i=>({...i}))}}
function broadcastWorld(){if(playMode==="online"&&net.connected&&net.isHost)net.send("world",serialWorld())}
function onWorld(s){if(!s||net.isHost)return;if(!host||Number(s.revision)>=Number(host.revision)){host={revision:Number(s.revision||0),keysCollected:Number(s.keysCollected||0),exitOpen:Boolean(s.exitOpen),doors:Array.isArray(s.doors)?s.doors:[],enemies:Array.isArray(s.enemies)?s.enemies:[],items:Array.isArray(s.items)?s.items:[]};sync()}}
function hostEnemyStep(dt){if(!net.isHost)return;A.stepEnemies(host,world.map,allPlayers(),dt,{shoot:s=>{spawnEnemyShot(s);if(playMode==="online")net.send("enemy_shot",s)},melee:(e,target,power)=>{const lp=findLocal(target.id);if(lp)hurtPlayer(lp,power,false,e.follower?.name||e.kind);else if(playMode==="online")net.send("player_hit",{target:target.id,power,source:e.follower?.name||e.kind})},notice:(html,sound)=>{say(html);if(sound)S.sfx(sound);if(playMode==="online")net.send("notice",{html})},alert:(e,state)=>{const near=localPlayers().some(p=>md(e,p)<9);if(state==="alert"&&near){S.sfx("alert");floatText(e.x,e.y,"!",P.red)}if(state==="search"&&near)S.sfx("search")}})}
function onHit(p){if(!net.isHost||!p?.enemyId)return;const e=host.enemies.find(x=>x.id===p.enemyId&&x.alive);if(e){if(p.source)A.alertEnemy(e,p.source.x,p.source.y);damageEnemy(e,Math.max(1,Math.min(4,Number(p.power||1))))}}
function damageEnemy(e,power){if(!e.alive)return;e.hp-=power;e.flash=160;S.sfx("hit");burst(e.x,e.y,P.orange,8,1.2);ring(e.x,e.y,P.orange,20);floatText(e.x,e.y,`-${power}`,P.white);if(e.hp<=0){e.hp=0;e.alive=false;host.revision++;score+=e.follower?500:120;if(e.follower)stats.elites++;const fx={type:"death",x:e.x,y:e.y,color:e.follower?P.gold:P.pink,elite:Boolean(e.follower)};onFX(fx);if(playMode==="online")net.send("fx",fx);if(e.follower){S.sfx("elite");showToast(`${e.follower.name.toUpperCase()} FREED`,`The Score Goblin's influence has worn off. +500 points.`,"green");if(e.follower.name==="CPU")host.items.push({id:`food-${Date.now()}`,x:e.x,y:e.y,kind:"health",active:true,title:"CPU's Emergency Roast"})}else S.sfx("death");updateQuests();broadcastWorld()}}
function onFX(p){if(!p)return;if(p.type==="death"){burst(p.x,p.y,p.color||P.pink,p.elite?28:18,p.elite?1.8:1.35);ring(p.x,p.y,p.color||P.pink,p.elite?42:30);shake=Math.max(shake,p.elite?11:6);floatText(p.x,p.y,p.elite?"FREED!":"ZAPPED!",p.color||P.gold)}}
function onCollectRequest(p){if(!net.isHost||!p?.itemId)return;const i=host.items.find(x=>x.id===p.itemId&&x.active);if(!i)return;i.active=false;if(i.kind==="key"){host.keysCollected=Math.min(C.keyTarget,host.keysCollected+1);host.exitOpen=host.keysCollected>=C.keyTarget}host.revision++;const ev={item:{...i},collector:p.collector};onCollected(ev);if(playMode==="online")net.send("collected",ev);broadcastWorld();sync()}
function requestCollect(i,p){if(!i.active||pendingItems.has(i.id))return;pendingItems.add(i.id);if(playMode==="online"&&p.id===p1.id&&!net.isHost)net.send("collect",{itemId:i.id,collector:p.id});else onCollectRequest({itemId:i.id,collector:p.id});setTimeout(()=>pendingItems.delete(i.id),500)}
function onCollected(ev){const i=ev?.item;if(!i)return;const p=findLocal(ev.collector);ring(i.x,i.y,i.kind==="key"?P.gold:i.kind==="health"?P.green:i.kind==="mana"?P.cyan:P.white,34);burst(i.x,i.y,P.gold,14,1.2);if(!p){if(i.kind==="key"){S.sfx("key");say(`<strong>TEAM KEY FOUND.</strong> ${host.keysCollected}/${C.keyTarget}.`)}return}applyItem(i,p);sync()}
function applyItem(i,p){const who=p===p2?"P2":"P1";if(i.kind==="health"){p.health=Math.min(p.maxHealth,p.health+3);S.sfx("pickup");showToast("HEALTH PACK",`${who} restores 3 health.`,"green")}else if(i.kind==="mana"){p.mana=Math.min(p.maxMana,p.mana+5);S.sfx("pickup");showToast("MANA CELL",`${who} gains 5 mana.`,"cyan")}else if(i.kind==="game"){score+=250;stats.games++;S.sfx("pickup");showToast(`C64 RESCUED: ${i.title}`,"Onto the CCG shelf. +250 points.","gold")}else if(i.kind==="credits"){score+=125;S.sfx("pickup");showToast("CCG TOKEN","125 points. The arcade manager looks disappointed.","gold")}else if(i.kind==="sensor"){p.sensorMs=10000;S.sfx("cloak");showToast("RADAR BOOST","Hidden threats appear on the minimap for 10 seconds.","cyan")}else if(i.kind==="torch"){p.torchMs=C.player.torchMs;S.sfx("torch");showToast("TORCH LIT","Vision expands for 16 seconds — but enemies can spot the glow from farther away.","gold")}else if(i.kind==="armour"){p.armor=Math.min(6,p.armor+2);S.sfx("armour");showToast("ARMOUR PLATE",`${who} gains 2 armour. Armour absorbs incoming damage first.`,"cyan")}else if(i.kind==="potion"){p.potions++;S.sfx("potion");showToast("RESTORATION POTION",`${who} stores a potion. P1: E • P2: O`,"green")}else if(i.kind==="weapon"){p.weaponLevel=Math.min(3,p.weaponLevel+1);stats.weapons++;S.sfx("weapon");showToast(`WEAPON UPGRADE LV${p.weaponLevel}`,p.weaponLevel===2?"Shots now hit harder.":"Triple-shot unlocked and more projectiles can be active.","gold")}else if(i.kind==="rapid"){p.rapidMs=12000;S.sfx("weapon");showToast("RAPID FIRE","Fire delay reduced for 12 seconds.","gold")}else if(i.kind==="bronze"){p.bronzeKeys++;S.sfx("bronze");showToast("BRONZE KEY","Opens one optional treasure door. Main quest keys are separate.","gold")}else if(i.kind==="treasure"){S.sfx("weapon");showToast("TREASURE VAULT",`Bonus reward: ${i.reward.toUpperCase()}.`,"gold");applyItem({kind:i.reward,title:"Vault Reward"},p)}else if(i.kind==="key"){score+=400;S.sfx("key");shake=7;showToast("MAIN VAULT KEY",`${host.keysCollected}/${C.keyTarget} recovered. These keys never spawn behind locked bonus doors.`,"gold");if(host.exitOpen){setTimeout(()=>S.sfx("open"),150);say("<strong>MAIN VAULT OPEN.</strong> The purple exit is now active.")}}updateQuests()}
function usePotion(p){if(!p||p.potions<=0){S.sfx("empty");showToast("NO POTION","You appear to have drunk the last one already.","red");return}p.potions--;p.health=Math.min(p.maxHealth,p.health+4);p.mana=Math.min(p.maxMana,p.mana+4);S.sfx("potion");showToast("POTION USED","+4 health and +4 mana.","green");sync()}
function d1(){if(input.has("ArrowLeft")||input.has("KeyA"))return{x:-1,y:0};if(input.has("ArrowRight")||input.has("KeyD"))return{x:1,y:0};if(input.has("ArrowUp")||input.has("KeyW"))return{x:0,y:-1};if(input.has("ArrowDown")||input.has("KeyS"))return{x:0,y:1};return null}
function d2(){if(input.has("KeyJ"))return{x:-1,y:0};if(input.has("KeyL"))return{x:1,y:0};if(input.has("KeyI"))return{x:0,y:-1};if(input.has("KeyK"))return{x:0,y:1};return null}
function setDir(p,code){const m=p===p2?{KeyJ:{x:-1,y:0},KeyL:{x:1,y:0},KeyI:{x:0,y:-1},KeyK:{x:0,y:1}}:{ArrowLeft:{x:-1,y:0},KeyA:{x:-1,y:0},ArrowRight:{x:1,y:0},KeyD:{x:1,y:0},ArrowUp:{x:0,y:-1},KeyW:{x:0,y:-1},ArrowDown:{x:0,y:1},KeyS:{x:0,y:1}};if(m[code])p.dir=m[code]}
function tryDoor(p,x,y){const d=W.doorAt(host,x,y);if(!d?.locked)return true;if(p.bronzeKeys<=0){S.sfx("locked");showToast("LOCKED TREASURE DOOR","You need a bronze key. The main quest never requires this room.","red");return false}p.bronzeKeys--;d.locked=false;host.revision++;stats.doors++;S.sfx("door");shake=5;showToast("TREASURE DOOR OPENED","Bronze key used. This chamber is optional, so you can never be trapped by it.","gold");updateQuests();broadcastWorld();return true}
function movePlayer(p,dx,dy,dash=false){if(mode!=="playing"||!p)return;p.dir={x:dx,y:dy};const ox=p.x,oy=p.y;for(let n=0;n<(dash?2:1);n++){const warp=W.tunnelDestination(world,p.x,p.y,dx,dy);if(warp){p.x=warp.x;p.y=warp.y;p.rx=warp.x;p.ry=warp.y;S.sfx("warp");burst(p.x,p.y,P.cyan,18,1.2);continue}const nx=p.x+dx,ny=p.y+dy;if(!tryDoor(p,nx,ny))break;if(!W.walkable(world.map,nx,ny,host)){if(n===0)S.sfx("wall");break}p.x=nx;p.y=ny;for(const i of host.items)if(i.active&&i.x===nx&&i.y===ny)requestCollect(i,p);for(const e of host.enemies)if(e.alive&&e.x===nx&&e.y===ny)hurtPlayer(p,e.follower?2:1,false,e.follower?.name||e.kind);if(host.exitOpen&&nx===world.exit.x&&ny===world.exit.y){if(playMode==="online")net.send("complete",{by:p.name});finish(p.name);return}updateRoomMessage(p,false);reveal(p)}if(dash){S.sfx("dash");trailBetween(ox,oy,p.x,p.y,p===p2?P.green:P.cyan)}}
function dashPlayer(p,d){if(!p||!d||mode!=="playing")return;if(p.mana<2){S.sfx("empty");showToast("NOT ENOUGH MANA","Dash costs 2 mana.","red");return}p.mana-=2;movePlayer(p,d.x,d.y,true);sync()}
function firePlayer(p,d){if(!p||mode!=="playing")return;const cd=p===p2?fire2:fire1;if(cd>0)return;const active=bullets.filter(b=>b.owner===p.id&&b.ttl>0).length,max=C.player.maxProjectiles+(p.weaponLevel-1);if(active>=max){S.sfx("empty");return}if(p.mana<=0){S.sfx("empty");showToast("NO MANA","The fire button has filed for unpaid leave.","red");return}d=d||p.dir||{x:1,y:0};p.dir=d;p.mana--;const delay=p.rapidMs>0?105:C.player.fireDelay;if(p===p2)fire2=delay;else fire1=delay;const dirs=[d];if(p.weaponLevel>=3){if(d.x!==0)dirs.push({x:d.x,y:1},{x:d.x,y:-1});else dirs.push({x:1,y:d.y},{x:-1,y:d.y})}for(const z of dirs.slice(0,Math.max(1,max-active))){const b={id:`${p.id}-${Date.now()}-${Math.random()}`,owner:p.id,ownerName:p.name,x:p.x,y:p.y,dx:z.x,dy:z.y,ttl:14,power:p.weaponLevel>=2?2:1};spawnBullet(b,false);if(playMode==="online"&&p===p1)net.send("shot",b)}S.sfx("fire");muzzle(p.x,p.y,d);sync()}
function spawnBullet(b,remoteShot){if(b)bullets.push({...b,remote:!!remoteShot})}
function spawnEnemyShot(b){if(!b)return;enemyBullets.push({...b,ttl:Number(b.ttl||14)});if(localPlayers().some(p=>md(b,p)<9))S.sfx(b.style==="food"?"food":b.style==="fire"?"flame":"enemy")}
function stepProjectiles(){for(const b of bullets){if(b.ttl<=0)continue;const nx=b.x+b.dx,ny=b.y+b.dy;if(!W.walkable(world.map,nx,ny,host)){b.ttl=0;continue}b.x=nx;b.y=ny;b.ttl--;const e=host.enemies.find(e=>e.alive&&e.x===Math.round(nx)&&e.y===Math.round(ny));if(e){b.ttl=0;if(b.owner===p1.id||b.owner===p2?.id){if(net.isHost)damageEnemy(e,b.power);else if(playMode==="online")net.send("hit",{enemyId:e.id,power:b.power,source:{x:b.x,y:b.y}})}continue}for(const lp of localPlayers())if(lp.id!==b.owner&&Math.round(nx)===lp.x&&Math.round(ny)===lp.y){b.ttl=0;hurtPlayer(lp,1,true,b.ownerName||"your co-op partner");break}}for(const b of enemyBullets){if(b.ttl<=0)continue;const nx=b.x+b.dx,ny=b.y+b.dy;if(!W.walkable(world.map,nx,ny,host)){b.ttl=0;continue}b.x=nx;b.y=ny;b.ttl--;if(b.style==="fire")burst(nx,ny,Math.random()<.5?P.orange:P.gold,3,.6);for(const lp of localPlayers())if(Math.round(nx)===lp.x&&Math.round(ny)===lp.y){b.ttl=0;hurtPlayer(lp,Number(b.power||1),false,b.source||"enemy");break}}for(let i=bullets.length-1;i>=0;i--)if(bullets[i].ttl<=0)bullets.splice(i,1);for(let i=enemyBullets.length-1;i>=0;i--)if(enemyBullets[i].ttl<=0)enemyBullets.splice(i,1)}
function hurtPlayer(p,n,friendly=false,source="enemy"){if(!p||p.invuln>0||mode!=="playing")return;let left=n;if(p.armor>0){const a=Math.min(p.armor,left);p.armor-=a;left-=a;if(a){S.sfx("armour");floatText(p.x,p.y,"ARMOUR",P.cyan)}}if(left<=0){p.invuln=350;sync();return}p.health-=left;p.invuln=850;shake=10;damageFlash=.5;S.sfx("hurt");burst(p.x,p.y,P.red,16,1.4);ring(p.x,p.y,P.red,30);if(friendly){showToast("FRIENDLY FIRE",`${source} just shot a team-mate. Very cooperative.`,"red");say("<strong>FRIENDLY FIRE.</strong> The enemy has requested that you continue doing its work.")}if(p.health<=0){p.health=p.maxHealth;p.mana=p.maxMana;p.x=world.start.x;p.y=world.start.y;p.rx=p.x;p.ry=p.y;score=Math.max(0,score-500);S.sfx("respawn");showToast(`${p.name} RESPAWNS`,"Minus 500 points. Consider it a very visible trainer option.","cyan")}sync()}
function updateCamping(p,dt){let c=campStates.get(p.id);if(!c){resetCamp(p);c=campStates.get(p.id)}const room=W.roomAt(world,p.x,p.y),moved=Math.hypot(p.x-c.anchorX,p.y-c.anchorY);if(room!==c.room||moved>=C.camping.resetDistance){resetCamp(p);return}c.elapsed+=dt;if(c.elapsed<C.camping.graceMs)return;if(!c.active){c.active=true;c.nextBlast=200;S.sfx("campwarn");showToast("THE VAULT HAS NOTICED YOU HIDING","Mini explosions will begin here. Move out of the area.","red")}c.nextBlast-=dt;if(c.nextBlast<=0){const a=[];for(let dy=-4;dy<=4;dy++)for(let dx=-4;dx<=4;dx++){const x=c.anchorX+dx,y=c.anchorY+dy;if(W.walkable(world.map,x,y,host)&&Math.hypot(dx,dy)<=4.2)a.push({x,y})}if(a.length){const q=a[Math.floor(Math.random()*a.length)];hazards.push({x:q.x,y:q.y,life:C.camping.warningMs,maxLife:C.camping.warningMs})}c.nextBlast=C.camping.blastIntervalMs}}
function updateHazards(dt){for(let i=hazards.length-1;i>=0;i--){const h=hazards[i];h.life-=dt;if(h.life>0)continue;hazards.splice(i,1);S.sfx("explosion");shake=9;burst(h.x,h.y,P.orange,24,1.8);ring(h.x,h.y,P.red,42);for(const p of localPlayers())if(Math.hypot(p.x-h.x,p.y-h.y)<=1.15)hurtPlayer(p,1,false,"vault explosion")}}
function updateRoomMessage(p,force){const r=W.roomAt(world,p.x,p.y);if(!force&&r===p.lastRoom)return;p.lastRoom=r;const th=W.themeAt(world,p.x,p.y);UI.surroundings.innerHTML=`<strong>${th.name}</strong> — ${th.message}`;if(!force){S.sfx("room");showToast(th.name,th.message,"cyan")}}
function surroundingsTick(){if(!p1)return;const p=p1,r=W.roomAt(world,p.x,p.y),hidden=host.enemies.filter(e=>e.alive&&W.roomAt(world,e.x,e.y)===r&&!visibleTo(p,e.x,e.y)).length;if(hidden>0)say(`<strong>YOU HEAR MOVEMENT.</strong> Something else is in the ${W.themeAt(world,p.x,p.y).name}.`);else if(p.torchMs>0)say("<strong>TORCHLIGHT.</strong> You can see farther, but anything with sight can spot that glow from farther away.");else if(host.doors.some(d=>d.locked&&md(d,p)<7))say("<strong>METAL CLUNK.</strong> There is a locked bronze treasure door nearby.");else say(`<strong>${W.themeAt(world,p.x,p.y).name.toUpperCase()}.</strong> ${W.themeAt(world,p.x,p.y).message}`)}
function visibleTo(p,x,y){const r=p.torchMs>0?C.player.torchRadius:C.player.sightRadius;return Math.hypot(x-p.x,y-p.y)<=r+.2&&A.lineOfSight(world.map,p,{x,y},r,host)}
function burst(tx,ty,col,n=10,power=1){for(let i=0;i<n;i++)particles.push({x:tx*C.tile+C.tile/2,y:ty*C.tile+C.tile/2,vx:(Math.random()-.5)*3.2*power,vy:(Math.random()-.5)*3.2*power,life:300+Math.random()*360,col,size:1.5+Math.random()*3*power,drag:.97})}
function ring(tx,ty,col,max=30){rings.push({x:tx*C.tile+C.tile/2,y:ty*C.tile+C.tile/2,r:3,max,life:340,col})}
function floatText(tx,ty,text,col=P.white){floaters.push({x:tx*C.tile+C.tile/2,y:ty*C.tile-3,text,life:720,col})}
function muzzle(tx,ty,d){for(let i=0;i<5;i++)particles.push({x:tx*C.tile+C.tile/2+d.x*12,y:ty*C.tile+C.tile/2+d.y*12,vx:d.x*(2+Math.random()*2)+(Math.random()-.5),vy:d.y*(2+Math.random()*2)+(Math.random()-.5),life:160,col:P.gold,size:2+Math.random()*2,drag:.94})}
function trailBetween(x1,y1,x2,y2,col){for(let i=0;i<8;i++){const t=i/7;particles.push({x:(x1+(x2-x1)*t)*C.tile+C.tile/2,y:(y1+(y2-y1)*t)*C.tile+C.tile/2,vx:0,vy:0,life:220+i*12,col,size:3,drag:.97})}}
function updateEffects(dt){for(const q of particles){q.x+=q.vx;q.y+=q.vy;q.vx*=q.drag;q.vy*=q.drag;q.life-=dt}for(let i=particles.length-1;i>=0;i--)if(particles[i].life<=0)particles.splice(i,1);for(const r of rings){r.life-=dt;r.r+=(r.max-r.r)*.12}for(let i=rings.length-1;i>=0;i--)if(rings[i].life<=0)rings.splice(i,1);for(const f of floaters){f.life-=dt;f.y-=dt*.018}for(let i=floaters.length-1;i>=0;i--)if(floaters[i].life<=0)floaters.splice(i,1)}
function finish(by){if(won)return;won=true;mode="ended";S.stopMusic();S.sfx("win");UI.endTitle.textContent="THE VAULT IS OPEN";UI.endText.innerHTML=`${esc(by)} reached the exit.<br><br><strong>TEAM MISSION COMPLETE.</strong><br>Score: ${pad(score)}<br>Bonus doors opened: ${stats.doors}<br>C64 games rescued: ${stats.games}<br><br>The Score Goblin has lodged an appeal.`;UI.end.classList.remove("hidden")}
function update(dt){if(mode!=="playing")return;enemyCD-=dt;projectileCD-=dt;sendCD-=dt;worldCD-=dt;surroundCD-=dt;move1-=dt;move2-=dt;fire1-=dt;fire2-=dt;lowHealthCD-=dt;if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)UI.toast.classList.remove("show")}for(const p of localPlayers()){if(p.invuln>0)p.invuln-=dt;if(p.torchMs>0)p.torchMs=Math.max(0,p.torchMs-dt);if(p.sensorMs>0)p.sensorMs=Math.max(0,p.sensorMs-dt);if(p.rapidMs>0)p.rapidMs=Math.max(0,p.rapidMs-dt);p.rx+=(p.x-p.rx)*.32;p.ry+=(p.y-p.ry)*.32;updateCamping(p,dt);reveal(p)}for(const p of remote.values()){p.rx+=(p.x-p.rx)*.28;p.ry+=(p.y-p.ry)*.28}if(input.has("Space")&&fire1<=0)firePlayer(p1,d1());if(p2&&input.has("Enter")&&fire2<=0)firePlayer(p2,d2());if(move1<=0){const d=d1();if(d){movePlayer(p1,d.x,d.y);move1=C.player.moveDelay}}if(p2&&move2<=0){const d=d2();if(d){movePlayer(p2,d.x,d.y);move2=C.player.moveDelay}}if(projectileCD<=0){stepProjectiles();projectileCD=75}if(enemyCD<=0){hostEnemyStep(C.enemy.thinkDelay);enemyCD=C.enemy.thinkDelay}if(sendCD<=0){sendPlayer();sendCD=100}if(worldCD<=0&&net.isHost){broadcastWorld();worldCD=300}updateHazards(dt);updateEffects(dt);if(surroundCD<=0){surroundingsTick();surroundCD=9000}const seen=host.enemies.filter(e=>e.alive&&localPlayers().some(p=>A.lineOfSight(world.map,e,p,p.torchMs>0?C.enemy.torchSightRange:C.enemy.lineOfSightRange,host))).length;S.setDanger(Math.min(1,seen/3));if(localPlayers().some(p=>p.health<=2)&&lowHealthCD<=0){S.sfx("lowhealth");lowHealthCD=2600}for(const p of localPlayers()){const e=host.enemies.find(e=>e.alive&&e.x===p.x&&e.y===p.y);if(e)hurtPlayer(p,e.follower?2:1,false,e.follower?.name||e.kind)}sync()}
function camFor(p,v){let c=cameras.get(p.id)||{x:0,y:0};const tx=Math.max(0,Math.min(C.worldWidth*C.tile-v.w,p.rx*C.tile+C.tile/2-v.w/2)),ty=Math.max(0,Math.min(C.worldHeight*C.tile-v.h,p.ry*C.tile+C.tile/2-v.h/2));c.x+=(tx-c.x)*.12;c.y+=(ty-c.y)*.12;cameras.set(p.id,c);return c}
function ws(x,y){return{x:view.x+x*C.tile-cam.x+renderShake.x,y:view.y+y*C.tile-cam.y+renderShake.y}}
function drawTile(x,y){const s=ws(x,y),th=W.themeAt(world,x,y),wall=world.map[y][x]!==0;if(wall){ctx.fillStyle=th.wall;ctx.fillRect(s.x,s.y,C.tile,C.tile);ctx.fillStyle=th.hi;ctx.fillRect(s.x+2,s.y+2,C.tile-4,4);ctx.fillStyle="rgba(0,0,0,.25)";ctx.fillRect(s.x+C.tile-4,s.y+5,4,C.tile-5);ctx.fillRect(s.x+5,s.y+C.tile-4,C.tile-5,4)}else{ctx.fillStyle=(x+y)%2?th.floor:th.alt;ctx.fillRect(s.x,s.y,C.tile,C.tile);const code=(x*31+y*17+W.roomAt(world,x,y)*7)%37;ctx.fillStyle=th.accent+"22";if(code===0)ctx.fillRect(s.x+7,s.y+7,5,2);if(code===9)ctx.fillRect(s.x+20,s.y+19,3,5);if(th.name==="Budget Bin"&&code===12){ctx.fillStyle="#ffd85a44";ctx.fillRect(s.x+5,s.y+22,8,4)}}}
function drawDoors(){for(const d of host.doors){const s=ws(d.x,d.y);ctx.fillStyle=d.locked?"#6e4c22":"rgba(110,76,34,.22)";ctx.fillRect(s.x+4,s.y+2,C.tile-8,C.tile-4);ctx.strokeStyle=d.locked?P.gold:"#67533b";ctx.lineWidth=2;ctx.strokeRect(s.x+5,s.y+3,C.tile-10,C.tile-6);ctx.fillStyle=P.gold;ctx.fillRect(s.x+19,s.y+14,3,3)}}
function drawExit(){const s=ws(world.exit.x,world.exit.y),t=performance.now()/220;ctx.save();ctx.translate(s.x+15,s.y+15);ctx.strokeStyle=host.exitOpen?P.purple:"#66586e";ctx.lineWidth=3;ctx.shadowColor=host.exitOpen?P.purple:"transparent";ctx.shadowBlur=host.exitOpen?15:0;ctx.strokeRect(-9,-11,18,22);ctx.strokeRect(-4,-6,8,12);if(host.exitOpen){ctx.rotate(t);ctx.beginPath();ctx.arc(0,0,18,-.4,1.5);ctx.stroke()}ctx.restore()}
function itemInfo(i){return{key:["KEY",P.gold],health:["+",P.green],mana:["M",P.cyan],game:["C64",P.white],credits:["£",P.gold],sensor:["R",P.cyan],torch:["T",P.gold],armour:["A",P.blue],potion:["P",P.green],weapon:["W",P.orange],rapid:["RF",P.orange],bronze:["BK",P.gold],treasure:["?",P.gold]}[i.kind]||["?",P.white]}
function drawItem(i){if(!i.active)return;const s=ws(i.x,i.y),[txt,col]=itemInfo(i),pulse=1+Math.sin(performance.now()/155+i.x)*.08;ctx.save();ctx.translate(s.x+15,s.y+15);ctx.scale(pulse,pulse);ctx.shadowColor=col;ctx.shadowBlur=9;ctx.fillStyle=col;ctx.fillRect(-7,-7,14,14);ctx.fillStyle="#160d1b";ctx.font='bold 7px "Courier New"';ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(txt,0,1);ctx.restore()}
function label(text,s,col=P.white){ctx.save();ctx.font='bold 7px "Courier New"';const w=Math.min(96,ctx.measureText(text).width+6);ctx.fillStyle="rgba(5,3,8,.86)";ctx.fillRect(s.x+15-w/2,s.y-8,w,9);ctx.fillStyle=col;ctx.textAlign="center";ctx.fillText(text,s.x+15,s.y-1);ctx.restore()}
function enemyScreen(e){let v=enemyVisuals.get(e.id);if(!v){v={rx:e.x,ry:e.y};enemyVisuals.set(e.id,v)}const rate=e.aiState==="chase"?.23:.14;v.rx+=(e.x-v.rx)*rate;v.ry+=(e.y-v.ry)*rate;return ws(v.rx,v.ry)}
function drawEnemy(e){if(!e.alive)return;if(e.kind==="ghost"&&focus.sensorMs<=0&&e.aiState==="idle")return;const s=enemyScreen(e),f=e.follower,img=f?.avatar?avatarImages.get(f.name):null;ctx.fillStyle="rgba(0,0,0,.38)";ctx.beginPath();ctx.ellipse(s.x+15,s.y+25,11,4,0,0,Math.PI*2);ctx.fill();if(img&&img.complete&&img.naturalWidth){ctx.save();ctx.beginPath();ctx.arc(s.x+15,s.y+15,12,0,Math.PI*2);ctx.clip();ctx.drawImage(img,s.x+3,s.y+3,24,24);ctx.restore();ctx.strokeStyle=P.gold;ctx.lineWidth=2;ctx.beginPath();ctx.arc(s.x+15,s.y+15,12,0,Math.PI*2);ctx.stroke()}else{const k=f?.kind||e.kind,col=k==="hunter"?P.gold:k==="charger"?P.cyan:k==="ranger"?P.blue:k==="root"?P.green:k==="cook"?P.orange:k==="firebreather"?P.green:e.kind==="guard"?P.red:e.kind==="ghost"?P.purple:P.pink;ctx.fillStyle=col;ctx.fillRect(s.x+6,s.y+7,18,19);ctx.fillStyle=P.white;ctx.fillRect(s.x+9,s.y+11,4,4);ctx.fillRect(s.x+18,s.y+11,4,4)}label(f?.name||({scout:"Tape Scout",hunter:"Joystick Hunter",ambusher:"Raster Ambusher",guard:"1541 Guard",ghost:"Ghost Byte"}[e.kind]||"Enemy"),s,f?P.gold:P.white);if(e.aiState==="chase"||e.aiState==="search"){ctx.font='bold 14px "Courier New"';ctx.textAlign="center";ctx.fillStyle=e.aiState==="chase"?P.red:P.gold;ctx.fillText(e.aiState==="chase"?"!":"?",s.x+15,s.y-13)}}
function drawPlayer(p,kind="p1"){const s=ws(p.rx,p.ry),col=kind==="p2"?P.green:kind==="remote"?P.cyan:P.gold;ctx.fillStyle="rgba(0,0,0,.38)";ctx.beginPath();ctx.ellipse(s.x+15,s.y+26,12,4,0,0,Math.PI*2);ctx.fill();ctx.save();ctx.translate(s.x+15,s.y+15);ctx.fillStyle=col+"22";ctx.shadowColor=col;ctx.shadowBlur=p.torchMs>0?18:8;ctx.beginPath();ctx.arc(0,0,p.torchMs>0?22:19,0,Math.PI*2);ctx.fill();ctx.strokeStyle=col;ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,18,0,Math.PI*2);ctx.stroke();if(logo.complete&&logo.naturalWidth){const r=logo.naturalWidth/logo.naturalHeight;let dw=40,dh=dw/r;if(dh>24){dh=24;dw=dh*r}ctx.drawImage(logo,-dw/2,-dh/2,dw,dh)}else{ctx.fillStyle=col;ctx.font='bold 10px "Courier New"';ctx.textAlign="center";ctx.fillText("CCG",0,3)}ctx.restore();label(p.name,{x:s.x,y:s.y-2},col)}
function drawShots(){ctx.save();ctx.lineCap="round";for(const b of bullets){const s=ws(b.x,b.y),x=s.x+15,y=s.y+15;ctx.strokeStyle="rgba(255,153,80,.6)";ctx.lineWidth=4;ctx.shadowColor=P.orange;ctx.shadowBlur=9;ctx.beginPath();ctx.moveTo(x-b.dx*12,y-b.dy*12);ctx.lineTo(x+b.dx*3,y+b.dy*3);ctx.stroke()}for(const b of enemyBullets){const s=ws(b.x,b.y),x=s.x+15,y=s.y+15,col=b.style==="food"?P.orange:b.style==="root"?P.green:b.style==="fire"?P.gold:P.red;ctx.strokeStyle=col;ctx.lineWidth=b.style==="fire"?7:4;ctx.shadowColor=col;ctx.shadowBlur=10;ctx.beginPath();ctx.moveTo(x-b.dx*12,y-b.dy*12);ctx.lineTo(x+b.dx*2,y+b.dy*2);ctx.stroke()}ctx.restore()}
function drawEffects(){for(const q of particles){ctx.globalAlpha=Math.max(0,q.life/360);ctx.fillStyle=q.col;ctx.fillRect(view.x+q.x-cam.x,view.y+q.y-cam.y,q.size,q.size)}ctx.globalAlpha=1;for(const r of rings){ctx.globalAlpha=Math.max(0,r.life/340);ctx.strokeStyle=r.col;ctx.lineWidth=2;ctx.beginPath();ctx.arc(view.x+r.x-cam.x,view.y+r.y-cam.y,r.r,0,Math.PI*2);ctx.stroke()}ctx.globalAlpha=1;for(const f of floaters){ctx.globalAlpha=Math.max(0,f.life/420);ctx.fillStyle=f.col;ctx.font='bold 9px "Courier New"';ctx.textAlign="center";ctx.fillText(f.text,view.x+f.x-cam.x,view.y+f.y-cam.y)}ctx.globalAlpha=1}
function drawHazards(){for(const h of hazards){const s=ws(h.x,h.y),t=Math.max(0,h.life/h.maxLife);ctx.globalAlpha=.45+.4*Math.abs(Math.sin(performance.now()/70));ctx.strokeStyle=P.red;ctx.lineWidth=2;ctx.beginPath();ctx.arc(s.x+15,s.y+15,8+(1-t)*8,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1}}
function drawFog(){const ex=explored.get(focus.id)||new Set(),x0=Math.max(0,Math.floor(cam.x/C.tile)-1),x1=Math.min(C.worldWidth-1,Math.ceil((cam.x+view.w)/C.tile)+1),y0=Math.max(0,Math.floor(cam.y/C.tile)-1),y1=Math.min(C.worldHeight-1,Math.ceil((cam.y+view.h)/C.tile)+1);for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++){if(visibleTo(focus,x,y))continue;const s=ws(x,y);ctx.fillStyle=ex.has(`${x},${y}`)?"rgba(0,0,0,.70)":"rgba(0,0,0,.97)";ctx.fillRect(s.x,s.y,C.tile,C.tile)}if(focus.torchMs>0){const s=ws(focus.rx,focus.ry),g=ctx.createRadialGradient(s.x+15,s.y+15,15,s.x+15,s.y+15,170);g.addColorStop(0,"rgba(255,216,90,.12)");g.addColorStop(1,"rgba(255,180,60,0)");ctx.fillStyle=g;ctx.fillRect(view.x,view.y,view.w,view.h)}}
function minimap(){const sc=view.w<600?1:1.35,mw=C.worldWidth*sc,mh=C.worldHeight*sc,ox=view.x+view.w-mw-7,oy=view.y+7,ex=explored.get(focus.id)||new Set();ctx.fillStyle="rgba(5,3,8,.84)";ctx.fillRect(ox-3,oy-3,mw+6,mh+6);ctx.strokeStyle="#5c4275";ctx.strokeRect(ox-3,oy-3,mw+6,mh+6);for(let y=0;y<C.worldHeight;y++)for(let x=0;x<C.worldWidth;x++){if(!ex.has(`${x},${y}`))continue;ctx.fillStyle=world.map[y][x]?"#4c4164":"#1c1525";ctx.fillRect(ox+x*sc,oy+y*sc,sc,sc)}if(ex.has(`${world.exit.x},${world.exit.y}`)){ctx.fillStyle=host.exitOpen?P.purple:"#60536a";ctx.fillRect(ox+world.exit.x*sc,oy+world.exit.y*sc,2.5,2.5)}if(focus.sensorMs>0)for(const e of host.enemies)if(e.alive){ctx.fillStyle=P.red;ctx.fillRect(ox+e.x*sc,oy+e.y*sc,2,2)}ctx.fillStyle=P.gold;ctx.fillRect(ox+focus.x*sc,oy+focus.y*sc,3,3)}
function renderView(p,v){view=v;focus=p;cam=camFor(p,v);ctx.save();ctx.beginPath();ctx.rect(v.x,v.y,v.w,v.h);ctx.clip();ctx.fillStyle=P.black;ctx.fillRect(v.x,v.y,v.w,v.h);const x0=Math.max(0,Math.floor(cam.x/C.tile)-1),x1=Math.min(C.worldWidth-1,Math.ceil((cam.x+v.w)/C.tile)+1),y0=Math.max(0,Math.floor(cam.y/C.tile)-1),y1=Math.min(C.worldHeight-1,Math.ceil((cam.y+v.h)/C.tile)+1);for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++)drawTile(x,y);drawDoors();drawExit();drawHazards();host.items.forEach(drawItem);host.enemies.forEach(drawEnemy);drawShots();for(const r of remote.values())if(performance.now()-r.lastSeen<2600)drawPlayer(r,"remote");for(const lp of localPlayers())drawPlayer(lp,lp===p2?"p2":"p1");drawEffects();drawFog();minimap();ctx.fillStyle="rgba(5,3,8,.72)";ctx.fillRect(v.x+5,v.y+v.h-23,160,18);ctx.fillStyle=p===p2?P.green:P.gold;ctx.font='bold 9px "Courier New"';ctx.fillText(`${p.name}  H:${p.health} A:${p.armor} W:${p.weaponLevel}`,v.x+10,v.y+v.h-11);ctx.restore()}
function render(){if(!world||!p1)return;renderShake=shake>0?{x:(Math.random()-.5)*shake,y:(Math.random()-.5)*shake}:{x:0,y:0};if(shake>0){shake*=.84;if(shake<.25)shake=0}ctx.fillStyle=P.black;ctx.fillRect(0,0,canvas.width,canvas.height);if(p2){renderView(p1,{x:0,y:0,w:canvas.width/2,h:canvas.height});renderView(p2,{x:canvas.width/2,y:0,w:canvas.width/2,h:canvas.height});ctx.fillStyle=P.purple;ctx.fillRect(canvas.width/2-2,0,4,canvas.height)}else renderView(p1,{x:0,y:0,w:canvas.width,h:canvas.height});if(damageFlash>0){ctx.fillStyle=`rgba(255,50,70,${Math.min(.18,damageFlash*.18)})`;ctx.fillRect(0,0,canvas.width,canvas.height)}}
function pause(force=false){if(mode==="playing"&&!force){mode="paused";UI.pause.classList.remove("hidden");S.setMusicLevel(.03)}else if(mode==="paused"){mode="playing";UI.pause.classList.add("hidden");input.clear();S.setMusicLevel(.075)}}
function toggleSound(){S.toggle();sync()}
function loop(t){const dt=Math.min(45,t-last||16);last=t;if(damageFlash>0)damageFlash=Math.max(0,damageFlash-dt/500);update(dt);render();requestAnimationFrame(loop)}
$("solo-btn").addEventListener("click",startSolo);$("split-btn").addEventListener("click",startSplit);$("create-btn").addEventListener("click",createRoom);$("join-btn").addEventListener("click",joinRoom);$("resume-btn").addEventListener("click",()=>pause(true));UI.sound.addEventListener("click",toggleSound);$("again-btn").addEventListener("click",async()=>{UI.end.classList.add("hidden");await net.leave();UI.menu.classList.remove("hidden");mode="menu";p2=null;S.startMusic()});
addEventListener("keydown",e=>{if(["ArrowUp","ArrowDown","ArrowLeft","ArrowRight","Space"].includes(e.code))e.preventDefault();if(e.code==="KeyP"&&(mode==="playing"||mode==="paused")){pause();return}if(e.code==="KeyM"){toggleSound();return}if(p1)setDir(p1,e.code);if(p2)setDir(p2,e.code);input.add(e.code);if(e.code==="Space"&&!e.repeat)firePlayer(p1,d1());if(p2&&e.code==="Enter"&&!e.repeat)firePlayer(p2,d2());if(e.code==="ShiftLeft"&&!e.repeat)dashPlayer(p1,d1()||p1.dir);if(p2&&e.code==="ControlRight"&&!e.repeat)dashPlayer(p2,d2()||p2.dir);if(e.code==="KeyE"&&!e.repeat)usePotion(p1);if(p2&&e.code==="KeyO"&&!e.repeat)usePotion(p2)},{passive:false});
addEventListener("keyup",e=>input.delete(e.code));addEventListener("blur",()=>input.clear());document.addEventListener("visibilitychange",()=>{if(document.hidden)input.clear()});
net.setSolo("TITLE");startWorld("TITLE-ADVENTURE",false);mode="menu";document.body.dataset.gameReady="true";requestAnimationFrame(loop);
})();
