function onMembers(members,isHost,changed){if(changed&&isHost&&mode==="playing"){say("<strong>HOST MIGRATION.</strong> You're now running the dungeon simulation.","cyan");broadcastWorld()}sync()}
function onPacket(event,p){
  if(event==="player")onPlayer(p);else if(event==="shot")spawnBullet(p,true);else if(event==="enemy_shot")spawnEnemyShot(p);else if(event==="hit")onHit(p);else if(event==="player_hit"&&p?.target===p1?.id)hurtPlayer(p1,p.power||1,true,p.source||"another player");else if(event==="collect")onCollectRequest(p);else if(event==="collected")onCollected(p);else if(event==="world")onWorld(p);else if(event==="hello"&&net.isHost)broadcastWorld();else if(event==="notice"){const src=p?.source;if(!src||localPlayers().some(lp=>visibleTo(lp,src.x,src.y)))say(p?.html||"");}else if(event==="fx")onFX(p);else if(event==="complete")floorComplete(p?.by||"the team")
}
function onPlayer(p){
  if(!p||p.id===net.sessionId)return;const old=remote.get(p.id),changed=old&&Number(old.health)!==Number(p.health);
  remote.set(p.id,{...p,rx:old?.rx??p.x,ry:old?.ry??p.y,hpBarMs:changed?2600:Math.max(0,old?.hpBarMs||0),lastSeen:performance.now()})
}
function sendPlayer(){if(playMode!=="online")return;net.send("player",{id:p1.id,name:p1.name,x:p1.x,y:p1.y,health:p1.health,dir:p1.dir,torchMs:p1.torchMs,armor:p1.armor,level:p1.level})}
function serialWorld(){return{
  revision:host.revision,keysCollected:host.keysCollected,exitOpen:host.exitOpen,exitSigilCollected:Boolean(host.exitSigilCollected),exitSigilDropped:Boolean(host.exitSigilDropped),
  sigilRoomId:host.sigilRoomId??null,sigilLockdown:Boolean(host.sigilLockdown),sigilResolved:Boolean(host.sigilResolved),sigilDropPos:host.sigilDropPos?{...host.sigilDropPos}:null,radarSigilSeen:host.radarSigilSeen?{...host.radarSigilSeen}:null,radarSigilGateSeen:host.radarSigilGateSeen?{...host.radarSigilGateSeen}:null,sigilDefenderIds:[...(host.sigilDefenderIds||[])],sigilGateIds:[...(host.sigilGateIds||[])],
  doors:host.doors.map(d=>({...d})),chests:(host.chests||[]).map(c=>({...c,loot:c.loot?{...c.loot,weapon:c.loot.weapon?{...c.loot.weapon}:undefined}:null})),enemies:host.enemies.map(e=>({...e,lastSeen:e.lastSeen?{...e.lastSeen}:null,follower:e.follower||null})),items:host.items.map(i=>({...i})),
  traps:(host.traps||[]).map(x=>({...x})),generators:(host.generators||[]).map(x=>({...x})),shrines:(host.shrines||[]).map(x=>({...x})),switches:(host.switches||[]).map(x=>({...x})),arenas:(host.arenas||[]).map(x=>({...x})),timedRooms:(host.timedRooms||[]).map(x=>({...x})),
  trader:host.trader?{...host.trader,sold:{...(host.trader.sold||{})}}:null,startShop:host.startShop?{...host.startShop,sold:{...(host.startShop.sold||{})}}:null,shops:(host.shops||[]).map(x=>({...x,sold:{...(x.sold||{})}})),boulderTrap:host.boulderTrap?{...host.boulderTrap,start:{...host.boulderTrap.start},end:{...host.boulderTrap.end},target:{...host.boulderTrap.target}}:null,deathCaches:(host.deathCaches||[]).map(c=>({...c,inventory:(c.inventory||[]).map(x=>({...x})),games:[...(c.games||[])]})),voidStalkers:[...(host.voidStalkers||[])],defeatedDeathStalkers:[...(host.defeatedDeathStalkers||[])],
  bloodClue:host.bloodClue?{...host.bloodClue,sequence:[...(host.bloodClue.sequence||[])]}:null,memoryPuzzle:host.memoryPuzzle?{...host.memoryPuzzle,tiles:(host.memoryPuzzle.tiles||[]).map(x=>({...x})),sequence:[...(host.memoryPuzzle.sequence||[])]}:null,sequenceTorchPuzzle:host.sequenceTorchPuzzle?{...host.sequenceTorchPuzzle,torches:(host.sequenceTorchPuzzle.torches||[]).map(x=>({...x})),sequence:[...(host.sequenceTorchPuzzle.sequence||[])]}:null,weightBridge:host.weightBridge?{...host.weightBridge,pitTiles:(host.weightBridge.pitTiles||[]).map(x=>({...x})),bridgeTiles:(host.weightBridge.bridgeTiles||[]).map(x=>({...x}))}:null,
  rescue:host.rescue?{...host.rescue}:null,stalker:host.stalker?{...host.stalker}:null,objective:host.objective?{...host.objective}:null,mapRewards:host.mapRewards?{...host.mapRewards}:null,alertLevel:host.alertLevel||0
}}
function broadcastWorld(){if(playMode==="online"&&net.connected&&net.isHost)net.send("world",serialWorld())}
function onWorld(s){
  if(!s||net.isHost)return;
  if(!host||Number(s.revision)>=Number(host.revision)){
    host={...host,revision:Number(s.revision||0),keysCollected:Number(s.keysCollected||0),exitOpen:Boolean(s.exitOpen),exitSigilCollected:Boolean(s.exitSigilCollected),exitSigilDropped:Boolean(s.exitSigilDropped),
      sigilRoomId:s.sigilRoomId??host?.sigilRoomId??null,sigilLockdown:Boolean(s.sigilLockdown),sigilResolved:Boolean(s.sigilResolved),sigilDropPos:s.sigilDropPos||null,radarSigilSeen:s.radarSigilSeen||host?.radarSigilSeen||null,radarSigilGateSeen:s.radarSigilGateSeen||host?.radarSigilGateSeen||null,sigilDefenderIds:s.sigilDefenderIds||[],sigilGateIds:s.sigilGateIds||[],
      doors:s.doors||[],chests:s.chests||[],enemies:s.enemies||[],items:s.items||[],traps:s.traps||[],generators:s.generators||[],shrines:s.shrines||[],switches:s.switches||[],arenas:s.arenas||[],timedRooms:s.timedRooms||[],
      trader:s.trader||null,startShop:s.startShop||null,shops:s.shops||[],boulderTrap:s.boulderTrap||null,deathCaches:s.deathCaches||[],voidStalkers:s.voidStalkers||[],defeatedDeathStalkers:s.defeatedDeathStalkers||host?.defeatedDeathStalkers||[],bloodClue:s.bloodClue||null,memoryPuzzle:s.memoryPuzzle||null,sequenceTorchPuzzle:s.sequenceTorchPuzzle||null,weightBridge:s.weightBridge||null,rescue:s.rescue||null,stalker:s.stalker||null,objective:s.objective||host?.objective,mapRewards:s.mapRewards||host?.mapRewards,alertLevel:s.alertLevel||0};
    sync()
  }
}
function hostEnemyStep(dt){
  if(!net.isHost)return;const dm=PGR.difficulty(run).enemyDamage;
  A.stepEnemies(host,world.map,allPlayers(),dt,{
    shoot:s=>{s.power=Math.max(1,Math.round((s.power||1)*dm*(s.damageScale||1)));spawnEnemyShot(s);if(playMode==="online")net.send("enemy_shot",s)},
    melee:(e,target,power)=>{power=Math.max(1,Math.round(power*dm*(e.namedDamageScale||1)));const lp=findLocal(target.id);if(lp){const before=lp.health;hurtPlayer(lp,power,false,e.follower?.name||e.championName||e.kind);if(before>power)knockPlayerAway(lp,e)}else if(playMode==="online")net.send("player_hit",{target:target.id,power,source:e.follower?.name||e.kind})},
    notice:(html,sound,source)=>{const audible=source&&localPlayers().some(p=>visibleTo(p,source.x,source.y));if(audible){if(sound)S.sfx(sound);say(html,sound==="flame"?"red":"gold")}if(playMode==="online"&&source)net.send("notice",{html,source:{x:source.x,y:source.y}})},
    alert:(e,state,reason)=>{const seenHere=localPlayers().some(p=>visibleTo(p,e.x,e.y));if(state==="alert"&&seenHere){S.sfx("alert");floatText(e.x,e.y,"!",P.red);if(reason==="room"&&Math.random()<.18)say(`<strong>ROOM ALERT.</strong> ${e.follower?.name||e.championName||"Something"} has spotted you.`,"red")}if(state==="search"&&seenHere)S.sfx("search")}
  },world)
}
function onHit(p){if(!net.isHost||!p?.enemyId)return;const e=host.enemies.find(x=>x.id===p.enemyId&&x.alive);if(e){if(p.source)A.alertEnemy(e,p.source.x,p.source.y);damageEnemy(e,Math.max(1,Math.min(8,Number(p.power||1))),p.element||"energy",findLocal(p.owner)||p1)}}
function elementalDamage(e,power,element){if(!e.weakness)return power;if(e.weakness===element)return Math.ceil(power*1.75);return power}
function isDeathStalkerEnemy(e){return Boolean(e?.deathStalker&&e?.voidStalker)}
function damageEnemy(e,power,element="energy",attacker=p1){
  if(!e?.alive)return;
  if(isDeathStalkerEnemy(e)){e.flash=220;e.hpBarMs=1400;e.hitStunMs=220;knockEnemyAway(e,attacker);S.sfx("stalker");floatText(e.x,e.y,"KNOCKED BACK",P.purple);showToast("DEATH STALKER — INDESTRUCTIBLE","Weapons can repel it but cannot damage it. FIND 3 ARTEFACTS TO EXCHANGE FOR THE POTION TO KILL THIS INDESTRUCTIBLE ENEMY.","red",8500);return}
  power=elementalDamage(e,power,element);e.flash=160;e.hpBarMs=2800;e.hitStunMs=Math.max(e.hitStunMs||0,C.enemy.hitStunMs||1000);
  let hpDamage=power;
  if((e.armor||0)>0){const absorbed=Math.min(e.armor,hpDamage);e.armor-=absorbed;hpDamage-=absorbed;S.sfx("armour");burst(e.x,e.y,P.blue,7,1.0);ring(e.x,e.y,P.blue,18);floatText(e.x,e.y,`ARM -${absorbed}`,P.cyan)}
  if(hpDamage>0){e.hp-=hpDamage;S.sfx("hit");burst(e.x,e.y,isDeathStalkerEnemy(e)?P.purple:e.weakness===element?P.cyan:P.orange,8,1.2);ring(e.x,e.y,isDeathStalkerEnemy(e)?P.purple:P.orange,20);floatText(e.x,e.y,`-${hpDamage}`,P.white);if(!isDeathStalkerEnemy(e))knockEnemyAway(e,attacker)}
  if(e.hp>0)return;
  e.hp=0;e.alive=false;host.revision++;run.stats.kills++;
  let killScore=e.exitWarden?800:e.guardian?900:e.follower?500:e.champion?300:e.treasureGoblin?450:isDeathStalkerEnemy(e)?600:120;
  let xp=e.exitWarden?420:e.guardian?500:e.follower?300:e.champion?220:e.treasureGoblin?300:isDeathStalkerEnemy(e)?360:75;
  let reason=e.exitWarden?"Sigil Warden defeated":e.guardian?"Guardian defeated":e.follower?`${e.follower.name} freed`:isDeathStalkerEnemy(e)?"Death Stalker banished":e.champion?"Champion defeated":"Enemy defeated";
  if(e.generatorId){const g=(host.generators||[]).find(x=>x.id===e.generatorId);if(g){g.spawnKills=(g.spawnKills||0)+1;const farm=[35,25,15];xp=g.spawnKills<=3?farm[g.spawnKills-1]:5;killScore=g.spawnKills<=3?65:10;reason=g.spawnKills<=3?`Generator spawn ${g.spawnKills}/3`:`Generator farming diminished`}}
  score+=killScore;awardXP(attacker||p1,xp,reason);
  if(e.champion)run.stats.champions++;
  if(e.follower){stats.elites++;run.stats.namedDefeats=(run.stats.namedDefeats||0)+1;PGR.recordNamedEncounter(e.follower.name,true)}
  if(isDeathStalkerEnemy(e)){run.stats.stalkerEscapes=(run.stats.stalkerEscapes||0)+1;host.defeatedDeathStalkers=host.defeatedDeathStalkers||[];if(!host.defeatedDeathStalkers.includes(e.id))host.defeatedDeathStalkers.push(e.id);if(e.timedHunter){const tr=(host.timedRooms||[]).find(t=>t.hunterId===e.id||`death-stalker-${t.id}`===e.id);if(tr)tr.stalkerDefeated=true}}
  const fx={type:"death",x:e.x,y:e.y,color:e.guardian?P.red:e.follower?P.gold:isDeathStalkerEnemy(e)?P.purple:e.champion?P.cyan:P.pink,elite:Boolean(e.follower||e.guardian||e.champion||isDeathStalkerEnemy(e))};onFX(fx);if(playMode==="online")net.send("fx",fx);
  if(e.treasureGoblin){const loot=PGR.lootForChest({depth:9},run,Math.random);host.items.push({id:`goblin-loot-${Date.now()}`,x:e.x,y:e.y,kind:"loot",loot,active:true,title:loot.name||loot.weapon?.displayName});showToast("TREASURE GOBLIN CAUGHT","It dropped something substantially better than dignity.","gold")}
  if(e.exitWarden){host.sigilDropPos={x:e.x,y:e.y};const remaining=SYS.sigilDefendersAlive(host).length;if(remaining>0){showToast("SIGIL WARDEN DOWN",`${remaining} Sigil defender${remaining===1?"":"s"} still hold the chamber. The Exit Sigil remains sealed.`,"red",8500)}}
  if(e.sigilDefender){const remaining=SYS.sigilDefendersAlive(host);if(remaining.length===0&&!host.sigilResolved){host.sigilResolved=true;host.sigilLockdown=false;host.exitSigilDropped=true;const room=world.rooms[host.sigilRoomId],drop=host.sigilDropPos||{x:room?Math.floor(room.x+room.w/2):e.x,y:room?Math.floor(room.y+room.h/2):e.y};host.items.push({id:`exit-sigil-${Date.now()}`,...drop,kind:"exitSigil",active:true,title:"EXIT SIGIL"});for(const d of host.doors||[])if(d.sigilGate){d.locked=false;beginDoorOpening(d,950)}S.sfx("exitSigil");showToast("SIGIL CHAMBER CLEARED","Every defender is down. The EXIT SIGIL is exposed and the reinforced doors are releasing.","gold",10000)}}
  if(e.follower){
    const guaranteed=Math.random()<.45?{kind:"artefact",rarity:"SIZZLER",name:`${e.follower.name} Dossier Artefact`,xp:220}:PGR.lootForChest({depth:10+(run.floor||1)},run,()=>Math.random()*.72);
    host.items.push({id:`named-loot-${Date.now()}-${Math.random()}`,x:e.x,y:e.y,kind:"loot",loot:guaranteed,active:true,title:guaranteed.weapon?.displayName||guaranteed.name||"Named Enemy Cache"});
    if(PGR.inventoryCapacity(attacker||p1)<C.player.inventorySlots&&Math.random()<.015)host.items.push({id:`inventory-slot-${Date.now()}-${Math.random()}`,x:e.x,y:e.y,kind:"inventorySlot",active:true,title:"RARE INVENTORY EXPANSION"});
    S.sfx("elite");showToast(`${e.follower.name.toUpperCase()} FREED`,`You did not kill ${e.follower.name}; the dungeon corruption broke. A meaningful loot drop is guaranteed and the rescue is recorded in your dossier.`,"green",7600);if(!run.namedDossierAutoShown){run.namedDossierAutoShown=true;setTimeout(()=>{if(mode==="playing")showNamedDossier(e.follower.name,true)},320)}if(e.follower.name==="CPU")host.items.push({id:`food-${Date.now()}`,x:e.x,y:e.y,kind:"health",active:true,title:"CPU's Emergency Roast"})
  }else S.sfx("death");
  if(attacker?.weapon?.vampiric){attacker.killsSinceHeal=(attacker.killsSinceHeal||0)+1;if(attacker.killsSinceHeal>=8){attacker.killsSinceHeal=0;attacker.health=Math.min(attacker.maxHealth,attacker.health+1);attacker.hpBarMs=2800;showToast("VAMPIRIC WEAPON","Eight kills return 1 health.","green")}}
  SYS.updateObjective(host,run,Math.round(PGR.roomCompletion(explored.get(p1.id)||new Set(),world)*100));updateQuests();broadcastWorld()
}
function onFX(p){if(!p)return;if(p.type==="death"){burst(p.x,p.y,p.color||P.pink,p.elite?28:18,p.elite?1.8:1.35);ring(p.x,p.y,p.color||P.pink,p.elite?42:30);shake=Math.max(shake,p.elite?11:6);floatText(p.x,p.y,p.elite?"FREED!":"ZAPPED!",p.color||P.gold)}}
function floorItemNeedsSlot(i){if(!i)return false;if(i.carriedItem)return true;if(["potion","torch","teleport","banishment"].includes(i.kind))return true;return i.kind==="loot"&&["potion","torch","teleport","banishment","artefact"].includes(i.loot?.kind)}
function floorItemCarryCandidate(i){if(!i)return null;if(i.carriedItem)return{...i.carriedItem};if(["potion","torch","teleport","banishment"].includes(i.kind))return{kind:i.kind,name:i.title||i.kind,short:i.kind==="potion"?"POTION":i.kind==="torch"?"TORCH":i.kind==="teleport"?"WARP":"BANISH",qty:1};if(i.kind==="loot"&&["potion","torch","teleport","banishment","artefact"].includes(i.loot?.kind))return{kind:i.loot.kind,name:i.loot.name||i.title||i.loot.kind,short:i.loot.kind==="artefact"?"ARTEFACT":i.loot.kind==="teleport"?"WARP":i.loot.kind.toUpperCase(),rarity:i.loot.rarity,qty:1};return null}
function inventoryFullForPickup(i,p,snapshot=null){if(!floorItemNeedsSlot(i))return false;const candidate=floorItemCarryCandidate(i),holder=p||{inventory:Array.isArray(snapshot)?snapshot:[]};return !PGR.inventoryCanAdd(holder,candidate)}
function onCollectRequest(p){if(!net.isHost||!p?.itemId)return;const i=host.items.find(x=>x.id===p.itemId&&x.active);if(!i)return;const collector=findLocal(p.collector);if(inventoryFullForPickup(i,collector,p.inventorySnapshot)){if(collector)showToast("INVENTORY FULL","That item stays on the floor. Matching stackable items can still be collected; otherwise free a stack slot first.","red",6500);return}i.active=false;if(i.kind==="key")host.keysCollected=Math.min(C.keyTarget,host.keysCollected+1);if(i.kind==="exitSigil"){host.exitSigilCollected=true;host.radarSigilSeen=host.radarSigilSeen||{x:i.x,y:i.y}}host.revision++;SYS.updateObjective(host,run,Math.round(PGR.roomCompletion(explored.get(p1.id)||new Set(),world)*100));const ev={item:{...i},collector:p.collector};onCollected(ev);if(playMode==="online")net.send("collected",ev);broadcastWorld();sync()}
function requestCollect(i,p){if(!i?.active||pendingItems.has(i.id))return false;if(inventoryFullForPickup(i,p)){showToast("INVENTORY FULL","That item stays on the floor. Matching stackable items can still merge; otherwise press TAB and free a stack slot.","red",6500);S.sfx("empty");return false}pendingItems.add(i.id);const req={itemId:i.id,collector:p.id,inventorySnapshot:(p.inventory||[]).map(x=>({kind:x.kind,name:x.name,qty:x.qty||1}))};if(playMode==="online"&&p.id===p1.id&&!net.isHost)net.send("collect",req);else onCollectRequest(req);setTimeout(()=>pendingItems.delete(i.id),500);return true}
function collectedName(i){if(i.kind==="loot")return i.loot?.weapon?.displayName||i.loot?.name||i.title||"LOOT";return i.title||({health:"HEALTH PACK",mana:"AMMO PACK",ammo:"AMMO PACK",game:"C64 GAME",credits:"GOLD SCORE COIN",xpOrb:"XP ORB",torch:"FLAMING TORCH",teleport:"TELEPORT SPELL",banishment:"BANISHMENT FLASK",armour:"ARMOUR PLATE",potion:"RESTORATION POTION",weapon:"WEAPON",rapid:"RAPID FIRE",bronze:"BRONZE KEY",exitSigil:"EXIT SIGIL",key:"MAIN VAULT KEY"}[i.kind]||i.kind)}
function onCollected(ev){const i=ev?.item;if(!i)return;const p=findLocal(ev.collector),col=(i.kind==="key"||i.kind==="exitSigil"||i.kind==="bronze")?P.gold:i.kind==="health"?P.green:i.kind==="ammo"||i.kind==="mana"?P.cyan:i.kind==="loot"&&i.loot?.rarity==="ZZAP! 97%"?P.pink:P.white;ring(i.x,i.y,col,34);burst(i.x,i.y,P.gold,14,1.2);if(!p){if(i.kind==="key"){S.sfx("mainKey");say(`<strong>TEAM KEY FOUND.</strong> ${host.keysCollected}/${C.keyTarget}.`,"gold")}return}floatPickupText(p,collectedName(i),col);applyItem(i,p);sync()}
function storeConsumable(p,item,title,text,tone="gold"){
  if(!PGR.inventoryAdd(p,item)){showToast("INVENTORY FULL",`${title} cannot be carried. Free a slot and collect it again.`,"red");return false}
  S.sfx(item.kind==="potion"?"potion":item.kind==="torch"?"torch":"pickup");showToast(title,text,tone);return true
}
function equipWeapon(p,weapon){const old=p.weapon;p.weapon={...weapon};p.weaponLevel=Math.max(1,1+PGR.RARITY.indexOf(weapon.rarity));stats.weapons++;S.sfx("weapon");showToast(weapon.displayName,`${weapon.desc} ${weapon.mods?.length?`Modifiers: ${weapon.mods.join(", ")}.`:""} Element: ${weapon.element.toUpperCase()}.`,weapon.rarity==="GOLD MEDAL"?"gold":weapon.rarity==="ZZAP! 97%"?"red":"cyan",7200);if(old&&old.rating>weapon.rating)logEvent(`You replaced a higher-rated ${old.displayName}. Inventory decisions can hurt.`,"red",7500)}
function applyLoot(loot,p){
  if(!loot)return;
  if(loot.kind==="weaponLoot")equipWeapon(p,loot.weapon);
  else if(loot.kind==="armour"){p.armor=Math.min(12,p.armor+(loot.amount||2));S.sfx("armour");showToast(loot.name||"ARMOUR",`+${loot.amount||2} armour.`,"cyan")}
  else if(loot.kind==="ammo"){const n=Math.round((loot.amount||40)*(1+(p.scavenger||0))*PGR.difficulty(run).ammo);p.mana=Math.min(p.maxMana,p.mana+n);p.ammoFlashMs=C.player.ammoFlashMs;showToast(loot.name||"AMMO CACHE",`+${n} ammunition.`,"cyan")}
  else if(loot.kind==="potion")storeConsumable(p,{kind:"potion",name:loot.name||"Restoration Potion",short:"POTION"},loot.name||"RESTORATION POTION","Added to your inventory stack.","green");
  else if(loot.kind==="torch")storeConsumable(p,{kind:"torch",name:loot.name||"Flaming Torch",short:"TORCH"},loot.name||"FLAMING TORCH","Stored in its own slot. Press Q to light a torch.","gold");
  else if(loot.kind==="teleport")storeConsumable(p,{kind:"teleport",name:loot.name||"Teleport Spell",short:"WARP"},loot.name||"TELEPORT SPELL","Stacked in inventory. Press R to warp to a safe explored room.","purple");
  else if(loot.kind==="banishment")storeConsumable(p,{kind:"banishment",name:loot.name||"Banishment Flask",short:"BANISH"},loot.name||"BANISHMENT FLASK","Stacked in inventory. A flashing B prompt appears when a Death Stalker or Count Loadula is within Banishment range.","purple");
  else if(loot.kind==="rapid"){p.rapidMs=14000;S.sfx("weapon");showToast(loot.name||"RAPID FIRE","Fire delay reduced temporarily.","gold")}
  else if(loot.kind==="bountyArtefact")offerBanishmentArtefact(p,loot);
  else if(loot.kind==="artefact"){if(PGR.inventoryAdd(p,{kind:"artefact",name:loot.name,short:"ARTEFACT",rarity:loot.rarity})){awardXP(p,loot.xp||150,"Artefact recovered");showToast(loot.name,`Rare artefact stored. +${loot.xp||150} XP. Three artefacts can be traded for a Banishment Flask.`,"gold")}else showToast("INVENTORY FULL","The artefact cannot be carried.","red")}
}
function applyItem(i,p){
  const who=p===p2?"P2":"P1";
  if(i.carriedItem){if(!PGR.inventoryAdd(p,{...i.carriedItem})){showToast("INVENTORY FULL","The dropped item stays on the floor until you free a slot.","red");return false}S.sfx("pickup");showToast("ITEM RECOVERED",`${i.carriedItem.name||i.carriedItem.kind} returned to your inventory.`,"green");updateQuests();return true}
  if(i.kind==="loot")applyLoot(i.loot,p);
  else if(i.kind==="health"){p.health=Math.min(p.maxHealth,p.health+3);p.hpBarMs=2800;S.sfx("pickup");showToast("HEALTH PACK",`${who} restores 3 health.`,"green")}
  else if(i.kind==="mana"||i.kind==="ammo"){const n=Math.round(30*(1+(p.scavenger||0))*PGR.difficulty(run).ammo);p.mana=Math.min(p.maxMana,p.mana+n);p.ammoFlashMs=C.player.ammoFlashMs;S.sfx("pickup");showToast("AMMO PACK",`${who} gains ${n} shots.`,"cyan")}
  else if(i.kind==="game"){score+=250;stats.games++;run.floorGames.push(i.title);S.sfx("pickup");awardXP(p,100,"C64 game rescued");showToast(`C64 RESCUED: ${i.title}`,"Unbanked until this floor is cleared or you extract. +250 score.","gold",6500)}
  else if(i.kind==="credits"){score+=125;S.sfx("pickup");showToast("GOLD SCORE COIN","+125 score.","gold")}
  else if(i.kind==="xpOrb"){S.sfx("pickup");awardXP(p,175,"XP Orb collected");showToast("XP ORB","+175 XP unless your current floor cap has been reached.","cyan")}
  else if(i.kind==="torch")storeConsumable(p,{kind:"torch",name:"Flaming Torch",short:"TORCH"},"FLAMING TORCH","Stored in its own inventory slot. Press Q to light it.","gold");
  else if(i.kind==="teleport")storeConsumable(p,{kind:"teleport",name:"Teleport Spell",short:"WARP"},"TELEPORT SPELL","Stored. Press R to warp to a safe explored room.","purple");
  else if(i.kind==="banishment")storeConsumable(p,{kind:"banishment",name:"Banishment Flask",short:"BANISH"},"BANISHMENT FLASK","Stacked in inventory. Watch for the flashing Banishment prompt near a Death Stalker or Count Loadula.","purple");
  else if(i.kind==="armour"){p.armor=Math.min(12,p.armor+2);S.sfx("armour");showToast("ARMOUR PLATE",`${who} gains 2 armour.`,"cyan")}
  else if(i.kind==="potion")storeConsumable(p,{kind:"potion",name:"Restoration Potion",short:"POTION"},"RESTORATION POTION","Stored. Press E to drink it.","green");
  else if(i.kind==="weapon")equipWeapon(p,PGR.generateWeapon(world.rooms[W.roomAt(world,p.x,p.y)]?.depth||0,run.floor,Math.random));
  else if(i.kind==="rapid"){p.rapidMs=12000;S.sfx("weapon");showToast("RAPID FIRE","Fire delay reduced for 12 seconds.","gold")}
  else if(i.kind==="inventorySlot"){const before=PGR.inventoryCapacity(p);p.inventorySlots=Math.min(C.player.inventorySlots,before+1);S.sfx("level");showToast("RARE INVENTORY EXPANSION",p.inventorySlots>before?`Inventory expanded to ${p.inventorySlots} slots for this run.`:"Inventory is already fully expanded.","gold",8000)}
  else if(i.kind==="bronze"){p.bronzeKeys++;S.sfx("bronze");showToast("BRONZE KEY","Opens one bronze door or locked chest. Main objectives never depend on these.","gold")}
  else if(i.kind==="exitSigil"){host.exitSigilCollected=true;score+=650;S.sfx("exitSigil");shake=9;awardXP(p,260,"Exit Sigil recovered");SYS.updateObjective(host,run,Math.round(PGR.roomCompletion(explored.get(p.id)||new Set(),world)*100));showToast("EXIT SIGIL ACQUIRED","The floor exit can now be unlocked once the main objective is complete. Getting back alive is the final problem.","gold",10000)}
  else if(i.kind==="key"){score+=400;S.sfx("mainKey");shake=7;awardXP(p,140,"Main vault key");showToast("MAIN VAULT KEY",`${host.keysCollected}/${C.keyTarget} recovered. The Exit Sigil is a separate requirement.`,"gold",9000)}
  updateQuests();PGR.checkAchievements(run,p)
}
function usePotion(p){const ix=PGR.firstInventory(p,"potion");if(ix<0){S.sfx("empty");showToast("NO POTION","There is no restoration potion in your inventory stacks.","red");return}PGR.inventoryRemove(p,ix);const heal=4+(p.potionBonus||0);p.health=Math.min(p.maxHealth,p.health+heal);p.hpBarMs=3200;p.mana=Math.min(p.maxMana,p.mana+8);S.sfx("potion");showToast("POTION USED",`+${heal} health and +8 ammo.`,"green");sync()}
function banishmentState(p){const range=C.stalker.banishPromptDistance||8,hasFlask=PGR.firstInventory(p,"banishment")>=0,voids=(host?.enemies||[]).filter(e=>e.alive&&isDeathStalkerEnemy(e)&&md(e,p)<=range),count=host?.stalker?.awake&&!host.stalker.permanentlyBanished&&md(host.stalker,p)<=range?host.stalker:null,targets=[...voids,...(count?[count]:[])].sort((a,b)=>md(a,p)-md(b,p));return{ready:hasFlask&&targets.length>0,hasFlask,range,targets,nearest:targets[0]||null}}
function dropBanishmentArtefact(target,sourceName){const loot={kind:"bountyArtefact",rarity:"GOLD MEDAL",name:`${sourceName} Banishment Artefact`,scoreValue:10000,xpValue:2000};host.items.push({id:`banishment-artefact-${run.floor}-${Date.now()}`,x:target.x,y:target.y,kind:"loot",loot,active:true,title:loot.name})}
function offerBanishmentArtefact(p,loot){pendingBanishmentReward={p,loot};mode="artefactchoice";input.clear();if(UI.artefactChoiceName)UI.artefactChoiceName.textContent=`${loot.name} can be converted into ${Number(loot.scoreValue||10000).toLocaleString()} SCORE for a Daily Dungeon push, or ${Number(loot.xpValue||2000).toLocaleString()} XP for faster progression.`;UI.artefactChoice?.classList.remove("hidden");S.sfx("shrine")}
function claimBanishmentArtefact(choice){const reward=pendingBanishmentReward;if(!reward)return;const p=reward.p||p1,loot=reward.loot||{},takeScore=choice==="score";if(takeScore){const amount=loot.scoreValue||10000;score+=amount;floatText(p.x,p.y,`+${amount.toLocaleString()} SCORE`,P.gold);showToast("ARTEFACT CONVERTED",`${amount.toLocaleString()} score added to this run.`,"gold",7000)}else{const amount=loot.xpValue||2000;awardXP(p,amount,"Banishment Artefact converted");floatText(p.x,p.y,`+${amount.toLocaleString()} XP`,P.cyan);showToast("ARTEFACT CONVERTED",`${amount.toLocaleString()} XP applied to your run.`,"cyan",7000)}pendingBanishmentReward=null;UI.artefactChoice?.classList.add("hidden");mode="playing";sync()}
function permanentlyBanish(target,p){
  const name=target===host.stalker?C.stalker.name:"Death Stalker";
  if(target===host.stalker){target.awake=false;target.near=false;target.permanentlyBanished=true;target.spawnTimer=Number.POSITIVE_INFINITY;S.setStalkerNear(false)}else{target.alive=false;target.hp=0;target.permanentlyBanished=true;host.defeatedDeathStalkers=host.defeatedDeathStalkers||[];if(!host.defeatedDeathStalkers.includes(target.id))host.defeatedDeathStalkers.push(target.id);const tr=(host.timedRooms||[]).find(t=>t.hunterId===target.id);if(tr)tr.stalkerDefeated=true;run.stats.kills++}
  dropBanishmentArtefact(target,name);awardXP(p,250,`${name} permanently banished`);S.sfx("elite");burst(target.x,target.y,P.purple,30,1.8);ring(target.x,target.y,P.gold,46);floatText(target.x,target.y,"BANISHED!",P.gold);showToast(`${name.toUpperCase()} DESTROYED`,`Permanently removed from this floor. A Banishment Artefact has dropped — collect it and choose 10,000 SCORE or 2,000 XP.`,"green",10500);host.revision++;broadcastWorld()
}
function activateBanishment(p){
  const ix=PGR.firstInventory(p,"banishment");if(ix<0){S.sfx("empty");return false}const state=banishmentState(p);if(!state.ready){showToast("BANISHMENT OUT OF RANGE",`Move within ${state.range} tiles of a Death Stalker or Count Loadula. The B prompt will flash when the potion can kill it.`,"cyan",5600);return false}
  PGR.inventoryRemove(p,ix);S.sfx("shrine");shake=Math.max(shake,9);permanentlyBanish(state.nearest,p);sync();return true
}
function useUtility(p){const ix=PGR.firstInventory(p,"torch");if(ix>=0){const it=PGR.inventoryRemove(p,ix);p.torchMs=C.player.torchMs+(p.torchBonusMs||0);S.sfx("torch");run.alert=Math.min(100,run.alert+10);showToast(it.name||"FLAMING TORCH",`Visibility expands to ${C.player.torchRadius*2} tiles across for ${Math.ceil(p.torchMs/1000)} seconds. The flame increases dungeon alert.`,"gold");sync();return}S.sfx("empty");showToast("NO TORCH","Q is reserved for torches. Find a Flaming Torch or open TAB to check your stacks.","red",5200)}
function useTeleport(p){const ix=PGR.firstInventory(p,"teleport");if(ix<0){S.sfx("empty");showToast("NO TELEPORT SPELL","Find a Teleport Spell in the dungeon or a chest.","red",5200);return false}const ex=explored.get(p.id)||new Set(),rooms=world.rooms.filter(r=>!r.optional&&r.id!==W.roomAt(world,p.x,p.y)).filter(r=>ex.has(`${Math.floor(r.x+r.w/2)},${Math.floor(r.y+r.h/2)}`)),room=rooms.sort((a,b)=>Math.random()-.5).find(r=>md(p,{x:Math.floor(r.x+r.w/2),y:Math.floor(r.y+r.h/2)})>10);if(!room){showToast("TELEPORT HAS NO ANCHOR","Explore another room before using this spell.","cyan",5600);return false}const cells=[];for(let y=room.y+1;y<room.y+room.h;y++)for(let x=room.x+1;x<room.x+room.w;x++)if(W.walkable(world.map,x,y,host)&&!host.enemies.some(e=>e.alive&&e.x===x&&e.y===y))cells.push({x,y});const q=cells[Math.floor(Math.random()*cells.length)];if(!q)return false;PGR.inventoryRemove(p,ix);burst(p.x,p.y,P.purple,22,1.5);p.x=p.rx=q.x;p.y=p.ry=q.y;burst(p.x,p.y,P.cyan,24,1.6);ring(p.x,p.y,P.purple,48);S.sfx("warp");showToast("TELEPORT SPELL",`Warped to ${W.themeAt(world,p.x,p.y).name}.`,"purple",6500);reveal(p);updateRoomMessage(p,true);sync();return true}
function useBanishment(p){return activateBanishment(p)}
function useInventorySlot(p,index){const it=p?.inventory?.[index];if(!it)return;if(it.kind==="potion"){PGR.inventoryRemove(p,index);const heal=4+(p.potionBonus||0);p.health=Math.min(p.maxHealth,p.health+heal);p.hpBarMs=3200;p.mana=Math.min(p.maxMana,p.mana+8);p.ammoFlashMs=C.player.ammoFlashMs;S.sfx("potion");showToast("POTION USED",`+${heal} health and +8 ammo.`,"green")}else if(it.kind==="torch"){PGR.inventoryRemove(p,index);p.torchMs=C.player.torchMs+(p.torchBonusMs||0);run.alert=Math.min(100,run.alert+10);S.sfx("torch");showToast("TORCH LIT",`Visibility expands to ${C.player.torchRadius*2} tiles across for ${Math.ceil(p.torchMs/1000)} seconds.`,"gold")}else if(it.kind==="teleport"){useTeleport(p)}else if(it.kind==="banishment"){activateBanishment(p)}else{showToast("CANNOT QUICK-USE",`${it.name||it.kind} is not a consumable.`,"cyan")}sync();renderInventoryPanel()}
function dropInventorySlot(p,index){const it=PGR.inventoryRemove(p,index);if(!it)return;const kind=it.kind==="artefact"?"loot":it.kind,drop={id:`dropped-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,x:p.x,y:p.y,kind,active:true,title:it.name||PGR.inventoryLabel(it),carriedItem:{...it}};if(kind==="loot")drop.loot={kind:"artefact",rarity:it.rarity||"SIZZLER",name:it.name||"Dropped Artefact",xp:0};host.items.push(drop);host.revision++;showToast("ITEM DROPPED",`${it.name||it.kind} is now on the floor here. You can come back for it later.`,"cyan");broadcastWorld();sync();renderInventoryPanel()}
