window.CCGNetwork=(()=>{"use strict";
const C=window.CCG_CONFIG;const alphabet="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
function id(n=10){const b=new Uint8Array(n);crypto.getRandomValues(b);return Array.from(b,x=>alphabet[x%alphabet.length]).join("")}
function code(v){return String(v||"").toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6)}
function sleep(ms){return new Promise(resolve=>setTimeout(resolve,ms))}
function localDev(){return /^(localhost|127\.0\.0\.1|0\.0\.0\.0)$/i.test(location.hostname)}
class RoomNetwork{
 constructor(cb={}){this.cb=cb;this.sessionId=id(12);this.name="CCG Player";this.roomCode="";this.mode="solo";this.transport="solo";this.isHost=true;this.connected=false;this.members=new Map();this.joinedAt=Date.now();this.bc=null;this.client=null;this.channel=null;this.heartbeat=null;this.roomIntent="join";this._capacityRejected=false;this._lastMemberSignature=""}
 createCode(){return id(5)}
 setSolo(name){this.leave();this.mode="solo";this.transport="solo";this.name=name||"CCG Player";this.isHost=true;this.connected=false;this.roomCode="";this.members.set(this.sessionId,{id:this.sessionId,name:this.name,joinedAt:this.joinedAt,lastSeen:Date.now(),roomRole:"solo"});this.syncMembers()}
 async getSupabase(){if(window.ccgSupabase?.getClient)return window.ccgSupabase.getClient();if(/cheekycommodoregamer\.co\.uk$/i.test(location.hostname)){await this.load("/js/ccg-supabase-config.js");await this.load("/js/ccg-supabase-client.js");if(window.ccgSupabase?.getClient)return window.ccgSupabase.getClient()}return null}
 load(src){return new Promise((res,rej)=>{const ex=document.querySelector(`script[src="${src}"]`);if(ex){if(window.ccgSupabase?.getClient){res();return}ex.addEventListener("load",res,{once:true});setTimeout(()=>window.ccgSupabase?.getClient&&res(),0);return}const s=document.createElement("script");s.src=src;s.onload=res;s.onerror=rej;document.head.appendChild(s)})}
 async join(room,name,options={}){await this.leave();this.roomCode=code(room);if(this.roomCode.length<4)throw new Error("Room code must be at least four characters.");this.name=String(name||"CCG Player").trim().slice(0,18)||"CCG Player";this.joinedAt=Date.now();this.mode="coop";this.roomIntent=options.intent==="create"?"create":"join";this._capacityRejected=false;let supabase=null;try{supabase=await this.getSupabase()}catch(error){console.error("Lost Sizzler Realtime client failed",error)}if(!supabase){if(localDev()&&options.allowLocalDev===true){this.joinLocal();return{code:this.roomCode,transport:this.transport,members:this.getMembers()}}throw new Error("Online multiplayer could not connect to CCG Realtime. This room has not been created.")}await this.joinSupabase(supabase);if(this.roomIntent==="create")await this.verifyFreshRoom();else await this.verifyExistingRoom();if(this._capacityRejected){await this.leave();throw new Error(`Room is full. The Lost Sizzler supports a maximum of ${C.maxPlayers} online players.`)}this.send("hello",{id:this.sessionId,name:this.name,joinedAt:this.joinedAt,roomCode:this.roomCode});return{code:this.roomCode,transport:this.transport,members:this.getMembers()}}
 createOnlineRoom(room,name){return this.join(room,name,{intent:"create"})}
 joinExistingRoom(room,name){return this.join(room,name,{intent:"join"})}
 joinLocal(){this.transport="local";this.connected=true;this.bc=new BroadcastChannel(`ccg-quest:${this.roomCode}`);this.bc.onmessage=e=>this.receiveLocal(e.data);this.touchMember({id:this.sessionId,name:this.name,joinedAt:this.joinedAt,roomRole:this.roomIntent});this.postLocal({type:"hello",member:{id:this.sessionId,name:this.name,joinedAt:this.joinedAt,roomRole:this.roomIntent}});this.heartbeat=setInterval(()=>{this.postLocal({type:"heartbeat",member:{id:this.sessionId,name:this.name,joinedAt:this.joinedAt,roomRole:this.roomIntent}});this.prune()},1000);this.syncMembers()}
 receiveLocal(m){if(!m||m.sender===this.sessionId)return;if(m.type==="hello"||m.type==="heartbeat"){this.touchMember(m.member);if(m.type==="hello")this.postLocal({type:"heartbeat",member:{id:this.sessionId,name:this.name,joinedAt:this.joinedAt,roomRole:this.roomIntent}});this.syncMembers();return}if(m.type==="bye"){this.members.delete(m.memberId);this.syncMembers();return}if(m.type==="packet")this.cb.onPacket?.(m.event,m.payload)}
 postLocal(obj){this.bc?.postMessage({...obj,sender:this.sessionId})}
 touchMember(m){if(m?.id)this.members.set(m.id,{...m,lastSeen:Date.now()})}
 prune(){const now=Date.now();for(const [k,m] of this.members)if(k!==this.sessionId&&now-m.lastSeen>3500)this.members.delete(k);this.syncMembers()}
 async joinSupabase(client){this.transport="supabase";this.client=client;this.channel=client.channel(`ccg-quest:${this.roomCode}`,{config:{presence:{key:this.sessionId},broadcast:{self:false,ack:true}}});this.channel.on("presence",{event:"sync"},()=>this.syncSupabasePresence()).on("presence",{event:"join"},()=>this.syncSupabasePresence()).on("presence",{event:"leave"},()=>this.syncSupabasePresence()).on("broadcast",{event:"ccg_packet"},({payload})=>this.cb.onPacket?.(payload?.event,payload?.payload));await new Promise((res,rej)=>{let done=false;const finishError=message=>{if(done)return;done=true;clearTimeout(t);rej(new Error(message))};const t=setTimeout(()=>finishError("Timed out connecting to CCG Realtime."),10000);this.channel.subscribe(async status=>{if(status==="SUBSCRIBED"&&!done){try{const tracked=await this.channel.track({id:this.sessionId,name:this.name,joinedAt:this.joinedAt,roomRole:this.roomIntent,build:"V10.5"});if(tracked&&tracked!="ok"&&tracked.status&&tracked.status!=="ok")throw new Error("Presence tracking failed");done=true;clearTimeout(t);this.connected=true;this.syncSupabasePresence();res()}catch(error){finishError(error?.message||"Could not register in the online room.")}}else if(status==="CHANNEL_ERROR")finishError("Could not join the CCG Realtime room.");else if(status==="TIMED_OUT")finishError("CCG Realtime timed out while joining the room.");else if(status==="CLOSED"&&!done)finishError("The CCG Realtime room closed before joining completed.")})})}
 syncSupabasePresence(){if(!this.channel)return;this.members.clear();const raw=this.channel.presenceState();for(const arr of Object.values(raw))for(const p of arr)this.touchMember(p);this.touchMember({id:this.sessionId,name:this.name,joinedAt:this.joinedAt,roomRole:this.roomIntent,build:"V10.5"});this.syncMembers()}
 async verifyFreshRoom(){for(let i=0;i<5;i++){this.syncSupabasePresence();const others=[...this.members.values()].filter(member=>member.id!==this.sessionId);if(others.length){await this.leave();throw new Error("That randomly generated room code is already in use. Create another room.")}await sleep(120)}return true}
 async verifyExistingRoom(){for(let i=0;i<40;i++){this.syncSupabasePresence();if(this._capacityRejected)return false;const peers=[...this.members.values()].filter(member=>member.id!==this.sessionId);if(peers.length){const host=[...this.members.values()].sort((a,b)=>(a.joinedAt-b.joinedAt)||a.id.localeCompare(b.id))[0];if(host&&host.id!==this.sessionId)return true}await sleep(125)}await this.leave();throw new Error("Room not found or the host is no longer online. Check the room code and try again.")}
 syncMembers(){const all=[...this.members.values()].sort((x,y)=>(x.joinedAt-y.joinedAt)||x.id.localeCompare(y.id));const admitted=all.slice(0,C.maxPlayers),was=this.isHost;this._capacityRejected=all.length>C.maxPlayers&&!admitted.some(member=>member.id===this.sessionId);this.isHost=(admitted[0]?.id||this.sessionId)===this.sessionId;this._lastMemberSignature=admitted.map(member=>member.id).join("|");this.cb.onMembers?.(admitted,this.isHost,was!==this.isHost)}
 send(event,payload){if(this.mode!=="coop"||!this.connected)return Promise.resolve(null);if(this.transport==="local"){this.postLocal({type:"packet",event,payload});return Promise.resolve("ok")}return this.channel?.send({type:"broadcast",event:"ccg_packet",payload:{event,payload}})}
 async leave(){if(this.heartbeat){clearInterval(this.heartbeat);this.heartbeat=null}if(this.bc){this.postLocal({type:"bye",memberId:this.sessionId});this.bc.close();this.bc=null}if(this.channel){try{await this.channel.untrack()}catch(_){}try{await this.client?.removeChannel(this.channel)}catch(_){}this.channel=null}this.members.clear();this.connected=false;this.isHost=true;this._capacityRejected=false;this._lastMemberSignature=""}
 getMembers(){return[...this.members.values()].sort((a,b)=>(a.joinedAt-b.joinedAt)||a.id.localeCompare(b.id)).slice(0,C.maxPlayers)}
 getDiagnostics(){return{connected:this.connected,transport:this.transport,roomCode:this.roomCode,isHost:this.isHost,memberCount:this.getMembers().length,members:this.getMembers().map(member=>({id:member.id,name:member.name,role:member.roomRole||"peer"}))}}
}
RoomNetwork.prototype.__v104CapacityPatched=true;
return{RoomNetwork,cleanCode:code};})();