function onMembers(members,isHost,changed){if(changed&&isHost&&mode==="playing"){say("<strong>HOST MIGRATION.</strong> You're now running the dungeon simulation.");broadcastWorld()}sync()}
function onPacket(event,p){if(event==="player")onPlayer(p);else if(event==="shot")spawnBullet(p,true);else if(event==="enemy_shot")spawnEnemyShot(p);else if(event==="hit")onHit(p);else if(event==="player_hit"&&p?.target===p1?.id)hurtPlayer(p1,p.power||1,true,p.source||"another player");else if(event==="collect")onCollectRequest(p);else if(event==="collected")onCollected(p);else if(event==="world")onWorld(p);else if(event==="hello"&&net.isHost)broadcastWorld();else if(event==="notice")say(p?.html||"");else if(event==="fx")onFX(p);else if(event==="complete")finish(p?.by||"the team")}
function onPlayer(p){if(!p||p.id===net.sessionId)return;const old=remote.get(p.id);remote.set(p.id,{...p,rx:old?.rx??p.x,ry:old?.ry??p.y,lastSeen:performance.now()})}
function sendPlayer(){if(playMode!=="online")return;net.send("player",{id:p1.id,name:p1.name,x:p1.x,y:p1.y,health:p1.health,dir:p1.dir,torchMs:p1.torchMs,armor:p1.armor})}
function serialWorld(){return{revision:host.revision,keysCollected:host.keysCollected,exitOpen:host.exitOpen,doors:host.doors.map(d=>({...d})),chests:(host.chests||[]).map(c=>({...c})),enemies:host.enemies.map(e=>({...e,lastSeen:e.lastSeen?{...e.lastSeen}:null,follower:e.follower||null})),items:host.items.map(i=>({...i}))}}
function broadcastWorld(){if(playMode==="online"&&net.connected&&net.isHost)net.send("world",serialWorld())}
function onWorld(s){if(!s||net.isHost)return;if(!host||Number(s.revision)>=Number(host.revision)){host={revision:Number(s.revision||0),keysCollected:Number(s.keysCollected||0),exitOpen:Boolean(s.exitOpen),doors:Array.isArray(s.doors)?s.doors:[],chests:Array.isArray(s.chests)?s.chests:[],enemies:Array.isArray(s.enemies)?s.enemies:[],items:Array.isArray(s.items)?s.items:[]};sync()}}
function hostEnemyStep(dt){if(!net.isHost)return;A.stepEnemies(host,world.map,allPlayers(),dt,{shoot:s=>{spawnEnemyShot(s);if(playMode==="online")net.send("enemy_shot",s)},melee:(e,target,power)=>{const lp=findLocal(target.id);if(lp)hurtPlayer(lp,power,false,e.follower?.name||e.kind);else if(playMode==="online")net.send("player_hit",{target:target.id,power,source:e.follower?.name||e.kind})},notice:(html,sound)=>{say(html);if(sound)S.sfx(sound);if(playMode==="online")net.send("notice",{html})},alert:(e,state)=>{const near=localPlayers().some(p=>md(e,p)<9);if(state==="alert"&&near){S.sfx("alert");floatText(e.x,e.y,"!",P.red)}if(state==="search"&&near)S.sfx("search")}},world)}
function onHit(p){if(!net.isHost||!p?.enemyId)return;const e=host.enemies.find(x=>x.id===p.enemyId&&x.alive);if(e){if(p.source)A.alertEnemy(e,p.source.x,p.source.y);damageEnemy(e,Math.max(1,Math.min(4,Number(p.power||1))))}}
function damageEnemy(e,power){if(!e.alive)return;e.hp-=power;e.flash=160;S.sfx("hit");burst(e.x,e.y,P.orange,8,1.2);ring(e.x,e.y,P.orange,20);floatText(e.x,e.y,`-${power}`,P.white);if(e.hp<=0){e.hp=0;e.alive=false;host.revision++;score+=e.follower?500:120;if(e.follower)stats.elites++;const fx={type:"death",x:e.x,y:e.y,color:e.follower?P.gold:P.pink,elite:Boolean(e.follower)};onFX(fx);if(playMode==="online")net.send("fx",fx);if(e.follower){S.sfx("elite");showToast(`${e.follower.name.toUpperCase()} FREED`,`The Score Goblin's influence has worn off. +500 points.`,"green");if(e.follower.name==="CPU")host.items.push({id:`food-${Date.now()}`,x:e.x,y:e.y,kind:"health",active:true,title:"CPU's Emergency Roast"})}else S.sfx("death");updateQuests();broadcastWorld()}}
function onFX(p){if(!p)return;if(p.type==="death"){burst(p.x,p.y,p.color||P.pink,p.elite?28:18,p.elite?1.8:1.35);ring(p.x,p.y,p.color||P.pink,p.elite?42:30);shake=Math.max(shake,p.elite?11:6);floatText(p.x,p.y,p.elite?"FREED!":"ZAPPED!",p.color||P.gold)}}
function onCollectRequest(p){if(!net.isHost||!p?.itemId)return;const i=host.items.find(x=>x.id===p.itemId&&x.active);if(!i)return;i.active=false;if(i.kind==="key"){host.keysCollected=Math.min(C.keyTarget,host.keysCollected+1);host.exitOpen=host.keysCollected>=C.keyTarget}host.revision++;const ev={item:{...i},collector:p.collector};onCollected(ev);if(playMode==="online")net.send("collected",ev);broadcastWorld();sync()}
function requestCollect(i,p){if(!i.active||pendingItems.has(i.id))return;pendingItems.add(i.id);if(playMode==="online"&&p.id===p1.id&&!net.isHost)net.send("collect",{itemId:i.id,collector:p.id});else onCollectRequest({itemId:i.id,collector:p.id});setTimeout(()=>pendingItems.delete(i.id),500)}
function onCollected(ev){const i=ev?.item;if(!i)return;const p=findLocal(ev.collector);ring(i.x,i.y,i.kind==="key"?P.gold:i.kind==="health"?P.green:i.kind==="mana"?P.cyan:P.white,34);burst(i.x,i.y,P.gold,14,1.2);if(!p){if(i.kind==="key"){S.sfx("key");say(`<strong>TEAM KEY FOUND.</strong> ${host.keysCollected}/${C.keyTarget}.`)}return}applyItem(i,p);sync()}
function applyItem(i,p){const who=p===p2?"P2":"P1";if(i.kind==="health"){p.health=Math.min(p.maxHealth,p.health+3);S.sfx("pickup");showToast("HEALTH PACK",`${who} restores 3 health.`,"green")}else if(i.kind==="mana"||i.kind==="ammo"){p.mana=Math.min(p.maxMana,p.mana+18);S.sfx("pickup");showToast("AMMO PACK",`${who} gains 18 shots.`,"cyan")}else if(i.kind==="game"){score+=250;stats.games++;S.sfx("pickup");showToast(`C64 RESCUED: ${i.title}`,"Onto the CCG shelf. +250 points.","gold")}else if(i.kind==="credits"){score+=125;S.sfx("pickup");showToast("CCG TOKEN","125 points. The arcade manager looks disappointed.","gold")}else if(i.kind==="sensor"){S.sfx("cloak");showToast("MAP PULSE","The minimap remembers explored corridors. Enemies in darkness remain hidden.","cyan")}else if(i.kind==="torch"){p.torchMs=C.player.torchMs;S.sfx("torch");showToast("FLAMING TORCH","Fog radius expands from 10 tiles across to 20 for 24 seconds. The flame also makes you easier to spot.","gold")}else if(i.kind==="armour"){p.armor=Math.min(6,p.armor+2);S.sfx("armour");showToast("ARMOUR PLATE",`${who} gains 2 armour. Armour absorbs incoming damage first.`,"cyan")}else if(i.kind==="potion"){p.potions++;S.sfx("potion");showToast("RESTORATION POTION",`${who} stores a potion. P1: E • P2: O`,"green")}else if(i.kind==="weapon"){p.weaponLevel=Math.min(3,p.weaponLevel+1);stats.weapons++;S.sfx("weapon");showToast(`WEAPON UPGRADE LV${p.weaponLevel}`,p.weaponLevel===2?"Shots now hit harder.":"Triple-shot unlocked and more projectiles can be active.","gold")}else if(i.kind==="rapid"){p.rapidMs=12000;S.sfx("weapon");showToast("RAPID FIRE","Fire delay reduced for 12 seconds.","gold")}else if(i.kind==="bronze"){p.bronzeKeys++;S.sfx("bronze");showToast("BRONZE KEY","Opens one optional treasure door. Main quest keys are separate.","gold")}else if(i.kind==="treasure"){S.sfx("weapon");showToast("TREASURE VAULT",`Bonus reward: ${i.reward.toUpperCase()}.`,"gold");applyItem({kind:i.reward,title:"Vault Reward"},p)}else if(i.kind==="key"){score+=400;S.sfx("key");shake=7;showToast("MAIN VAULT KEY",`${host.keysCollected}/${C.keyTarget} recovered. These keys never spawn behind locked bonus doors.`,"gold");if(host.exitOpen){setTimeout(()=>S.sfx("open"),150);say("<strong>MAIN VAULT OPEN.</strong> The purple exit is now active.")}}updateQuests()}
function usePotion(p){if(!p||p.potions<=0){S.sfx("empty");showToast("NO POTION","You appear to have drunk the last one already.","red");return}p.potions--;p.health=Math.min(p.maxHealth,p.health+4);p.mana=Math.min(p.maxMana,p.mana+4);S.sfx("potion");showToast("POTION USED","+4 health and +4 mana.","green");sync()}
