function camFor(p,v){let c=cameras.get(p.id)||{x:0,y:0};const tx=Math.max(0,Math.min(C.worldWidth*C.tile-v.w,p.rx*C.tile+C.tile/2-v.w/2)),ty=Math.max(0,Math.min(C.worldHeight*C.tile-v.h,p.ry*C.tile+C.tile/2-v.h/2));c.x=tx;c.y=ty;cameras.set(p.id,c);return c}
function ws(x,y){return{x:view.x+x*C.tile-cam.x+renderShake.x,y:view.y+y*C.tile-cam.y+renderShake.y}}
function drawTile(x,y){const s=ws(x,y),th=W.themeAt(world,x,y),wall=world.map[y][x]!==0;if(wall){ctx.fillStyle=th.wall;ctx.fillRect(s.x,s.y,C.tile,C.tile);ctx.fillStyle=th.hi;ctx.fillRect(s.x+2,s.y+2,C.tile-4,4);ctx.fillStyle="rgba(0,0,0,.25)";ctx.fillRect(s.x+C.tile-4,s.y+5,4,C.tile-5);ctx.fillRect(s.x+5,s.y+C.tile-4,C.tile-5,4)}else{ctx.fillStyle=(x+y)%2?th.floor:th.alt;ctx.fillRect(s.x,s.y,C.tile,C.tile);const code=(x*31+y*17+W.roomAt(world,x,y)*7)%37;ctx.fillStyle=th.accent+"22";if(code===0)ctx.fillRect(s.x+7,s.y+7,5,2);if(code===9)ctx.fillRect(s.x+20,s.y+19,3,5);if(th.name==="Budget Bin"&&code===12){ctx.fillStyle="#ffd85a44";ctx.fillRect(s.x+5,s.y+22,8,4)}}}
function drawDoors(){for(const d of host.doors){const s=ws(d.x,d.y);ctx.fillStyle=d.locked?"#6e4c22":"rgba(110,76,34,.22)";ctx.fillRect(s.x+4,s.y+2,C.tile-8,C.tile-4);ctx.strokeStyle=d.locked?P.gold:"#67533b";ctx.lineWidth=2;ctx.strokeRect(s.x+5,s.y+3,C.tile-10,C.tile-6);ctx.fillStyle=P.gold;ctx.fillRect(s.x+19,s.y+14,3,3)}}
function drawExit(){const s=ws(world.exit.x,world.exit.y),t=performance.now()/220;ctx.save();ctx.translate(s.x+15,s.y+15);ctx.strokeStyle=host.exitOpen?P.purple:"#66586e";ctx.lineWidth=3;ctx.shadowColor=host.exitOpen?P.purple:"transparent";ctx.shadowBlur=host.exitOpen?15:0;ctx.strokeRect(-9,-11,18,22);ctx.strokeRect(-4,-6,8,12);if(host.exitOpen){ctx.rotate(t);ctx.beginPath();ctx.arc(0,0,18,-.4,1.5);ctx.stroke()}ctx.restore()}
function itemInfo(i){return{key:["KEY",P.gold],health:["+",P.green],mana:["AM",P.cyan],ammo:["AM",P.cyan],game:["C64",P.white],credits:["£",P.gold],sensor:["R",P.cyan],torch:["T",P.gold],armour:["A",P.blue],potion:["P",P.green],weapon:["W",P.orange],rapid:["RF",P.orange],bronze:["BK",P.gold],treasure:["?",P.gold]}[i.kind]||["?",P.white]}
function drawItem(i){if(!i.active)return;const s=ws(i.x,i.y),[txt,col]=itemInfo(i),pulse=1+Math.sin(performance.now()/155+i.x)*.08;ctx.save();ctx.translate(s.x+15,s.y+15);ctx.scale(pulse,pulse);ctx.shadowColor=col;ctx.shadowBlur=9;ctx.fillStyle=col;ctx.fillRect(-7,-7,14,14);ctx.fillStyle="#160d1b";ctx.font='bold 7px "Courier New"';ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(txt,0,1);ctx.restore()}
function drawChests(){for(const c of host.chests||[]){if(!c.active)continue;const s=ws(c.x,c.y);ctx.save();ctx.shadowColor=c.locked?P.gold:P.cyan;ctx.shadowBlur=8;ctx.fillStyle="#5a351d";ctx.fillRect(s.x+4,s.y+10,C.tile-8,C.tile-11);ctx.fillStyle="#a86b32";ctx.fillRect(s.x+4,s.y+6,C.tile-8,7);ctx.strokeStyle=c.locked?P.gold:P.cyan;ctx.lineWidth=2;ctx.strokeRect(s.x+4,s.y+6,C.tile-8,C.tile-7);ctx.fillStyle=P.gold;ctx.fillRect(s.x+C.tile/2-2,s.y+14,4,5);ctx.restore();if(md(c,focus)<=2)label(c.locked?"LOCKED CHEST":"CHEST",{x:s.x,y:s.y-1},c.locked?P.gold:P.cyan)}}
function label(text,s,col=P.white){ctx.save();ctx.font='bold 7px "Courier New"';const w=Math.min(96,ctx.measureText(text).width+6);ctx.fillStyle="rgba(5,3,8,.86)";ctx.fillRect(s.x+15-w/2,s.y-8,w,9);ctx.fillStyle=col;ctx.textAlign="center";ctx.fillText(text,s.x+15,s.y-1);ctx.restore()}
function enemyScreen(e){let v=enemyVisuals.get(e.id);if(!v){v={rx:e.x,ry:e.y};enemyVisuals.set(e.id,v)}const rate=e.aiState==="chase"?.23:.14;v.rx+=(e.x-v.rx)*rate;v.ry+=(e.y-v.ry)*rate;return ws(v.rx,v.ry)}
function drawEnemy(e){if(!e.alive||!visibleTo(focus,e.x,e.y))return;const s=enemyScreen(e),f=e.follower,img=f?.avatar?avatarImages.get(f.name):null;ctx.fillStyle="rgba(0,0,0,.38)";ctx.beginPath();ctx.ellipse(s.x+15,s.y+25,11,4,0,0,Math.PI*2);ctx.fill();if(img&&img.complete&&img.naturalWidth){ctx.save();ctx.beginPath();ctx.arc(s.x+15,s.y+15,12,0,Math.PI*2);ctx.clip();ctx.drawImage(img,s.x+3,s.y+3,24,24);ctx.restore();ctx.strokeStyle=P.gold;ctx.lineWidth=2;ctx.beginPath();ctx.arc(s.x+15,s.y+15,12,0,Math.PI*2);ctx.stroke()}else{const k=f?.kind||e.kind,col=k==="hunter"?P.gold:k==="charger"?P.cyan:k==="ranger"?P.blue:k==="root"?P.green:k==="cook"?P.orange:k==="firebreather"?P.green:e.kind==="guard"?P.red:e.kind==="ghost"?P.purple:P.pink;ctx.fillStyle=col;ctx.fillRect(s.x+6,s.y+7,18,19);ctx.fillStyle=P.white;ctx.fillRect(s.x+9,s.y+11,4,4);ctx.fillRect(s.x+18,s.y+11,4,4)}label(f?.name||({scout:"Tape Scout",hunter:"Joystick Hunter",ambusher:"Raster Ambusher",guard:"1541 Guard",ghost:"Ghost Byte"}[e.kind]||"Enemy"),s,f?P.gold:P.white);if(e.aiState==="chase"||e.aiState==="search"){ctx.font='bold 14px "Courier New"';ctx.textAlign="center";ctx.fillStyle=e.aiState==="chase"?P.red:P.gold;ctx.fillText(e.aiState==="chase"?"!":"?",s.x+15,s.y-13)}}
function drawPlayer(p,kind="p1"){const s=ws(p.rx,p.ry),col=kind==="p2"?P.green:kind==="remote"?P.cyan:P.gold;ctx.fillStyle="rgba(0,0,0,.38)";ctx.beginPath();ctx.ellipse(s.x+15,s.y+26,12,4,0,0,Math.PI*2);ctx.fill();ctx.save();ctx.translate(s.x+15,s.y+15);ctx.fillStyle=col+"22";ctx.shadowColor=col;ctx.shadowBlur=p.torchMs>0?18:8;ctx.beginPath();ctx.arc(0,0,p.torchMs>0?22:19,0,Math.PI*2);ctx.fill();ctx.strokeStyle=col;ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,18,0,Math.PI*2);ctx.stroke();if(logo.complete&&logo.naturalWidth){const r=logo.naturalWidth/logo.naturalHeight;let dw=40,dh=dw/r;if(dh>24){dh=24;dw=dh*r}ctx.drawImage(logo,-dw/2,-dh/2,dw,dh)}else{ctx.fillStyle=col;ctx.font='bold 10px "Courier New"';ctx.textAlign="center";ctx.fillText("CCG",0,3)}if(p.torchMs>0){const flick=2+Math.sin(performance.now()/55+p.x)*2;ctx.fillStyle=P.orange;ctx.beginPath();ctx.moveTo(12,-14);ctx.quadraticCurveTo(8+flick,-25,14,-30);ctx.quadraticCurveTo(20-flick,-23,16,-14);ctx.fill();ctx.fillStyle=P.gold;ctx.beginPath();ctx.arc(14,-18,3,0,Math.PI*2);ctx.fill()}ctx.restore();label(p.name,{x:s.x,y:s.y-2},col)}
function drawShots(){ctx.save();ctx.lineCap="round";for(const b of bullets){const s=ws(b.x,b.y),x=s.x+15,y=s.y+15;ctx.strokeStyle="rgba(255,153,80,.6)";ctx.lineWidth=4;ctx.shadowColor=P.orange;ctx.shadowBlur=9;ctx.beginPath();ctx.moveTo(x-b.dx*12,y-b.dy*12);ctx.lineTo(x+b.dx*3,y+b.dy*3);ctx.stroke()}for(const b of enemyBullets){const s=ws(b.x,b.y),x=s.x+15,y=s.y+15,col=b.style==="food"?P.orange:b.style==="root"?P.green:b.style==="fire"?P.gold:P.red;ctx.strokeStyle=col;ctx.lineWidth=b.style==="fire"?7:4;ctx.shadowColor=col;ctx.shadowBlur=10;ctx.beginPath();ctx.moveTo(x-b.dx*12,y-b.dy*12);ctx.lineTo(x+b.dx*2,y+b.dy*2);ctx.stroke()}ctx.restore()}
function drawEffects(){for(const q of particles){ctx.globalAlpha=Math.max(0,q.life/360);ctx.fillStyle=q.col;ctx.fillRect(view.x+q.x-cam.x,view.y+q.y-cam.y,q.size,q.size)}ctx.globalAlpha=1;for(const r of rings){ctx.globalAlpha=Math.max(0,r.life/340);ctx.strokeStyle=r.col;ctx.lineWidth=2;ctx.beginPath();ctx.arc(view.x+r.x-cam.x,view.y+r.y-cam.y,r.r,0,Math.PI*2);ctx.stroke()}ctx.globalAlpha=1;for(const f of floaters){ctx.globalAlpha=Math.max(0,f.life/420);ctx.fillStyle=f.col;ctx.font='bold 9px "Courier New"';ctx.textAlign="center";ctx.fillText(f.text,view.x+f.x-cam.x,view.y+f.y-cam.y)}ctx.globalAlpha=1}
function drawHazards(){for(const h of hazards){const s=ws(h.x,h.y),t=Math.max(0,h.life/h.maxLife);ctx.globalAlpha=.45+.4*Math.abs(Math.sin(performance.now()/70));ctx.strokeStyle=P.red;ctx.lineWidth=2;ctx.beginPath();ctx.arc(s.x+15,s.y+15,8+(1-t)*8,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1}}
function drawFog(){const ex=explored.get(focus.id)||new Set(),x0=Math.max(0,Math.floor(cam.x/C.tile)-1),x1=Math.min(C.worldWidth-1,Math.ceil((cam.x+view.w)/C.tile)+1),y0=Math.max(0,Math.floor(cam.y/C.tile)-1),y1=Math.min(C.worldHeight-1,Math.ceil((cam.y+view.h)/C.tile)+1);for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++){if(visibleTo(focus,x,y))continue;const s=ws(x,y);ctx.fillStyle=ex.has(`${x},${y}`)?"rgba(0,0,0,.94)":"rgba(0,0,0,1)";ctx.fillRect(s.x,s.y,C.tile,C.tile)}if(focus.torchMs>0){const s=ws(focus.rx,focus.ry),g=ctx.createRadialGradient(s.x+15,s.y+15,15,s.x+15,s.y+15,170);g.addColorStop(0,"rgba(255,216,90,.12)");g.addColorStop(1,"rgba(255,180,60,0)");ctx.fillStyle=g;ctx.fillRect(view.x,view.y,view.w,view.h)}}
function minimap(){const sc=view.w<650?.72:.9,mw=C.worldWidth*sc,mh=C.worldHeight*sc,ox=view.x+view.w-mw-7,oy=view.y+7,ex=explored.get(focus.id)||new Set();ctx.fillStyle="rgba(5,3,8,.90)";ctx.fillRect(ox-3,oy-3,mw+6,mh+6);ctx.strokeStyle="#5c4275";ctx.strokeRect(ox-3,oy-3,mw+6,mh+6);for(let y=0;y<C.worldHeight;y++)for(let x=0;x<C.worldWidth;x++){if(!ex.has(`${x},${y}`))continue;ctx.fillStyle=world.map[y][x]?"#403650":"#211829";ctx.fillRect(ox+x*sc,oy+y*sc,Math.max(1,sc),Math.max(1,sc))}if(ex.has(`${world.exit.x},${world.exit.y}`)){ctx.fillStyle=host.exitOpen?P.purple:"#60536a";ctx.fillRect(ox+world.exit.x*sc,oy+world.exit.y*sc,2.5,2.5)}ctx.fillStyle=P.gold;ctx.fillRect(ox+focus.x*sc,oy+focus.y*sc,3,3)}
function drawViewHUD(p,v){const th=W.themeAt(world,p.x,p.y),torch=Math.ceil(p.torchMs/1000);ctx.save();ctx.fillStyle="rgba(5,3,8,.82)";ctx.strokeStyle=p===p2?P.green:P.purple;ctx.lineWidth=1;ctx.fillRect(v.x+8,v.y+8,230,48);ctx.strokeRect(v.x+8,v.y+8,230,48);ctx.font='bold 10px "Courier New"';ctx.fillStyle=p===p2?P.green:P.gold;ctx.textAlign="left";ctx.fillText(`${p.name}  HP ${p.health}/${p.maxHealth}  ARM ${p.armor}`,v.x+15,v.y+24);ctx.fillStyle=P.cyan;ctx.fillText(`AMMO ${p.mana}/${p.maxMana}  WPN LV${p.weaponLevel}  POT ${p.potions}`,v.x+15,v.y+39);ctx.fillStyle=torch>0?P.gold:"#9b8daa";ctx.fillText(torch>0?`TORCH ${torch}s • 20-TILE LIGHT`:`10-TILE LIGHT`,v.x+15,v.y+52);ctx.textAlign="right";ctx.fillStyle="#d7cbe1";ctx.fillText(th.name.toUpperCase(),v.x+v.w-10,v.y+v.h-12);ctx.restore()}
function renderView(p,v){view=v;focus=p;cam=camFor(p,v);ctx.save();ctx.beginPath();ctx.rect(v.x,v.y,v.w,v.h);ctx.clip();ctx.fillStyle=P.black;ctx.fillRect(v.x,v.y,v.w,v.h);const x0=Math.max(0,Math.floor(cam.x/C.tile)-1),x1=Math.min(C.worldWidth-1,Math.ceil((cam.x+v.w)/C.tile)+1),y0=Math.max(0,Math.floor(cam.y/C.tile)-1),y1=Math.min(C.worldHeight-1,Math.ceil((cam.y+v.h)/C.tile)+1);for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++)drawTile(x,y);drawDoors();drawExit();drawHazards();drawChests();host.items.forEach(drawItem);host.enemies.forEach(drawEnemy);drawShots();for(const r of remote.values())if(performance.now()-r.lastSeen<2600)drawPlayer(r,"remote");for(const lp of localPlayers())drawPlayer(lp,lp===p2?"p2":"p1");drawEffects();drawFog();minimap();drawViewHUD(p,v);ctx.fillStyle="rgba(5,3,8,.72)";ctx.fillRect(v.x+5,v.y+v.h-23,160,18);ctx.fillStyle=p===p2?P.green:P.gold;ctx.font='bold 9px "Courier New"';ctx.fillText(`${p.name}  H:${p.health} A:${p.armor} W:${p.weaponLevel}`,v.x+10,v.y+v.h-11);ctx.restore()}
function render(){if(!world||!p1)return;renderShake=shake>0?{x:(Math.random()-.5)*shake,y:(Math.random()-.5)*shake}:{x:0,y:0};if(shake>0){shake*=.84;if(shake<.25)shake=0}ctx.fillStyle=P.black;ctx.fillRect(0,0,canvas.width,canvas.height);if(p2){renderView(p1,{x:0,y:0,w:canvas.width/2,h:canvas.height});renderView(p2,{x:canvas.width/2,y:0,w:canvas.width/2,h:canvas.height});ctx.fillStyle=P.purple;ctx.fillRect(canvas.width/2-2,0,4,canvas.height)}else renderView(p1,{x:0,y:0,w:canvas.width,h:canvas.height});if(damageFlash>0){ctx.fillStyle=`rgba(255,50,70,${Math.min(.18,damageFlash*.18)})`;ctx.fillRect(0,0,canvas.width,canvas.height)}}
function pause(force=false){if(mode==="playing"&&!force){mode="paused";UI.pause.classList.remove("hidden");S.setMusicLevel(.03)}else if(mode==="paused"){mode="playing";UI.pause.classList.add("hidden");input.clear();S.setMusicLevel(.075)}}
async function toggleFullscreen(){const area=document.querySelector(".game-area");try{if(!document.fullscreenElement)await area.requestFullscreen();else await document.exitFullscreen()}catch(_){showToast("FULLSCREEN UNAVAILABLE","Your browser blocked fullscreen for this session.","red")}}
function toggleSound(){S.toggle();sync()}
function loop(t){const dt=Math.min(45,t-last||16);last=t;if(damageFlash>0)damageFlash=Math.max(0,damageFlash-dt/500);update(dt);render();requestAnimationFrame(loop)}
