function d1(){const l=input.has("ArrowLeft")||input.has("KeyA"),r=input.has("ArrowRight")||input.has("KeyD"),u=input.has("ArrowUp")||input.has("KeyW"),d=input.has("ArrowDown")||input.has("KeyS");const x=(r?1:0)-(l?1:0),y=(d?1:0)-(u?1:0);return x||y?{x,y}:null}
function d2(){const l=input.has("KeyJ"),r=input.has("KeyL"),u=input.has("KeyI"),d=input.has("KeyK");const x=(r?1:0)-(l?1:0),y=(d?1:0)-(u?1:0);return x||y?{x,y}:null}
function setDir(p,code){const m=p===p2?{KeyJ:{x:-1,y:0},KeyL:{x:1,y:0},KeyI:{x:0,y:-1},KeyK:{x:0,y:1}}:{ArrowLeft:{x:-1,y:0},KeyA:{x:-1,y:0},ArrowRight:{x:1,y:0},KeyD:{x:1,y:0},ArrowUp:{x:0,y:-1},KeyW:{x:0,y:-1},ArrowDown:{x:0,y:1},KeyS:{x:0,y:1}};if(m[code])p.dir=m[code]}
function tryDoor(p,x,y){const d=W.doorAt(host,x,y);if(!d?.locked)return true;if(p.bronzeKeys<=0){S.sfx("locked");showToast("LOCKED TREASURE DOOR","You need a bronze key. The main quest never requires this room.","red");return false}p.bronzeKeys--;d.locked=false;host.revision++;stats.doors++;S.sfx("door");shake=5;showToast("TREASURE DOOR OPENED","Bronze key used. This chamber is optional, so you can never be trapped by it.","gold");updateQuests();broadcastWorld();return true}
function openChest(p,chest){if(!chest?.active)return true;if(chest.locked&&p.bronzeKeys<=0){S.sfx("locked");showToast("LOCKED CHEST","A bronze key opens this chest. Leave it and return later — it never blocks the main quest.","red");return false}if(chest.locked)p.bronzeKeys--;chest.active=false;host.revision++;S.sfx("door");shake=4;const reward=chest.reward||"ammo";const names={weapon:"WEAPON UPGRADE",armour:"ARMOUR PLATE",potion:"RESTORATION POTION",torch:"FLAMING TORCH",ammo:"AMMO PACK",rapid:"RAPID FIRE",health:"HEALTH PACK"};showToast("CHEST OPENED",`Inside: ${names[reward]||reward.toUpperCase()}.`,"gold");setTimeout(()=>{if(mode==="playing")applyItem({kind:reward,title:"Chest Reward"},p)},420);broadcastWorld();return true}
function tryChest(p,x,y){const c=W.chestAt(host,x,y);return c?openChest(p,c):true}
function diagonalClear(dx,dy,p){if(!dx||!dy)return true;return W.walkable(world.map,p.x+dx,p.y,host)&&W.walkable(world.map,p.x,p.y+dy,host)}
function movePlayer(p,dx,dy,dash=false){if(mode!=="playing"||!p)return;p.dir={x:dx,y:dy};const ox=p.x,oy=p.y;for(let n=0;n<(dash?2:1);n++){if(dx&&dy&&!diagonalClear(dx,dy,p)){if(n===0)S.sfx("wall");break}const warp=(!dy)?W.tunnelDestination(world,p.x,p.y,dx,dy):null;if(warp){p.x=warp.x;p.y=warp.y;p.rx=warp.x;p.ry=warp.y;S.sfx("warp");burst(p.x,p.y,P.cyan,18,1.2);continue}const nx=p.x+dx,ny=p.y+dy;if(!tryDoor(p,nx,ny)||!tryChest(p,nx,ny))break;if(!W.walkable(world.map,nx,ny,host)){if(n===0)S.sfx("wall");break}p.x=nx;p.y=ny;for(const i of host.items)if(i.active&&i.x===nx&&i.y===ny)requestCollect(i,p);for(const e of host.enemies)if(e.alive&&e.x===nx&&e.y===ny)hurtPlayer(p,e.follower?2:1,false,e.follower?.name||e.kind);if(host.exitOpen&&nx===world.exit.x&&ny===world.exit.y){if(playMode==="online")net.send("complete",{by:p.name});finish(p.name);return}updateRoomMessage(p,false);reveal(p)}if(dash){S.sfx("dash");trailBetween(ox,oy,p.x,p.y,p===p2?P.green:P.cyan)}}
function dashPlayer(p,d){if(!p||!d||mode!=="playing")return;movePlayer(p,d.x,d.y,true);sync()}
function spreadDirections(d){const dirs=[{x:1,y:0},{x:1,y:1},{x:0,y:1},{x:-1,y:1},{x:-1,y:0},{x:-1,y:-1},{x:0,y:-1},{x:1,y:-1}],i=dirs.findIndex(q=>q.x===d.x&&q.y===d.y);if(i<0)return[d];return[d,dirs[(i+7)%8],dirs[(i+1)%8]]}
function firePlayer(p,d){if(!p||mode!=="playing")return;const cd=p===p2?fire2:fire1;if(cd>0)return;const active=bullets.filter(b=>b.owner===p.id&&b.ttl>0).length,max=C.player.maxProjectiles+(p.weaponLevel-1);if(active>=max){S.sfx("empty");return}if(p.mana<=0){S.sfx("empty");showToast("OUT OF AMMO","Find an ammo pack or a supply chest. You are not expected to fight the dungeon with stern looks.","red");return}d=d||p.dir||{x:1,y:0};p.dir=d;p.mana--;const delay=p.rapidMs>0?88:C.player.fireDelay;if(p===p2)fire2=delay;else fire1=delay;const dirs=p.weaponLevel>=3?spreadDirections(d):[d];for(const z of dirs.slice(0,Math.max(1,max-active))){const b={id:`${p.id}-${Date.now()}-${Math.random()}`,owner:p.id,ownerName:p.name,x:p.x,y:p.y,dx:z.x,dy:z.y,ttl:18,power:p.weaponLevel>=2?2:1};spawnBullet(b,false);if(playMode==="online"&&p===p1)net.send("shot",b)}S.sfx("fire");muzzle(p.x,p.y,d);sync()}
function spawnBullet(b,remoteShot){if(b)bullets.push({...b,remote:!!remoteShot})}
function spawnEnemyShot(b){if(!b)return;enemyBullets.push({...b,ttl:Number(b.ttl||14)});if(localPlayers().some(p=>md(b,p)<9))S.sfx(b.style==="food"?"food":b.style==="fire"?"flame":"enemy")}
function stepProjectiles(){for(const b of bullets){if(b.ttl<=0)continue;const nx=b.x+b.dx,ny=b.y+b.dy;if(!W.walkable(world.map,nx,ny,host)){b.ttl=0;continue}b.x=nx;b.y=ny;b.ttl--;const e=host.enemies.find(e=>e.alive&&e.x===Math.round(nx)&&e.y===Math.round(ny));if(e){b.ttl=0;if(b.owner===p1.id||b.owner===p2?.id){if(net.isHost)damageEnemy(e,b.power);else if(playMode==="online")net.send("hit",{enemyId:e.id,power:b.power,source:{x:b.x,y:b.y}})}continue}for(const lp of localPlayers())if(lp.id!==b.owner&&Math.round(nx)===lp.x&&Math.round(ny)===lp.y){b.ttl=0;hurtPlayer(lp,1,true,b.ownerName||"your co-op partner");break}}for(const b of enemyBullets){if(b.ttl<=0)continue;const nx=b.x+b.dx,ny=b.y+b.dy;if(!W.walkable(world.map,nx,ny,host)){b.ttl=0;continue}b.x=nx;b.y=ny;b.ttl--;if(b.style==="fire")burst(nx,ny,Math.random()<.5?P.orange:P.gold,3,.6);for(const lp of localPlayers())if(Math.round(nx)===lp.x&&Math.round(ny)===lp.y){b.ttl=0;hurtPlayer(lp,Number(b.power||1),false,b.source||"enemy");break}}for(let i=bullets.length-1;i>=0;i--)if(bullets[i].ttl<=0)bullets.splice(i,1);for(let i=enemyBullets.length-1;i>=0;i--)if(enemyBullets[i].ttl<=0)enemyBullets.splice(i,1)}
function hurtPlayer(p,n,friendly=false,source="enemy"){if(!p||p.invuln>0||mode!=="playing")return;let left=n;if(p.armor>0){const a=Math.min(p.armor,left);p.armor-=a;left-=a;if(a){S.sfx("armour");floatText(p.x,p.y,"ARMOUR",P.cyan)}}if(left<=0){p.invuln=350;sync();return}p.health-=left;p.invuln=850;shake=10;damageFlash=.5;S.sfx(friendly?"hurt":"hurt");burst(p.x,p.y,P.red,16,1.4);ring(p.x,p.y,P.red,30);if(friendly){showToast("FRIENDLY FIRE",`${source} just shot a team-mate. Very cooperative.`,"red");say("<strong>FRIENDLY FIRE.</strong> The enemy has requested that you continue doing its work.")}if(p.health<=0){p.health=p.maxHealth;p.mana=p.maxMana;p.x=world.start.x;p.y=world.start.y;p.rx=p.x;p.ry=p.y;score=Math.max(0,score-500);S.sfx("respawn");showToast(`${p.name} RESPAWNS`,"Minus 500 points. Consider it a very visible trainer option.","cyan")}sync()}
function updateCamping(p,dt){let c=campStates.get(p.id);if(!c){resetCamp(p);c=campStates.get(p.id)}const room=W.roomAt(world,p.x,p.y),moved=Math.hypot(p.x-c.anchorX,p.y-c.anchorY);if(room!==c.room||moved>=C.camping.resetDistance){resetCamp(p);return}c.elapsed+=dt;if(c.elapsed<C.camping.graceMs)return;if(!c.active){c.active=true;c.nextBlast=150;c.blastCount=0;S.sfx("campwarn");showToast("THE VAULT HAS NOTICED YOU HIDING","The first blasts are warnings. Stay here and the dungeon will start targeting your exact position.","red")}c.nextBlast-=dt;if(c.nextBlast<=0){c.blastCount=(c.blastCount||0)+1;let q;if(c.blastCount%C.camping.directBlastEvery===0){q={x:p.x,y:p.y,direct:true}}else{const a=[];for(let dy=-C.camping.zoneRadius;dy<=C.camping.zoneRadius;dy++)for(let dx=-C.camping.zoneRadius;dx<=C.camping.zoneRadius;dx++){const x=p.x+dx,y=p.y+dy;if(W.walkable(world.map,x,y,host)&&Math.hypot(dx,dy)<=C.camping.zoneRadius+.2)a.push({x,y})}q=a[Math.floor(Math.random()*a.length)]||{x:p.x,y:p.y}}hazards.push({x:q.x,y:q.y,life:C.camping.warningMs,maxLife:C.camping.warningMs,direct:!!q.direct});c.nextBlast=C.camping.blastIntervalMs}}
function updateHazards(dt){for(let i=hazards.length-1;i>=0;i--){const h=hazards[i];h.life-=dt;if(h.life>0)continue;hazards.splice(i,1);S.sfx("explosion");shake=Math.max(shake,h.direct?13:9);burst(h.x,h.y,P.orange,h.direct?32:24,h.direct?2.1:1.8);ring(h.x,h.y,P.red,h.direct?54:42);for(const p of localPlayers())if(Math.hypot(p.x-h.x,p.y-h.y)<=C.camping.blastRadius)hurtPlayer(p,C.camping.damage,false,"anti-camping blast")}}
function updateRoomMessage(p,force){const r=W.roomAt(world,p.x,p.y);if(!force&&r===p.lastRoom)return;p.lastRoom=r;const th=W.themeAt(world,p.x,p.y);UI.surroundings.innerHTML=`<strong>${th.name}</strong> — ${th.message}`;if(!force){S.sfx("room");showToast(th.name,th.message,"cyan")}}
function surroundingsTick(){if(!p1)return;const p=p1,r=W.roomAt(world,p.x,p.y),hidden=host.enemies.filter(e=>e.alive&&W.roomAt(world,e.x,e.y)===r&&!visibleTo(p,e.x,e.y)).length;if(hidden>0)say(`<strong>YOU HEAR MOVEMENT.</strong> Something else is in the ${W.themeAt(world,p.x,p.y).name}.`);else if(p.torchMs>0)say("<strong>TORCHLIGHT.</strong> You can see farther, but anything with sight can spot that glow from farther away.");else if(host.doors.some(d=>d.locked&&md(d,p)<7))say("<strong>METAL CLUNK.</strong> There is a locked bronze treasure door nearby.");else say(`<strong>${W.themeAt(world,p.x,p.y).name.toUpperCase()}.</strong> ${W.themeAt(world,p.x,p.y).message}`)}
function visibleTo(p,x,y){const r=p.torchMs>0?C.player.torchRadius:C.player.sightRadius;return Math.hypot(x-p.x,y-p.y)<=r+.2&&A.lineOfSight(world.map,p,{x,y},r,host)}
function burst(tx,ty,col,n=10,power=1){for(let i=0;i<n;i++)particles.push({x:tx*C.tile+C.tile/2,y:ty*C.tile+C.tile/2,vx:(Math.random()-.5)*3.2*power,vy:(Math.random()-.5)*3.2*power,life:300+Math.random()*360,col,size:1.5+Math.random()*3*power,drag:.97})}
function ring(tx,ty,col,max=30){rings.push({x:tx*C.tile+C.tile/2,y:ty*C.tile+C.tile/2,r:3,max,life:340,col})}
function floatText(tx,ty,text,col=P.white){floaters.push({x:tx*C.tile+C.tile/2,y:ty*C.tile-3,text,life:720,col})}
function muzzle(tx,ty,d){for(let i=0;i<5;i++)particles.push({x:tx*C.tile+C.tile/2+d.x*12,y:ty*C.tile+C.tile/2+d.y*12,vx:d.x*(2+Math.random()*2)+(Math.random()-.5),vy:d.y*(2+Math.random()*2)+(Math.random()-.5),life:160,col:P.gold,size:2+Math.random()*2,drag:.94})}
function trailBetween(x1,y1,x2,y2,col){for(let i=0;i<8;i++){const t=i/7;particles.push({x:(x1+(x2-x1)*t)*C.tile+C.tile/2,y:(y1+(y2-y1)*t)*C.tile+C.tile/2,vx:0,vy:0,life:220+i*12,col,size:3,drag:.97})}}
function updateEffects(dt){for(const q of particles){q.x+=q.vx;q.y+=q.vy;q.vx*=q.drag;q.vy*=q.drag;q.life-=dt}for(let i=particles.length-1;i>=0;i--)if(particles[i].life<=0)particles.splice(i,1);for(const r of rings){r.life-=dt;r.r+=(r.max-r.r)*.12}for(let i=rings.length-1;i>=0;i--)if(rings[i].life<=0)rings.splice(i,1);for(const f of floaters){f.life-=dt;f.y-=dt*.018}for(let i=floaters.length-1;i>=0;i--)if(floaters[i].life<=0)floaters.splice(i,1)}
function finish(by){if(won)return;won=true;mode="ended";S.stopMusic();S.sfx("win");UI.endTitle.textContent="THE VAULT IS OPEN";UI.endText.innerHTML=`${esc(by)} reached the exit.<br><br><strong>TEAM MISSION COMPLETE.</strong><br>Score: ${pad(score)}<br>Bonus doors opened: ${stats.doors}<br>C64 games rescued: ${stats.games}<br><br>The Score Goblin has lodged an appeal.`;UI.end.classList.remove("hidden")}
function update(dt){if(mode!=="playing")return;enemyCD-=dt;projectileCD-=dt;sendCD-=dt;worldCD-=dt;surroundCD-=dt;move1-=dt;move2-=dt;fire1-=dt;fire2-=dt;lowHealthCD-=dt;if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)UI.toast.classList.remove("show")}for(const p of localPlayers()){if(p.invuln>0)p.invuln-=dt;if(p.torchMs>0)p.torchMs=Math.max(0,p.torchMs-dt);if(p.rapidMs>0)p.rapidMs=Math.max(0,p.rapidMs-dt);p.rx+=(p.x-p.rx)*.32;p.ry+=(p.y-p.ry)*.32;updateCamping(p,dt);reveal(p)}for(const p of remote.values()){p.rx+=(p.x-p.rx)*.28;p.ry+=(p.y-p.ry)*.28}if(input.has("Space")&&fire1<=0)firePlayer(p1,d1());if(p2&&input.has("Enter")&&fire2<=0)firePlayer(p2,d2());if(move1<=0){const d=d1();if(d){movePlayer(p1,d.x,d.y);move1=C.player.moveDelay}}if(p2&&move2<=0){const d=d2();if(d){movePlayer(p2,d.x,d.y);move2=C.player.moveDelay}}if(projectileCD<=0){stepProjectiles();projectileCD=75}if(enemyCD<=0){hostEnemyStep(C.enemy.thinkDelay);enemyCD=C.enemy.thinkDelay}if(sendCD<=0){sendPlayer();sendCD=100}if(worldCD<=0&&net.isHost){broadcastWorld();worldCD=300}updateHazards(dt);updateEffects(dt);if(surroundCD<=0){surroundingsTick();surroundCD=9000}const seen=host.enemies.filter(e=>e.alive&&e.aiState==="chase"&&localPlayers().some(p=>md(e,p)<14)).length;S.setDanger(Math.min(1,seen/3));if(localPlayers().some(p=>p.health<=2)&&lowHealthCD<=0){S.sfx("lowhealth");lowHealthCD=2600}for(const p of localPlayers()){const e=host.enemies.find(e=>e.alive&&e.x===p.x&&e.y===p.y);if(e)hurtPlayer(p,e.follower?2:1,false,e.follower?.name||e.kind)}sync()}
