"use strict";
const C=window.CCG_CONFIG,W=window.CCGWorld,A=window.CCGAI,S=window.CCGSound,$=id=>document.getElementById(id);
const canvas=$("game"),ctx=canvas.getContext("2d");ctx.imageSmoothingEnabled=false;
const UI={health:$("hud-health"),p2:$("hud-p2"),mana:$("hud-mana"),keys:$("hud-keys"),bronze:$("hud-bronze"),weapon:$("hud-weapon"),score:$("hud-score"),room:$("hud-room"),mission:$("mission-text"),net:$("net-status"),sound:$("sound-btn"),message:$("message"),list:$("player-list"),quests:$("quest-list"),loadout:$("loadout"),surroundings:$("surroundings"),menu:$("menu"),pause:$("pause"),end:$("end"),endTitle:$("end-title"),endText:$("end-text"),name:$("player-name"),roomCode:$("room-code"),note:$("menu-note"),toast:$("pickup-toast"),toastTitle:$("pickup-title"),toastText:$("pickup-text")};
const logo=new Image();logo.onerror=()=>{if(!logo.src.endsWith(C.logoFallback))logo.src=C.logoFallback};logo.src=C.logoAsset;
const avatarImages=new Map();for(const f of C.followerElites)if(f.avatar){const im=new Image();im.src=f.avatar.startsWith("embedded:")?(window.CCG_AVATAR_DATA?.[f.avatar.slice(9)]||""):f.avatar;avatarImages.set(f.name,im)}
const P={purple:"#b978ff",gold:"#ffd85a",cyan:"#6cecff",green:"#72ff9b",pink:"#ff5bae",red:"#ff6868",orange:"#ff9950",white:"#faf4ff",blue:"#6aa9ff",brown:"#9b6134",black:"#030205"};
const input=new Set(),remote=new Map(),bullets=[],enemyBullets=[],particles=[],rings=[],floaters=[],hazards=[],pendingItems=new Set(),enemyVisuals=new Map(),cameras=new Map(),explored=new Map(),campStates=new Map();
let mode="menu",playMode="solo",world=null,host=null,p1=null,p2=null,score=0,last=0,enemyCD=0,projectileCD=0,sendCD=0,worldCD=0,surroundCD=0,move1=0,move2=0,fire1=0,fire2=0,won=false,shake=0,damageFlash=0,renderShake={x:0,y:0},toastTimer=0,lowHealthCD=0;
let view={x:0,y:0,w:canvas.width,h:canvas.height},focus=null,cam={x:0,y:0};
const stats={games:0,elites:0,doors:0,weapons:0},questDone=new Set();
let net=null;
const esc=v=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const pad=n=>String(Math.max(0,Math.floor(n))).padStart(6,"0"),md=(a,b)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
const localPlayers=()=>[p1,p2].filter(Boolean), findLocal=id=>localPlayers().find(p=>p.id===id)||null;
const allPlayers=()=>{const a=[...localPlayers()],now=performance.now();for(const p of remote.values())if(now-p.lastSeen<2600)a.push(p);return a};
function say(s){UI.message.innerHTML=s}
function showToast(title,text,tone="gold"){UI.toast.className=`pickup-toast ${tone}`;UI.toastTitle.textContent=title;UI.toastText.textContent=text;requestAnimationFrame(()=>UI.toast.classList.add("show"));toastTimer=2300}
function playerName(){return String(UI.name.value||"CCG Player").trim().slice(0,18)||"CCG Player"}
function makePlayer(id,name,x,y){return{id,name,x,y,rx:x,ry:y,health:C.player.maxHealth,maxHealth:C.player.maxHealth,mana:C.player.maxMana,maxMana:C.player.maxMana,armor:0,bronzeKeys:0,potions:0,weaponLevel:1,dir:{x:1,y:0},invuln:0,torchMs:0,rapidMs:0,lastRoom:-99}}
function nearbyOpen(x,y,avoid=[]){for(let r=1;r<7;r++)for(let dy=-r;dy<=r;dy++)for(let dx=-r;dx<=r;dx++){const nx=x+dx,ny=y+dy;if(W.walkable(world.map,nx,ny,host)&&!avoid.some(p=>p.x===nx&&p.y===ny))return{x:nx,y:ny}}return{x,y}}
function resetCamp(p){campStates.set(p.id,{anchorX:p.x,anchorY:p.y,room:W.roomAt(world,p.x,p.y),elapsed:0,active:false,nextBlast:0})}
function reveal(p){let ex=explored.get(p.id);if(!ex){ex=new Set();explored.set(p.id,ex)}const r=p.torchMs>0?C.player.torchRadius:C.player.sightRadius;for(let y=Math.max(0,p.y-r);y<=Math.min(C.worldHeight-1,p.y+r);y++)for(let x=Math.max(0,p.x-r);x<=Math.min(C.worldWidth-1,p.x+r);x++)if(Math.hypot(x-p.x,y-p.y)<=r+.2&&A.lineOfSight(world.map,p,{x,y},r,host))ex.add(`${x},${y}`)}
function startWorld(seed,split=false){world=W.generate(seed);window.__CCG_WORLD=world;host=W.createHostState(world);p1=makePlayer(net.sessionId,playerName(),world.start.x,world.start.y);p2=null;if(split){const q=nearbyOpen(world.start.x+2,world.start.y,[p1]);p2=makePlayer("LOCAL-P2","PLAYER 2",q.x,q.y)}score=0;won=false;remote.clear();enemyVisuals.clear();bullets.length=enemyBullets.length=particles.length=rings.length=floaters.length=hazards.length=0;pendingItems.clear();cameras.clear();explored.clear();campStates.clear();questDone.clear();stats.games=stats.elites=stats.doors=stats.weapons=0;shake=damageFlash=0;move1=move2=fire1=fire2=0;for(const p of localPlayers()){resetCamp(p);reveal(p);updateRoomMessage(p,true)}sync()}
async function startSolo(){await S.start();S.startMusic();net.setSolo(playerName());playMode="solo";startWorld("SOLO-ADVENTURE",false);mode="playing";UI.menu.classList.add("hidden");S.sfx("join");say("<strong>SOLO MODE.</strong> Three main keys, optional treasure vaults and rather too many eyes in the dark.")}
async function startSplit(){await S.start();S.startMusic();net.setSolo(`${playerName()} + P2`);playMode="split";startWorld("LOCAL-SPLIT-ADVENTURE",true);mode="playing";UI.menu.classList.add("hidden");S.sfx("join");showToast("2 PLAYER SPLIT SCREEN","Friendly fire is ON. Try to remain friends.","cyan");say("<strong>LOCAL CO-OP.</strong> Two players, one dungeon, and absolutely no guarantee you won't shoot each other.")}
async function createRoom(){await S.start();S.startMusic();const c=net.createCode();UI.note.textContent="Creating room…";try{playMode="online";startWorld(c,false);const r=await net.join(c,playerName());mode="playing";UI.roomCode.value=c;UI.menu.classList.add("hidden");S.sfx("join");say(`<strong>ROOM ${c}</strong> created using ${r.transport==="supabase"?"internet":"local"} co-op. Friendly fire is enabled.`);if(net.isHost)broadcastWorld();sync()}catch(e){mode="menu";UI.note.textContent=e.message}}
async function joinRoom(){await S.start();S.startMusic();const c=window.CCGNetwork.cleanCode(UI.roomCode.value);if(c.length<4){UI.note.textContent="Enter the room code from the host.";return}try{playMode="online";startWorld(c,false);const r=await net.join(c,playerName());mode="playing";UI.menu.classList.add("hidden");S.sfx("join");say(`<strong>JOINED ${c}</strong> using ${r.transport==="supabase"?"internet":"local"} co-op. Watch your fire.`);sync()}catch(e){mode="menu";UI.note.textContent=e.message}}
function sync(){if(!p1||!host)return;UI.health.textContent=`${p1.health}/${p1.maxHealth}`;UI.p2.textContent=p2?`${p2.health}/${p2.maxHealth}`:`ARM ${p1.armor}`;UI.mana.textContent=`${p1.mana}/${p1.maxMana}`;UI.keys.textContent=`${host.keysCollected}/${C.keyTarget}`;UI.bronze.textContent=p1.bronzeKeys+(p2?` + ${p2.bronzeKeys}`:"");UI.weapon.textContent=`LV${p1.weaponLevel}${p2?` / ${p2.weaponLevel}`:""}`;UI.score.textContent=pad(score);UI.room.textContent=playMode==="online"?net.roomCode:playMode==="split"?"SPLIT":"SOLO";UI.net.textContent=playMode==="online"?(net.transport==="supabase"?(net.isHost?"ONLINE • HOST":"ONLINE • CO-OP"):(net.isHost?"LOCAL ROOM • HOST":"LOCAL ROOM • CO-OP")):playMode==="split"?"LOCAL SPLIT":"SOLO";UI.net.classList.toggle("online",playMode==="online"&&net.connected);UI.mission.textContent=host.exitOpen?"Main vault open — reach the pulsing purple exit.":`Find the three main vault keys (${host.keysCollected}/${C.keyTarget}). Bronze keys only open optional treasure rooms.`;UI.sound.textContent=S.isEnabled()?"SOUND ON":"SOUND OFF";UI.loadout.innerHTML=`P1: Weapon LV${p1.weaponLevel} • Armour ${p1.armor} • Potions ${p1.potions} • Ammo ${p1.mana}/${p1.maxMana} • ${p1.torchMs>0?"TORCH ACTIVE":"No torch"}${p2?`<br>P2: Weapon LV${p2.weaponLevel} • Armour ${p2.armor} • Potions ${p2.potions} • Ammo ${p2.mana}/${p2.maxMana} • ${p2.torchMs>0?"TORCH ACTIVE":"No torch"}`:""}`;const rows=net.getMembers();UI.list.innerHTML=playMode==="split"?"P1 + PLAYER 2":(rows.length?rows.map((m,i)=>`${esc(m.name)}${i===0?" ★":""}`).join("<br>"):"");updateQuests()}
function updateQuests(){const q=[{id:"games",label:"Rescue 3 C64 games",v:stats.games,t:3},{id:"elites",label:"Free 2 named followers",v:stats.elites,t:2},{id:"doors",label:"Open 1 bronze treasure door",v:stats.doors,t:1},{id:"weapons",label:"Find a weapon upgrade",v:stats.weapons,t:1}];for(const x of q)if(x.v>=x.t&&!questDone.has(x.id)){questDone.add(x.id);score+=350;showToast("SIDE QUEST COMPLETE",`${x.label} — 350 bonus points.`,"green");S.sfx("key")}UI.quests.innerHTML=q.map(x=>`<div class="${x.v>=x.t?"quest-done":""}">${x.v>=x.t?"✓ ":""}${x.label} <b>${Math.min(x.v,x.t)}/${x.t}</b></div>`).join("")}
