window.CCGNetwork=(()=>{"use strict";
const C=window.CCG_CONFIG;const alphabet="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
function id(n=10){const b=new Uint8Array(n);crypto.getRandomValues(b);return Array.from(b,x=>alphabet[x%alphabet.length]).join("")}
function code(v){return String(v||"").toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6)}
class RoomNetwork{
 constructor(cb={}){this.cb=cb;this.sessionId=id(12);this.name="CCG Player";this.roomCode="";this.mode="solo";this.transport="solo";this.isHost=true;this.connected=false;this.members=new Map();this.joinedAt=Date.now();this.bc=null;this.client=null;this.channel=null;this.heartbeat=null}
 createCode(){return id(5)}
 setSolo(name){this.leave();this.mode="solo";this.transport="solo";this.name=name||"CCG Player";this.isHost=true;this.connected=false;this.members.set(this.sessionId,{id:this.sessionId,name:this.name,joinedAt:this.joinedAt,lastSeen:Date.now()});this.syncMembers()}
 async getSupabase(){if(window.ccgSupabase?.getClient)return window.ccgSupabase.getClient();if(/cheekycommodoregamer\.co\.uk$/i.test(location.hostname)){await this.load("/js/ccg-supabase-config.js");await this.load("/js/ccg-supabase-client.js");if(window.ccgSupabase?.getClient)return window.ccgSupabase.getClient()}return null}
 load(src){return new Promise((res,rej)=>{const ex=document.querySelector(`script[src="${src}"]`);if(ex){if(window.ccgSupabase)res();else ex.addEventListener("load",res,{once:true});return}const s=document.createElement("script");s.src=src;s.onload=res;s.onerror=rej;document.head.appendChild(s)})}
 async join(room,name){await this.leave();this.roomCode=code(room);if(this.roomCode.length<4)throw new Error("Room code must be at least four characters.");this.name=String(name||"CCG Player").trim().slice(0,18)||"CCG Player";this.joinedAt=Date.now();this.mode="coop";const supabase=await this.getSupabase().catch(()=>null);if(supabase){await this.joinSupabase(supabase)}else this.joinLocal();return{code:this.roomCode,transport:this.transport}}
 joinLocal(){this.transport="local";this.connected=true;this.bc=new BroadcastChannel(`ccg-quest:${this.roomCode}`);this.bc.onmessage=e=>this.receiveLocal(e.data);this.touchMember({id:this.sessionId,name:this.name,joinedAt:this.joinedAt});this.postLocal({type:"hello",member:{id:this.sessionId,name:this.name,joinedAt:this.joinedAt}});this.heartbeat=setInterval(()=>{this.postLocal({type:"heartbeat",member:{id:this.sessionId,name:this.name,joinedAt:this.joinedAt}});this.prune()},1000);this.syncMembers()}
 receiveLocal(m){if(!m||m.sender===this.sessionId)return;if(m.type==="hello"||m.type==="heartbeat"){this.touchMember(m.member);if(m.type==="hello")this.postLocal({type:"heartbeat",member:{id:this.sessionId,name:this.name,joinedAt:this.joinedAt}});this.syncMembers();return}if(m.type==="bye"){this.members.delete(m.memberId);this.syncMembers();return}if(m.type==="packet")this.cb.onPacket?.(m.event,m.payload)}
 postLocal(obj){this.bc?.postMessage({...obj,sender:this.sessionId})}
 touchMember(m){if(m?.id)this.members.set(m.id,{...m,lastSeen:Date.now()})}
 prune(){const now=Date.now();for(const [k,m] of this.members)if(k!==this.sessionId&&now-m.lastSeen>3500)this.members.delete(k);this.syncMembers()}
 async joinSupabase(client){this.transport="supabase";this.client=client;this.channel=client.channel(`ccg-quest:${this.roomCode}`,{config:{presence:{key:this.sessionId},broadcast:{self:false}}});this.channel.on("presence",{event:"sync"},()=>this.syncSupabasePresence()).on("broadcast",{event:"ccg_packet"},({payload})=>this.cb.onPacket?.(payload?.event,payload?.payload));await new Promise((res,rej)=>{let done=false;const t=setTimeout(()=>{if(!done)rej(new Error("Timed out connecting to CCG Realtime."))},8000);this.channel.subscribe(async status=>{if(status==="SUBSCRIBED"&&!done){done=true;clearTimeout(t);this.connected=true;await this.channel.track({id:this.sessionId,name:this.name,joinedAt:this.joinedAt});res()}else if(status==="CHANNEL_ERROR"&&!done){done=true;clearTimeout(t);rej(new Error("Could not join the CCG Realtime room."))}})});this.syncSupabasePresence()}
 syncSupabasePresence(){if(!this.channel)return;this.members.clear();const raw=this.channel.presenceState();for(const arr of Object.values(raw))for(const p of arr)this.touchMember(p);this.touchMember({id:this.sessionId,name:this.name,joinedAt:this.joinedAt});this.syncMembers()}
 syncMembers(){const a=[...this.members.values()].sort((x,y)=>(x.joinedAt-y.joinedAt)||x.id.localeCompare(y.id)).slice(0,C.maxPlayers),was=this.isHost;this.isHost=(a[0]?.id||this.sessionId)===this.sessionId;this.cb.onMembers?.(a,this.isHost,was!==this.isHost)}
 send(event,payload){if(this.mode!=="coop"||!this.connected)return;if(this.transport==="local")this.postLocal({type:"packet",event,payload});else return this.channel?.send({type:"broadcast",event:"ccg_packet",payload:{event,payload}})}
 async leave(){if(this.heartbeat){clearInterval(this.heartbeat);this.heartbeat=null}if(this.bc){this.postLocal({type:"bye",memberId:this.sessionId});this.bc.close();this.bc=null}if(this.channel){try{await this.channel.untrack()}catch(_){}try{await this.client?.removeChannel(this.channel)}catch(_){}this.channel=null}this.members.clear();this.connected=false;this.isHost=true}
 getMembers(){return[...this.members.values()].sort((a,b)=>a.joinedAt-b.joinedAt)}
}
return{RoomNetwork,cleanCode:code};})();
