(function(){
  "use strict";
  const Q=window.CCGQuest;
  class AudioEngine{
    constructor(){this.ctx=null;this.master=null;this.timer=null;this.step=0;this.theme=0;this.boss=false;this.muted=false;this.next=0;this.noise=null;this.scene='title';this.external=null;this.externalSrc=null;this.externalFailed=new Set();this.externalVolume=.48;}
    async start(){if(!this.ctx){this.ctx=new (window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.master.gain.value=.17;this.master.connect(this.ctx.destination);this.makeNoise();}if(this.ctx.state==='suspended')await this.ctx.resume();if(!this.timer){this.next=this.ctx.currentTime+.05;this.timer=setInterval(()=>this.schedule(),55);}this.syncExternal();}
    makeNoise(){const len=this.ctx.sampleRate,b=this.ctx.createBuffer(1,len,this.ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<len;i++)d[i]=Math.random()*2-1;this.noise=b;}
    tone(freq,dur=.1,type='square',gain=.08,when){if(!this.ctx||this.muted||this.external)return;const t=when??this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(gain,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+dur+.02);}
    noiseHit(dur=.05,gain=.045,when){if(!this.ctx||this.muted||this.external)return;const t=when??this.ctx.currentTime,s=this.ctx.createBufferSource(),g=this.ctx.createGain(),f=this.ctx.createBiquadFilter();s.buffer=this.noise;f.type='highpass';f.frequency.value=1100;g.gain.setValueAtTime(gain,t);g.gain.exponentialRampToValueAtTime(.0001,t+dur);s.connect(f);f.connect(g);g.connect(this.master);s.start(t);s.stop(t+dur);}
    musicPath(scene,boss){const key=boss?scene+'Boss':scene;return Q.customAsset?.('music',key)||Q.customAsset?.('music',scene)||null;}
    stopExternal(){if(this.external){try{this.external.pause();this.external.currentTime=0;}catch(e){}this.external=null;this.externalSrc=null;}if(this.ctx)this.next=this.ctx.currentTime+.05;}
    syncExternal(){const src=this.musicPath(this.scene,this.boss);if(!src||this.externalFailed.has(src)){this.stopExternal();return;}if(this.external&&this.externalSrc===src){this.external.muted=this.muted;return;}this.stopExternal();const a=new Audio(src);a.loop=true;a.preload='auto';a.volume=this.externalVolume;a.muted=this.muted;a.addEventListener('error',()=>{if(this.external===a){console.warn('[CCG QUEST] MP3 unavailable, falling back to procedural music:',src);this.externalFailed.add(src);this.stopExternal();}},{once:true});this.external=a;this.externalSrc=src;const play=a.play();if(play&&typeof play.catch==='function')play.catch(()=>{});}
    setTheme(i,boss=false,scene=null){this.theme=i|0;this.boss=!!boss;this.scene=scene||this.scene||'title';this.step=0;if(this.ctx)this.next=this.ctx.currentTime+.05;this.syncExternal();}
    schedule(){if(!this.ctx||this.muted||this.external)return;const look=.18,baseTempo=this.boss?138:112+[0,4,0,8,12][this.theme],beat=60/baseTempo/2;const scales=[[0,3,7,10,7,3,12,10],[0,4,7,9,7,4,11,9],[0,5,7,12,7,5,10,7],[0,4,7,12,14,12,7,4],[0,1,6,7,12,7,6,1]],roots=[110,123.47,98,130.81,92.5];while(this.next<this.ctx.currentTime+look){const s=this.step++,pat=scales[this.theme],semi=pat[s%pat.length],root=roots[this.theme],f=root*Math.pow(2,semi/12);if(s%2===0)this.tone(f*2,.105,'square',.048,this.next);if(s%4===0)this.tone(root/2,.19,'triangle',.065,this.next);if(s%4===2)this.tone(root*.75,.11,'sawtooth',.028,this.next);if(s%2===1)this.noiseHit(.035,.025,this.next);if(s%8===0){this.tone(54,.12,'sine',.08,this.next);this.noiseHit(.07,.04,this.next);}this.next+=beat;}}
    sfx(name){if(!this.ctx||this.muted)return;const ext=this.external;this.external=null;const n=this.ctx.currentTime;if(name==='jump'){this.tone(330,.06,'square',.065,n);this.tone(440,.08,'square',.05,n+.045);}else if(name==='pickup'){this.tone(660,.05,'square',.055,n);this.tone(990,.08,'triangle',.05,n+.04);}else if(name==='hit'){this.noiseHit(.12,.09,n);this.tone(105,.16,'sawtooth',.08,n);}else if(name==='shot'){this.tone(510,.05,'square',.05,n);}else if(name==='bosswarn'){this.tone(180,.12,'sawtooth',.07,n);this.tone(180,.12,'sawtooth',.07,n+.17);}else if(name==='shield'){this.tone(780,.07,'triangle',.05,n);this.tone(1040,.1,'triangle',.05,n+.06);}else if(name==='shieldlow'){this.tone(250,.06,'square',.045,n);}else if(name==='unlock'){[523,659,784,1046].forEach((f,i)=>this.tone(f,.12,'square',.05,n+i*.07));}else if(name==='punch'){this.noiseHit(.05,.055,n);this.tone(145,.055,'square',.055,n);}else if(name==='kick'){this.noiseHit(.075,.07,n);this.tone(118,.075,'sawtooth',.068,n);this.tone(185,.045,'square',.035,n+.03);}this.external=ext;}
    toggle(){this.muted=!this.muted;if(this.master)this.master.gain.value=this.muted?0:.17;if(this.external)this.external.muted=this.muted;return !this.muted;}
  }
  Q.AudioEngine=AudioEngine;
})();
