(function(){
'use strict';
const Q=window.CCGQuest,canvas=document.getElementById('game'),ctx=canvas.getContext('2d',{alpha:false}),loading=document.getElementById('loading');
const input=new Q.Input(canvas),assets=new Q.AssetLoader(),audio=new Q.AudioEngine();ctx.imageSmoothingEnabled=true;
const S={mode:'loading',returnMode:'title',practice:false,stage:0,elapsed:0,score:0,lives:3,mult:1,best:0,time:0,last:0,entities:[],shots:[],particles:[],boss:null,fighter:null,beadTime:0,spawn:0,itemSpawn:0,enemySpawn:0,powerSpawn:0,transition:null,buttons:[],shake:0,flash:0,toast:null};
const P={x:250,y:603,w:88,h:132,vx:0,vy:0,ground:true,face:1,hp:100,max:100,inv:0,fire:0,duck:false,shield:0,speed:0,double:0,anim:0,attack:null,attackT:0,attackLen:0};
const ACH=new Q.Achievements(a=>{S.toast={text:a.name,xp:a.xp,until:Q.now()+3200};audio.sfx('unlock');});S.best=ACH.profile.best||0;
const now=()=>Q.now(),rhit=(a,b)=>Q.rectHit(a,b),clamp=Q.clamp,rand=Q.rand,pick=Q.pick;
function rr(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill)ctx.fill();if(stroke)ctx.stroke();}
function text(t,x,y,size=20,col='#fff',align='left',weight=800){ctx.fillStyle=col;ctx.font=`${weight} ${size}px Consolas,monospace`;ctx.textAlign=align;ctx.fillText(t,x,y);}
function focus(){canvas.focus({preventScroll:true});try{scrollTo({top:0,left:0,behavior:'instant'});}catch(_e){scrollTo(0,0);}}
function mode(m){S.mode=m;S.buttons=[];focus();}
function load(){const jobs=[];['bedroom','budget','christmas','amiga','guru','beads','fighter'].forEach(k=>{jobs.push(assets.optionalImage('bg_'+k,`assets/backgrounds/${k}.svg`));jobs.push(assets.optionalImage('custom_bg_'+k,Q.customAsset?.('backgrounds',k)));});jobs.push(assets.optionalImage('mascot','/resources/images/ccgamer-logo.png'));jobs.push(assets.optionalImage('custom_mascot',Q.customAsset?.('player','mascot')));['bedroom','budget','christmas','amiga','guru'].forEach(k=>{jobs.push(assets.optionalImage('boss_'+k,Q.customAsset?.('bosses',k)));jobs.push(assets.optionalImage('hazard_'+k,Q.customAsset?.('hazards',k)));});['tape','disk','zzap','joystick'].forEach(k=>jobs.push(assets.optionalImage('item_'+k,Q.customAsset?.('collectibles',k))));['shield','speed','double'].forEach(k=>jobs.push(assets.optionalImage('power_'+k,Q.customAsset?.('powers',k))));jobs.push(assets.optionalImage('fighter_enemy',Q.customAsset?.('fighter','enemy')));return Promise.all(jobs);}
function reset(){S.score=0;S.lives=3;S.mult=1;S.entities=[];S.shots=[];S.particles=[];S.boss=null;S.fighter=null;P.x=250;P.y=Q.GROUND-P.h;P.vx=P.vy=0;P.hp=100;P.inv=0;P.shield=P.speed=P.double=0;P.attack=null;}
function startQuest(){audio.start();ACH.startRun();S.practice=false;reset();enterStage(0);}
function practice(id){audio.start();S.practice=true;reset();if(id==='beads')startBeads();else if(id==='fighter')startFighter();else enterStage(Math.max(0,Q.STAGES.findIndex(s=>s.id===id)));}
function enterStage(i){S.stage=i;S.elapsed=0;S.entities=[];S.shots=[];S.boss=null;S.spawn=1.1;S.itemSpawn=.5;S.enemySpawn=2.4;S.powerSpawn=7;P.x=250;P.y=Q.GROUND-P.h;P.vx=P.vy=0;P.hp=Math.max(65,P.hp);P.inv=now()+1000;audio.setTheme(Q.STAGES[i].music,false,Q.STAGES[i].id);transition(Q.STAGES[i].name,Q.STAGES[i].subtitle,'stage',1.8);if(!S.practice&&i===3)ACH.flag('amiga');if(!S.practice&&i===4)ACH.flag('guru');}
function transition(title,sub,next,dur=1.8){S.transition={title,sub,next,t:0,dur};mode('transition');}
function stageNext(){if(S.practice){transition('PRACTICE COMPLETE','Score not submitted.','title',1.8);return;}if(S.stage===0)startBeads();else if(S.stage===1)startFighter();else if(S.stage<4)enterStage(S.stage+1);else win();}
function startBeads(){S.entities=[];S.shots=[];S.beadTime=0;S.spawn=.65;audio.setTheme(0,false,'beads');transition('ELECTRIC BEAD RUN','JUMP THE CHARGED BEADS.','beads',1.7);}
function startFighter(){S.entities=[];S.shots=[];S.fighter={x:1120,y:Q.GROUND-142,w:92,h:142,hp:100,max:100,vx:0,vy:0,ground:true,think:.25,cool:.8,guard:0,attack:null,phase:0,timer:0,message:'SPECIAL MOVES: MISSING',messageT:2};P.x=330;P.y=Q.GROUND-P.h;P.hp=100;P.vx=P.vy=0;P.attack=null;audio.setTheme(1,true,'fighter');transition('THE 36% CONVERSION BOUT','TIER-TEX NOW ACTUALLY FIGHTS BACK.','fighter',1.9);}
function playerBox(){return P.duck?{x:P.x+18,y:P.y+72,w:50,h:55}:{x:P.x+17,y:P.y+16,w:56,h:110};}
function score(n,x=P.x,y=P.y){const v=Math.round(n*(now()<P.double?2:1)*S.mult);S.score+=v;if(!S.practice){ACH.score(S.score);ACH.profile.totals.scoreLifetime+=v;if(S.score>S.best){S.best=S.score;ACH.profile.best=S.best;}ACH.save();}float('+'+v,x,y,'#ffe66c');}
function float(t,x,y,c='#fff'){S.particles.push({kind:'text',t,x,y,c,life:1});}
function sparks(x,y,c='#6eeaff',n=12){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,v=rand(90,330);S.particles.push({kind:'dot',x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,c,r:rand(2,6),life:rand(.25,.7)});}}
function hurt(n){if(now()<P.inv)return;if(now()<P.shield){if(!S.practice)ACH.add('shieldBlocks',1);audio.sfx('shield');float('BLOCKED',P.x,P.y-12,'#7ef3ff');return;}P.hp-=n;P.inv=now()+900;S.shake=10;S.flash=.2;audio.sfx('hit');sparks(P.x+45,P.y+65,'#ff6075',18);if(P.hp<=0){S.lives--;if(S.lives<=0){gameOver();return;}P.hp=100;P.x=210;P.vy=-350;P.inv=now()+1600;}}
function updatePlayer(dt,fire=true){P.duck=(input.down('ArrowDown','KeyS')&&P.ground);const move=(input.down('ArrowLeft','KeyA')?-1:0)+(input.down('ArrowRight','KeyD')?1:0),max=(now()<P.speed?570:450)*(P.duck?.32:1);P.vx=Q.lerp(P.vx,move*max,1-Math.pow(.001,dt));if(!move)P.vx*=Math.pow(.02,dt);if(move)P.face=move;if(!P.duck&&input.tap('Space','ArrowUp','KeyW')&&P.ground){P.vy=-795;P.ground=false;audio.sfx('jump');}P.vy+=2050*dt;P.x=clamp(P.x+P.vx*dt,70,1160);P.y+=P.vy*dt;if(P.y>=Q.GROUND-P.h){P.y=Q.GROUND-P.h;P.vy=0;P.ground=true;}P.fire=Math.max(0,P.fire-dt);if(fire&&!P.duck&&input.down('KeyZ','ControlLeft')&&P.fire<=0){P.fire=now()<P.double?.14:.22;let sx=P.x+P.w,sy=P.y+58,vx=930,vy=0;if(S.boss){const dx=S.boss.x-sx,dy=S.boss.y-sy,m=Math.max(1,Math.hypot(dx,dy));vx=930*dx/m;vy=930*dy/m;}S.shots.push({x:sx,y:sy,vx,vy,r:8,owner:'p',life:2});if(now()<P.double)S.shots.push({x:sx,y:sy+12,vx:vx*.98,vy:vy+15,r:6,owner:'p',life:2});audio.sfx('shot');}P.anim+=dt*(Math.abs(P.vx)>45?9:2.5);}
function lane(h){return pick([Q.GROUND-h-8,Q.GROUND-P.h+20-h,Q.GROUND-P.h-112])+rand(-6,6);}
function spawnItem(){const type=pick(S.stage<3?['tape','zzap','joystick']:['disk','zzap','joystick']);S.entities.push({k:'item',type,x:1620,y:lane(54),w:54,h:54,vx:-315-S.stage*20,t:0});}
function spawnPower(){S.entities.push({k:'power',type:pick(['shield','speed','double']),x:1620,y:lane(64),w:64,h:64,vx:-285,t:0});}
function spawnHazard(){const i=S.stage,s=Q.STAGES[i];let e;if(i===0){const high=Math.random()<.35;e={k:'haz',label:high?'LOAD ERROR — DUCK':s.hazard,m:'slide',x:1540,y:high?530:640,w:105,h:high?72:95,vx:-285,wait:.8};}else if(i===1){const high=Math.random()<.4;e={k:'haz',label:high?'£9.99 PRICE TAG — DUCK':s.hazard,m:'slide',x:1540,y:high?520:625,w:125,h:high?78:110,vx:-305,wait:.8};}else if(i===2)e={k:'haz',label:'FALLING PRESENT',m:'fall',x:rand(820,1450),y:120,w:84,h:84,vx:-65,vy:240,wait:.7};else if(i===3)e={k:'haz',label:'BOUNCING DISK',m:'bounce',x:1540,y:570,w:88,h:88,vx:-270,vy:-360,wait:.75};else e={k:'haz',label:'GURU GLITCH BEAM',m:'beam',x:rand(820,1420),y:480,w:72,h:255,vx:0,wait:1.05,life:1.2};S.entities.push(e);audio.sfx('bosswarn');}
function spawnEnemy(){S.entities.push({k:'enemy',x:1620,y:lane(70),w:70,h:70,vx:-250,hp:1,t:Math.random()*6});}
function updateStage(dt){S.elapsed+=dt;updatePlayer(dt,true);S.itemSpawn-=dt;S.spawn-=dt;S.enemySpawn-=dt;S.powerSpawn-=dt;if(S.itemSpawn<=0){spawnItem();S.itemSpawn=rand(.8,1.3);}if(S.spawn<=0){spawnHazard();S.spawn=rand(2.3,3.2);}if(S.enemySpawn<=0){spawnEnemy();S.enemySpawn=rand(2.8,4.3);}if(S.powerSpawn<=0){spawnPower();S.powerSpawn=rand(8,12);}updateEntities(dt);updateShots(dt);if(S.elapsed>=Q.STAGES[S.stage].duration)enterBoss();}
function updateEntities(dt){const pb=playerBox();for(const e of S.entities){e.t=(e.t||0)+dt;if(e.wait>0){e.wait-=dt;continue;}if(e.k==='haz'){if(e.m==='fall'){e.vy+=650*dt;e.y+=e.vy*dt;if(e.y>Q.GROUND-e.h){e.y=Q.GROUND-e.h;e.vy=0;e.vx=-250;}}else if(e.m==='bounce'){e.vy+=1050*dt;e.y+=e.vy*dt;if(e.y>Q.GROUND-e.h){e.y=Q.GROUND-e.h;e.vy=-440;}}else if(e.m==='beam'){e.life-=dt;if(e.life<=0)e.dead=true;}e.x+=(e.vx||0)*dt;}else{e.x+=(e.vx||0)*dt;if(e.k==='enemy'){if(S.stage===3)e.y+=Math.sin(e.t*5)*2.6;else if(S.stage===4)e.y+=Math.sin(e.t*7)*4;}}const box={x:e.x,y:e.y,w:e.w,h:e.h};if(!e.dead&&rhit(pb,box)){if(e.k==='item'){score(130,e.x,e.y);audio.sfx('pickup');if(!S.practice){ACH.add('pickups',1);if(e.type==='tape')ACH.add('tapes',1);}e.dead=true;}else if(e.k==='power'){if(e.type==='shield')P.shield=now()+7600;if(e.type==='speed')P.speed=now()+7200;if(e.type==='double')P.double=now()+7200;audio.sfx('pickup');score(200,e.x,e.y);e.dead=true;}else{hurt(e.k==='enemy'?18:24);e.dead=true;}}if(e.x<-180)e.dead=true;}S.entities=S.entities.filter(e=>!e.dead);}
function enterBoss(){S.entities=S.entities.filter(e=>e.k==='item'||e.k==='power');const st=Q.STAGES[S.stage];S.boss={x:1280,y:500,homeX:1280,homeY:500,w:205,h:180,hp:st.bossHp,max:st.bossHp,t:0,next:1.4,warn:0,type:'direct',label:'TRACKING SHOT',relocate:2.5};audio.setTheme(st.music,true,st.id);transition('BOSS: '+st.boss,'READ THE WARNING — JUMP, DUCK OR MOVE.','boss',1.5);}
function bossAttack(){const b=S.boss,i=S.stage,r=Math.random(),opts=i===0?['direct','high','low']:i===1?['lead','low','high','direct']:i===2?['spread','lead','high','low']:i===3?['curve','spread','lead','high','low']:['curve','spread','lead','high','low'];b.type=opts[Math.floor(r*opts.length)];b.label={direct:'TRACKING SHOT',lead:'LEADING SHOT',high:'HIGH SHOT — DUCK',low:'LOW SHOT — JUMP',spread:'SPREAD — FIND THE GAP',curve:'CURVE SHOT — KEEP MOVING'}[b.type];b.warn=1;audio.sfx('bosswarn');}
function bossShoot(kind,off=0){const b=S.boss,sx=b.x-b.w/2,sy=b.y+off,px=P.x+45,py=P.y+(P.duck?100:60),speed=315+S.stage*18;let tx=px,ty=py;if(kind==='lead')tx+=P.vx*.42;if(kind==='high')ty=515;if(kind==='low')ty=Q.GROUND-22;const dx=tx-sx,dy=ty-sy,m=Math.max(1,Math.hypot(dx,dy));S.shots.push({x:sx,y:sy,vx:dx/m*speed,vy:dy/m*speed,r:17,owner:'b',life:6,curve:kind==='curve'?130:0});audio.sfx('shot');}
function moveBoss(dt){const b=S.boss,i=S.stage;b.t+=dt;b.relocate-=dt;if(i===0){b.x=b.homeX+Math.sin(b.t*.75)*45;b.y=b.homeY+Math.sin(b.t*1.4)*45;}else if(i===1){b.x=b.homeX+Math.sin(b.t*.95)*110;b.y=b.homeY+Math.sin(b.t*1.8)*55;}else if(i===2){b.x=b.homeX+Math.sin(b.t*.62)*125;b.y=b.homeY+Math.sin(b.t*2.05)*65;if(b.relocate<=0){b.homeX=pick([1180,1300,1400]);b.relocate=rand(2.2,3.4);}}else if(i===3){b.x=b.homeX+Math.sin(b.t*1.2)*140;b.y=b.homeY+Math.sin(b.t*2.4)*72*Math.cos(b.t*.7);}else{b.x=b.homeX+Math.sin(b.t*1.55)*155;b.y=b.homeY+Math.sin(b.t*2.7)*75;if(b.relocate<=0){b.homeX=pick([1160,1280,1400]);b.homeY=pick([465,510,550]);b.relocate=rand(1.6,2.7);}}b.x=clamp(b.x,1080,1440);b.y=clamp(b.y,445,575);}
function updateBoss(dt){updatePlayer(dt,true);updateEntities(dt);updateShots(dt);const b=S.boss;if(!b)return;moveBoss(dt);b.next-=dt;if(b.warn>0){b.warn-=dt;if(b.warn<=0){if(b.type==='spread'){bossShoot('direct',-75);setTimeout(()=>S.mode==='boss'&&bossShoot('direct',0),360);setTimeout(()=>S.mode==='boss'&&bossShoot('direct',75),720);}else if(b.type==='curve'){bossShoot('curve');setTimeout(()=>S.mode==='boss'&&bossShoot('curve',-60),540);}else bossShoot(b.type);b.next=rand(2.8,4);}}else if(b.next<=0)bossAttack();if(b.hp<=0){if(!S.practice){ACH.add('bosses',1);if(S.stage===1)ACH.flag('budgetBoss');if(S.stage===2)ACH.flag('xmasBoss');}score(1800,b.x,b.y);stageNext();}}
function updateShots(dt){for(const s of S.shots){s.x+=s.vx*dt;s.y+=s.vy*dt;s.vy+=(s.curve||0)*dt;s.life-=dt;if(s.owner==='p'){if(S.boss&&rhit({x:s.x-s.r,y:s.y-s.r,w:s.r*2,h:s.r*2},{x:S.boss.x-S.boss.w/2,y:S.boss.y-S.boss.h/2,w:S.boss.w,h:S.boss.h})){S.boss.hp-=1;s.dead=true;sparks(s.x,s.y,'#ffe66c',7);}for(const e of S.entities)if(!s.dead&&e.k==='enemy'&&rhit({x:s.x-s.r,y:s.y-s.r,w:s.r*2,h:s.r*2},e)){e.dead=true;s.dead=true;score(180,e.x,e.y);if(!S.practice)ACH.add('kills',1);}}else if(rhit({x:s.x-s.r,y:s.y-s.r,w:s.r*2,h:s.r*2},playerBox())){hurt(20);s.dead=true;}if(s.life<=0||s.x<-100||s.x>1700||s.y<-100||s.y>1000)s.dead=true;}S.shots=S.shots.filter(s=>!s.dead);S.entities=S.entities.filter(e=>!e.dead);}
function updateBeads(dt){S.beadTime+=dt;updatePlayer(dt,false);S.spawn-=dt;if(S.spawn<=0){S.entities.push({k:'bead',x:1640,y:Q.GROUND-54,w:54,h:54,vx:-rand(430,560),t:0});S.spawn=rand(.55,1);}const pb=playerBox();for(const e of S.entities){e.x+=e.vx*dt;e.t+=dt;if(!e.hit&&rhit(pb,e)){hurt(24);e.hit=true;}if(!e.scored&&e.x+e.w<P.x&&P.y<Q.GROUND-P.h-15){e.scored=true;score(120,e.x,e.y);if(!S.practice)ACH.add('cleanJumps',1);}if(e.x<-80)e.dead=true;}S.entities=S.entities.filter(e=>!e.dead);if(S.beadTime>12){if(!S.practice&&P.hp>=100)ACH.flag('beadPerfect');if(S.practice)transition('PRACTICE COMPLETE','Electric Bead Run complete.','title',1.8);else enterStage(1);}}
function fighterPlayerAttack(type){if(P.attack||P.duck)return;P.attack=type;P.attackT=now();P.attackLen=type==='kick'?430:300;audio.sfx(type);}
function enemyStart(type){const f=S.fighter;if(f.attack)return;f.attack=type;f.phase=0;f.timer=type==='kick'?.62:.48;f.message=type==='punch'?'TIER-TEX: HIGH PUNCH — DUCK':'TIER-TEX: LOW KICK — JUMP';f.messageT=1;}
function updateFighter(dt){const f=S.fighter;P.duck=input.down('ArrowDown','KeyS')&&P.ground;const move=(input.down('ArrowLeft','KeyA')?-1:0)+(input.down('ArrowRight','KeyD')?1:0);P.vx=Q.lerp(P.vx,move*(P.duck?130:360),1-Math.pow(.001,dt));if(!move)P.vx*=Math.pow(.02,dt);if(input.tap('Space','ArrowUp','KeyW')&&P.ground&&!P.duck){P.vy=-760;P.ground=false;audio.sfx('jump');}P.vy+=2050*dt;P.x=clamp(P.x+P.vx*dt,90,1430);P.y+=P.vy*dt;if(P.y>=Q.GROUND-P.h){P.y=Q.GROUND-P.h;P.vy=0;P.ground=true;}P.face=f.x>=P.x?1:-1;if(input.tap('KeyZ','ControlLeft'))fighterPlayerAttack('punch');if(input.tap('KeyX','KeyC'))fighterPlayerAttack('kick');if(P.attack&&now()-P.attackT>P.attackLen)P.attack=null;f.messageT-=dt;f.guard=Math.max(0,f.guard-dt);f.cool-=dt;f.think-=dt;const dist=f.x-P.x,ad=Math.abs(dist);if(f.think<=0&&!f.attack){f.think=rand(.2,.55);if(f.cool<=0&&ad<190&&Math.random()<.58){enemyStart(Math.random()<.55?'punch':'kick');f.cool=rand(.75,1.35);}else if(Math.random()<.18)f.guard=.55;else f.vx=(ad>175?-Math.sign(dist):Math.random()<.5?Math.sign(dist):-Math.sign(dist))*rand(120,260);if(Math.random()<.08&&f.ground){f.vy=-650;f.ground=false;}}if(f.guard>0)f.vx*=.82;f.vy+=2050*dt;f.x=clamp(f.x+f.vx*dt,100,1500);f.y+=f.vy*dt;if(f.y>=Q.GROUND-f.h){f.y=Q.GROUND-f.h;f.vy=0;f.ground=true;}f.vx*=Math.pow(.12,dt);if(f.attack){f.phase+=dt;f.timer-=dt;if(f.timer<=0){const range=f.attack==='kick'?175:145,vertical=f.attack==='kick'?Math.abs((P.y+95)-(f.y+115))<75:Math.abs((P.y+(P.duck?105:50))-(f.y+55))<65;if(Math.abs(P.x-f.x)<range&&vertical){if(f.attack==='punch'&&P.duck)float('DUCKED',P.x,P.y-15,'#72f1ff');else if(f.attack==='kick'&&!P.ground)float('JUMPED',P.x,P.y-15,'#72f1ff');else hurt(f.attack==='kick'?18:13);}f.attack=null;f.cool=rand(.8,1.4);}}if(P.attack){const prog=clamp((now()-P.attackT)/P.attackLen,0,1),active=prog>.22&&prog<.72,reach=P.attack==='kick'?190:145;if(active&&Math.abs(P.x-f.x)<reach&&!P.hitLatch){P.hitLatch=true;let dmg=P.attack==='kick'?14:9;if(f.guard>0){dmg=Math.ceil(dmg*.35);float('BLOCKED',f.x,f.y-15,'#8feaff');}f.hp-=dmg;audio.sfx(P.attack);sparks(f.x,f.y+65,P.attack==='kick'?'#6eeaff':'#ffe56e',10);score(90,f.x,f.y);}if(prog>.8)P.hitLatch=false;}if(f.hp<=0){if(!S.practice){ACH.add('fighterWins',1);ACH.flag('fighterCombo');}score(2600,f.x,f.y);if(S.practice)transition('PRACTICE COMPLETE','Tier-Tex has been defeated.','title',1.8);else enterStage(2);}if(P.hp<=0)gameOver();}
function update(dt){S.time+=dt;if(S.mode==='transition'){S.transition.t+=dt;if(S.transition.t>=S.transition.dur)mode(S.transition.next);}else if(S.mode==='stage')updateStage(dt);else if(S.mode==='boss')updateBoss(dt);else if(S.mode==='beads')updateBeads(dt);else if(S.mode==='fighter')updateFighter(dt);for(const p of S.particles){p.life-=dt;if(p.kind==='dot'){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=360*dt;}else p.y-=34*dt;}S.particles=S.particles.filter(p=>p.life>0);S.flash=Math.max(0,S.flash-dt);S.shake*=Math.pow(.01,dt);}
function bg(id){const im=assets.get('custom_bg_'+id)||assets.get('bg_'+id);if(im){ctx.drawImage(im,0,0,Q.W,Q.H);return;}const pal={bedroom:['#19133a','#39284c'],budget:['#101b2d','#4c2d25'],christmas:['#162e32','#402044'],amiga:['#06192c','#192868'],guru:['#13020b','#460811'],beads:['#341d65','#111128'],fighter:['#8072b7','#302b5a']}[id]||['#111','#222'],g=ctx.createLinearGradient(0,0,0,Q.H);g.addColorStop(0,pal[0]);g.addColorStop(1,pal[1]);ctx.fillStyle=g;ctx.fillRect(0,0,Q.W,Q.H);ctx.globalAlpha=.18;ctx.strokeStyle='#7deaff';for(let x=0;x<Q.W;x+=80){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,Q.H);ctx.stroke();}ctx.globalAlpha=1;}
function drawPlayer(){const cx=P.x+44,ground=P.y+P.h+6,duck=P.duck&&P.ground,run=Math.abs(P.vx)>30&&!duck,sw=run?Math.sin(P.anim)*22:0;if(now()<P.inv&&Math.floor(now()/85)%2===0)ctx.globalAlpha=.4;ctx.save();ctx.fillStyle='rgba(0,0,0,.3)';ctx.beginPath();ctx.ellipse(cx,ground+5,45,11,0,0,7);ctx.fill();const hip=duck?ground-55:ground-83;function leg(x,s,front){let fx=x+s,fy=ground-5;if(P.attack==='kick'&&front){const q=Math.sin(clamp((now()-P.attackT)/P.attackLen,0,1)*Math.PI);fx=x+P.face*105*q;fy=ground-42*q;}ctx.strokeStyle='#07111b';ctx.lineWidth=30;ctx.beginPath();ctx.moveTo(x,hip);ctx.quadraticCurveTo((x+fx)/2,hip+37,fx,fy-10);ctx.stroke();ctx.strokeStyle='#17425b';ctx.lineWidth=21;ctx.stroke();ctx.fillStyle='#080b10';rr(fx-18,fy-14,39,18,8,true,false);}leg(cx-18,-sw,false);leg(cx+18,sw,true);ctx.fillStyle='#17425b';ctx.strokeStyle='#07111b';ctx.lineWidth=6;rr(cx-43,hip-25,86,48,18,true,true);const im=assets.get('custom_mascot')||assets.get('mascot'),w=duck?122:138,h=duck?108:140,y=duck?hip-86:hip-114;if(im){if(P.face<0){ctx.save();ctx.translate(cx+w/2,0);ctx.scale(-1,1);ctx.drawImage(im,0,y,w,h);ctx.restore();}else ctx.drawImage(im,cx-w/2,y,w,h);}else{ctx.fillStyle='#efb58e';ctx.beginPath();ctx.arc(cx,y+42,40,0,7);ctx.fill();ctx.fillStyle='#17384d';rr(cx-44,y+70,88,60,16,true,false);text('CCG',cx,y+108,15,'#fff','center',900);}ctx.restore();ctx.globalAlpha=1;bar(P.x-10,P.y-35,110,P.hp/P.max,'#62ed8e');if(now()<P.shield){const rem=clamp((P.shield-now())/7600,0,1);ctx.strokeStyle=rem<.25?'#ffd45d':'#70efff';ctx.lineWidth=5;ctx.beginPath();ctx.arc(cx,P.y+62,82,-Math.PI/2,-Math.PI/2+Math.PI*2*rem);ctx.stroke();}}
function bar(x,y,w,p,c){ctx.fillStyle='rgba(0,0,0,.75)';rr(x,y,w,14,6,true,false);ctx.fillStyle='#252334';rr(x+2,y+2,w-4,10,4,true,false);ctx.fillStyle=c;rr(x+2,y+2,(w-4)*clamp(p,0,1),10,4,true,false);}
function drawEntities(){for(const e of S.entities){if(e.k==='item'){const im=assets.get('item_'+e.type);if(im)ctx.drawImage(im,e.x,e.y,e.w,e.h);else{text(e.type.toUpperCase(),e.x+e.w/2,e.y+32,13,'#fff','center');ctx.strokeStyle='#6eeaff';ctx.strokeRect(e.x,e.y,e.w,e.h);}}else if(e.k==='power'){const im=assets.get('power_'+e.type);if(im)ctx.drawImage(im,e.x,e.y,e.w,e.h);else{text(e.type==='shield'?'AR':e.type==='double'?'X2':'CP',e.x+e.w/2,e.y+38,18,'#ffe56e','center');ctx.strokeStyle='#ffe56e';ctx.strokeRect(e.x,e.y,e.w,e.h);}}else if(e.k==='enemy'){ctx.fillStyle='#19141e';ctx.strokeStyle='#ff6bd5';ctx.lineWidth=4;rr(e.x,e.y,e.w,e.h,10,true,true);text('8BIT',e.x+35,e.y+42,13,'#7eeaff','center');}else if(e.k==='haz'){if(e.wait>0){text('! INCOMING !',e.x+e.w/2,e.y-15,14,'#ffd45d','center');ctx.strokeStyle='#ff4964';ctx.setLineDash([10,8]);ctx.strokeRect(e.x-8,e.y-8,e.w+16,e.h+16);ctx.setLineDash([]);}const im=assets.get('hazard_'+Q.STAGES[S.stage].id);if(im)ctx.drawImage(im,e.x,e.y,e.w,e.h);else{ctx.fillStyle='#3b1420';ctx.strokeStyle='#ff4964';ctx.lineWidth=4;rr(e.x,e.y,e.w,e.h,10,true,true);text(e.label,e.x+e.w/2,e.y+e.h/2,13,'#fff','center');}}else if(e.k==='bead'){ctx.shadowBlur=22;ctx.shadowColor='#66efff';ctx.fillStyle='#74f5ff';ctx.beginPath();ctx.arc(e.x+27,e.y+27,23,0,7);ctx.fill();ctx.shadowBlur=0;}}}
function drawShots(){for(const s of S.shots){ctx.shadowBlur=14;ctx.shadowColor=s.owner==='p'?'#ffe66c':'#ff536d';ctx.fillStyle=s.owner==='p'?'#ffe66c':'#ff536d';ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,7);ctx.fill();ctx.shadowBlur=0;}}
function drawBoss(){const b=S.boss;if(!b)return;const st=Q.STAGES[S.stage],im=assets.get('boss_'+st.id);if(im)ctx.drawImage(im,b.x-b.w/2,b.y-b.h/2,b.w,b.h);else{ctx.fillStyle='#12101a';ctx.strokeStyle=st.accent;ctx.lineWidth=6;rr(b.x-b.w/2,b.y-b.h/2,b.w,b.h,20,true,true);text(st.boss,b.x,b.y,18,'#fff','center');}bar(b.x-b.w/2,b.y-b.h/2-26,b.w,b.hp/b.max,'#ff5570');if(b.warn>0){text(b.label,b.x,b.y-b.h/2-48,16,'#ffe66c','center');ctx.strokeStyle='#ff5268';ctx.lineWidth=5;ctx.beginPath();ctx.arc(b.x-b.w/2-25,b.y,30+30*(1-b.warn),0,7);ctx.stroke();}}
function drawFighter(){bg('fighter');const f=S.fighter;drawPlayer();const im=assets.get('fighter_enemy');if(im)ctx.drawImage(im,f.x-f.w/2,f.y,f.w,f.h);else{ctx.fillStyle=f.guard>0?'#314a63':'#36313a';ctx.strokeStyle='#ffb759';ctx.lineWidth=5;rr(f.x-f.w/2,f.y,f.w,f.h,18,true,true);text('TIER-TEX',f.x,f.y+58,14,'#fff','center');}bar(f.x-f.w/2,f.y-28,f.w,f.hp/f.max,'#ff6a62');if(f.attack){ctx.strokeStyle=f.attack==='kick'?'#6eeaff':'#ffe66c';ctx.lineWidth=12;ctx.beginPath();ctx.moveTo(f.x,f.y+70);ctx.lineTo(f.x-110,f.y+(f.attack==='kick'?112:48));ctx.stroke();}text('36% CONVERSION BOUT',800,88,28,'#ffe56e','center');text('Z/CTRL PUNCH   X/C KICK   ↓ DUCK   SPACE JUMP',800,125,15,'#fff','center');if(f.messageT>0)text(f.message,800,170,18,'#ffcf68','center');}
function drawHUD(){ctx.fillStyle='rgba(4,4,12,.78)';ctx.fillRect(0,0,Q.W,75);text('SCORE '+Q.fmt(S.score),24,31,18,'#fff');text('LIVES '+'♥'.repeat(Math.max(0,S.lives)),24,58,16,'#ff7690');text(S.mode==='fighter'?'36% BOUT':Q.STAGES[S.stage]?.name||'',800,35,20,'#7eeaff','center');text('BEST '+Q.fmt(S.best),1570,31,17,'#fff','right');text('RANK '+ACH.rank(),1570,58,13,'#ffd45d','right');if(now()<P.shield){const rem=Math.max(0,(P.shield-now())/1000);text('ACTION REPLAY '+rem.toFixed(1)+'s',800,61,13,rem<2?'#ffcf5a':'#78efff','center');}}
function particlesDraw(){for(const p of S.particles){ctx.globalAlpha=clamp(p.life*2,0,1);if(p.kind==='dot'){ctx.fillStyle=p.c;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,7);ctx.fill();}else text(p.t,p.x,p.y,15,p.c,'center');}ctx.globalAlpha=1;}
function drawStageScene(){bg(Q.STAGES[S.stage].id);drawEntities();drawShots();drawBoss();drawPlayer();drawHUD();}
function drawBeads(){bg('beads');drawEntities();drawPlayer();drawHUD();text('ELECTRIC BEAD RUN',800,115,28,'#ffe56e','center');}
function button(x,y,w,h,label,fn,hot=false){S.buttons.push({x,y,w,h,fn});ctx.fillStyle=hot?'rgba(255,70,90,.18)':'rgba(10,18,31,.85)';ctx.strokeStyle=hot?'#ff6074':'#66eaff';ctx.lineWidth=2;rr(x,y,w,h,12,true,true);text(label,x+w/2,y+h/2+7,18,'#fff','center');}
function title(){S.buttons=[];bg('bedroom');ctx.fillStyle='rgba(3,4,12,.72)';ctx.fillRect(0,0,Q.W,Q.H);text('CCG ARCADE PRESENTS',800,135,22,'#72eaff','center');text("CHEEKY'S COMMODORE QUEST",800,225,58,'#fff','center',900);text('GITHUB FOUNDATION • LIVE ASSET PIPELINE',800,270,18,'#ffd45d','center');button(530,410,250,62,'START QUEST',startQuest);button(820,410,250,62,'LEVEL SELECT',()=>mode('levels'));button(530,500,250,58,audio.muted?'SOUND: OFF':'SOUND: ON',()=>audio.toggle());button(820,500,250,58,'ACHIEVEMENTS',()=>mode('achievements'));text('MOVE A/D • JUMP SPACE • DUCK S/↓ • FIRE/PUNCH Z • KICK X/C',800,650,17,'#d3d5e4','center');text('Custom graphics and music can be replaced from the CCG admin panel.',800,690,14,'#9ca1b7','center');}
function levels(){S.buttons=[];ctx.fillStyle='#080713';ctx.fillRect(0,0,Q.W,Q.H);text('LEVEL SELECT',800,110,46,'#72eaff','center');let y=170;Q.LEVELS.forEach((l,i)=>{button(480,y,640,58,`${i+1}. ${l[1]}`,()=>practice(l[0]));y+=70;});button(650,775,300,52,'BACK',()=>mode('title'));}
function achievementScreen(){S.buttons=[];ctx.fillStyle='#080713';ctx.fillRect(0,0,Q.W,Q.H);text('CCG ACHIEVEMENTS',800,65,40,'#72eaff','center');const list=ACH.entries();list.forEach((a,i)=>{const c=i%4,r=(i/4)|0,x=45+c*385,y=105+r*98;ctx.fillStyle=a.done?'rgba(45,130,80,.26)':'rgba(15,16,29,.9)';ctx.strokeStyle=a.done?'#78efa4':'#555a6d';rr(x,y,355,82,10,true,true);text((a.done?'✓ ':'')+a.name,x+12,y+24,13,a.done?'#8cffb5':'#fff');text(a.desc.slice(0,43),x+12,y+45,10,'#adb1c2');text(`${Math.min(a.value,a.target)}/${a.target}`,x+335,y+68,10,'#ffd45d','right');});button(650,805,300,45,'BACK',()=>mode('title'));}
function overlay(){if(S.mode==='transition'){ctx.fillStyle='rgba(0,0,0,.68)';ctx.fillRect(0,0,Q.W,Q.H);text(S.transition.title,800,410,48,'#72eaff','center');text(S.transition.sub,800,465,20,'#ffe56e','center');}else if(S.mode==='pause'||S.mode==='quit'){S.buttons=[];ctx.fillStyle='rgba(0,0,0,.65)';ctx.fillRect(0,0,Q.W,Q.H);text(S.mode==='pause'?'PAUSED':'ABANDON THIS RUN?',800,300,52,S.mode==='pause'?'#72eaff':'#ff7183','center');button(590,375,420,58,'RESUME',()=>mode(S.returnMode));if(S.mode==='pause')button(590,450,420,58,'LEVEL SELECT',()=>mode('levels'));button(590,S.mode==='pause'?525:460,420,58,'QUIT TO TITLE',quit,true);}else if(S.mode==='over'||S.mode==='won'){S.buttons=[];ctx.fillStyle='rgba(0,0,0,.74)';ctx.fillRect(0,0,Q.W,Q.H);text(S.mode==='won'?'COMMODORE QUEST COMPLETE':'GAME OVER',800,280,54,S.mode==='won'?'#7df0a5':'#ff7183','center');text('SCORE '+Q.fmt(S.score),800,350,30,'#fff','center');button(535,420,250,60,'PLAY AGAIN',startQuest);button(815,420,250,60,'LEVEL SELECT',()=>mode('levels'));button(675,505,250,54,'TITLE',quit);}}
function draw(){ctx.save();const sh=S.shake;ctx.translate(sh?rand(-sh,sh):0,sh?rand(-sh,sh):0);if(S.mode==='title')title();else if(S.mode==='levels')levels();else if(S.mode==='achievements')achievementScreen();else if(S.mode==='fighter')drawFighter();else if(S.mode==='beads')drawBeads();else drawStageScene();particlesDraw();if(S.toast&&now()<S.toast.until){ctx.fillStyle='rgba(4,8,15,.94)';ctx.strokeStyle='#ffd45d';ctx.lineWidth=3;rr(1080,760,470,105,12,true,true);text('ACHIEVEMENT UNLOCKED',1100,790,13,'#ffd45d');text(S.toast.text,1100,820,19,'#fff');text('+'+S.toast.xp+' CCG XP',1100,846,13,'#7ff0a4');}overlay();ctx.restore();if(S.flash>0){ctx.globalAlpha=S.flash;ctx.fillStyle='#ff4964';ctx.fillRect(0,0,Q.W,Q.H);ctx.globalAlpha=1;}ctx.globalAlpha=.08;ctx.fillStyle='#000';for(let y=0;y<Q.H;y+=4)ctx.fillRect(0,y,Q.W,1);ctx.globalAlpha=1;}
function gameOver(){mode('over');if(!S.practice)ACH.save();}
function win(){if(!S.practice)ACH.flag('won');mode('won');}
function quit(){audio.setTheme(0,false,'title');reset();mode('title');}
function pointer(ev){const r=canvas.getBoundingClientRect();return{x:(ev.clientX-r.left)*Q.W/r.width,y:(ev.clientY-r.top)*Q.H/r.height};}
canvas.addEventListener('pointerdown',e=>{focus();const p=pointer(e);for(let i=S.buttons.length-1;i>=0;i--){const b=S.buttons[i];if(p.x>=b.x&&p.x<=b.x+b.w&&p.y>=b.y&&p.y<=b.y+b.h){b.fn();break;}}});
function pause(){if(['stage','boss','beads','fighter','transition'].includes(S.mode)){S.returnMode=S.mode;mode('pause');}else if(S.mode==='pause')mode(S.returnMode);}
document.getElementById('btn-pause').onclick=pause;document.getElementById('btn-level').onclick=()=>mode('levels');document.getElementById('btn-quit').onclick=()=>{if(S.mode==='title')return;S.returnMode=S.mode;mode('quit');};document.getElementById('btn-fullscreen').onclick=()=>{const sh=document.getElementById('game-shell');document.fullscreenElement?document.exitFullscreen?.():sh.requestFullscreen?.();focus();};
document.querySelectorAll('[data-touch]').forEach(b=>{const n=b.dataset.touch;['pointerdown','touchstart'].forEach(ev=>b.addEventListener(ev,e=>{e.preventDefault();input.setVirtual(n,true);}));['pointerup','pointercancel','pointerleave','touchend'].forEach(ev=>b.addEventListener(ev,e=>{e.preventDefault();input.setVirtual(n,false);}));});
addEventListener('keydown',e=>{if(e.code==='Escape')pause();});
function loop(t){const dt=Math.min(.033,(t-S.last)/1000||0);S.last=t;if(!['title','levels','achievements','pause','quit','over','won','loading'].includes(S.mode))update(dt);draw();input.clear();requestAnimationFrame(loop);}
window.CCGQuestDebug={startQuest,practice,getState:()=>({mode:S.mode,stage:S.stage,score:S.score,player:{x:P.x,y:P.y,hp:P.hp,duck:P.duck},boss:S.boss&&{x:S.boss.x,y:S.boss.y,hp:S.boss.hp},fighter:S.fighter&&{x:S.fighter.x,hp:S.fighter.hp,attack:S.fighter.attack}})};
Promise.resolve(Q.hydrateRemoteAssets?.()).catch(()=>false).then(load).then(()=>{loading.classList.add('is-hidden');audio.setTheme(0,false,'title');mode('title');requestAnimationFrame(loop);}).catch(e=>{loading.textContent='LOAD ERROR: '+e.message;console.error(e);});
})();
