"use strict";
function drawEntities(){
  for(const e of S.entities){
    if(e.kind==='item'){const im=assets.get('item_'+e.type),bob=Math.sin(e.t*5)*4;ctx.save();ctx.translate(e.x+e.w/2,e.y+e.h/2+bob);ctx.rotate((e.rot||0)+(e.spin||0)*e.t);ctx.shadowBlur=16;ctx.shadowColor='#72ff91';if(im)ctx.drawImage(im,-e.w/2,-e.h/2,e.w,e.h);else{ctx.fillStyle='#275b37';rr(-e.w/2,-e.h/2,e.w,e.h,8);text(e.type.toUpperCase(),0,5,12,'#fff','center');}ctx.restore();ctx.shadowBlur=0;}
    else if(e.kind==='power'){const im=assets.get('power_'+e.type);ctx.save();ctx.translate(e.x+e.w/2,e.y+e.h/2);const p=1+Math.sin(e.t*7)*.05;ctx.scale(p,p);ctx.shadowBlur=18;ctx.shadowColor='#ffe66c';if(im)ctx.drawImage(im,-32,-32,64,64);else{ctx.fillStyle='#171223';rr(-30,-30,60,60,12);text(e.type.toUpperCase(),0,6,11,'#ffe66c','center');}ctx.restore();ctx.shadowBlur=0;}
    else if(e.kind==='enemy')drawEnemy(e);else if(e.kind==='hazard')drawHazard(e);else if(e.kind==='bead'){ctx.save();ctx.translate(e.x+e.w/2,e.y+e.h/2);if(e.wait>0){ctx.globalAlpha=.35;ctx.strokeStyle=e.response==='duck'?'#ff7b8f':'#70e8ff';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,28+Math.sin(e.t*12)*5,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1;}else{ctx.shadowBlur=18;ctx.shadowColor=e.response==='duck'?'#ff7b8f':'#70e8ff';ctx.fillStyle=e.response==='duck'?'#ff7b8f':'#70e8ff';ctx.beginPath();ctx.arc(0,0,e.w*.42,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(-8,-8,6,0,Math.PI*2);ctx.fill();}ctx.restore();ctx.shadowBlur=0;}
  }
}
function drawShots(){for(const s of S.shots){ctx.shadowBlur=10;ctx.shadowColor=s.owner==='p'?'#ffe66c':'#ff536d';ctx.fillStyle=s.owner==='p'?'#ffe66c':'#ff536d';ctx.beginPath();ctx.arc(s.x,s.y,s.r||6,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;}}
function drawBoss(){const b=S.boss;if(!b)return;const id=stage().id,key='boss'+id.charAt(0).toUpperCase()+id.slice(1),sheet=assets.get('sheet_'+key),meta=Q.customAssetMeta?.('spritesheets',key),im=assets.get('boss_'+id),face=playerAnchorX()>=b.x?1:-1,stateName=b.anim?.state||'idle';if(sheet&&meta)Q.drawAnchoredSprite(ctx,sheet,meta,stateName,b.anim?.time||0,b.x,b.y+b.h/2,face);else if(im)ctx.drawImage(im,b.x-b.w/2,b.y-b.h/2,b.w,b.h);else{ctx.fillStyle='#29111d';ctx.strokeStyle=stage().accent;ctx.lineWidth=6;rr(b.x-b.w/2,b.y-b.h/2,b.w,b.h,20,true,true);text(stage().boss,b.x,b.y,18,'#fff','center');}bar(b.x-b.w/2,b.y-b.h/2-28,b.w,b.hp/b.max,'#ff5570');text(`PHASE ${b.phase}`,b.x,b.y-b.h/2-46,13,stage().accent,'center');}
function drawHUD(){const st=stage();ctx.fillStyle='rgba(5,7,15,.82)';rr(24,20,575,86,14);text(`SCORE ${Q.fmt(S.score)}`,44,50,18,'#fff');text(`BEST ${Q.fmt(S.best)}`,44,78,13,'#9fb0c9');text(`LIVES ${S.lives}`,242,50,18,'#fff');text(`HP ${Math.max(0,Math.ceil(P.hp))}`,242,78,13,'#9fb0c9');if(S.mode==='stage'||S.mode==='boss'){text(`${st.objective}: ${S.objective}/${st.objectiveTarget}`,405,50,15,st.accent);text(S.combo>1?`CHAIN x${S.mult.toFixed(2)}`:st.mechanic.toUpperCase(),405,78,13,S.combo>1?'#ffe66c':'#9fb0c9');}else if(S.mode==='beads')text(`${Math.max(0,Math.ceil(T.beads.duration-S.mini.time))} SEC`,405,50,16,'#70e8ff');}
function drawStage(){const id=stage().id;bg(id);drawEntities();drawShots();drawPlayer();if(S.mode==='boss')drawBoss();foreground(id);drawHUD();}
function drawBeads(){bg('beads');drawEntities();drawPlayer();foreground('beads');drawHUD();text('LOW = JUMP     HIGH = CROUCH',800,120,16,'#fff','center');}

function drawFighter(){
  bg('fighter');drawPlayer();const f=S.fighter,sheet=assets.get('sheet_fighter'),meta=fighterEnemyMeta(),stateName=f.anim.state;if(sheet&&meta)Q.drawAnchoredSprite(ctx,sheet,meta,stateName,f.anim.time,f.x,f.groundY,f.face||-1);else{ctx.fillStyle='#7b3c48';rr(f.x-46,f.groundY-154,92,154,18);}
  if(f.attack&&f.attack.phase==='telegraph'){ctx.strokeStyle=f.attack.type==='kick'?'#ffe66c':'#70e8ff';ctx.lineWidth=6;ctx.globalAlpha=.8;ctx.beginPath();ctx.arc(f.x,f.groundY-160,105+Math.sin(S.time*18)*8,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1;}
  foreground('fighter');bar(90,40,440,P.hp/P.max,'#62ed8e');bar(1070,40,440,f.hp/f.max,'#ff6a62');text('CHEEKY',90,32,16,'#fff');text('RETSU',1510,32,16,'#fff','right');text(`TIMER ${Math.ceil(f.time)}`,800,65,22,'#ffe66c','center');text(f.ai.toUpperCase(),800,100,16,f.attack?.phase==='telegraph'?'#ffe66c':'#70e8ff','center');text('Z PUNCH   X/C KICK   ↓ CROUCH HIGH PUNCH   SPACE JUMP LOW KICK',800,855,14,'#fff','center');
}
function drawInvaders(){
  bg('invaders');const g=S.inv;for(const b of g.bunkers){if(b.hp<=0)continue;const im=assets.get('invader_bunker');ctx.globalAlpha=.3+.7*(b.hp/b.max);if(im)ctx.drawImage(im,b.x-b.w/2,b.y,b.w,b.h);else{ctx.fillStyle='#59d98a';ctx.fillRect(b.x-b.w/2,b.y,b.w,b.h);}ctx.globalAlpha=1;}for(const a of g.aliens){if(!a.alive)continue;const im=assets.get('invader_alien'+Math.min(5,a.row+1)),bob=Math.sin(a.phase)*3;if(im)ctx.drawImage(im,a.x,a.y+bob,a.w,a.h);else{ctx.fillStyle='#70e8ff';ctx.fillRect(a.x,a.y+bob,a.w,a.h);}}const ship=assets.get('invader_ship');if(ship)ctx.drawImage(ship,g.shipX-48,775,96,58);else{ctx.fillStyle='#fff';ctx.beginPath();ctx.moveTo(g.shipX,770);ctx.lineTo(g.shipX-50,830);ctx.lineTo(g.shipX+50,830);ctx.closePath();ctx.fill();}for(const sh of g.shots){const im=assets.get('invader_'+(sh.owner==='p'?'playerShot':'enemyShot'));if(im)ctx.drawImage(im,sh.x-8,sh.y-14,16,28);else{ctx.fillStyle=sh.owner==='p'?'#ffe66c':'#ff536d';ctx.fillRect(sh.x-3,sh.y-10,6,20);}}text('ALIEN FORMATION',800,62,28,'#70e8ff','center');text(`SHIELDS ${g.shield}   ALIENS ${g.aliens.filter(a=>a.alive).length}`,800,96,15,'#fff','center');
}
function drawMaze(){
  bg('maze');const m=S.maze,cell=52,ox=(Q.W-m.W*cell)/2,oy=130;for(const k of m.walls){const[x,y]=k.split(',').map(Number),px=ox+x*cell,py=oy+y*cell;ctx.fillStyle='#170b2b';ctx.fillRect(px,py,cell,cell);ctx.strokeStyle='#743cff';ctx.lineWidth=3;ctx.strokeRect(px+3,py+3,cell-6,cell-6);ctx.strokeStyle='#b36cff';ctx.lineWidth=1;ctx.strokeRect(px+9,py+9,cell-18,cell-18);}for(const k of m.dots){const[x,y]=k.split(',').map(Number);ctx.fillStyle=m.power.has(k)?'#ffe66c':'#70e8ff';ctx.beginPath();ctx.arc(ox+x*cell+26,oy+y*cell+26,m.power.has(k)?8:3,0,Math.PI*2);ctx.fill();}if(m.fruit.active){ctx.fillStyle='#ff7b8f';ctx.beginPath();ctx.arc(ox+m.fruit.x*cell+26,oy+m.fruit.y*cell+26,11,0,Math.PI*2);ctx.fill();ctx.fillStyle='#7dffb4';ctx.fillRect(ox+m.fruit.x*cell+25,oy+m.fruit.y*cell+8,3,9);}const pcx=ox+m.px*cell+26,pcy=oy+m.py*cell+26,ang=(Math.sin(m.mouth)+1)*.18+.08,base=Math.atan2(m.dir.y,m.dir.x)||0;ctx.fillStyle=m.powered>0?'#ffe66c':'#fff';ctx.beginPath();ctx.moveTo(pcx,pcy);ctx.arc(pcx,pcy,18,base+ang,base+Math.PI*2-ang);ctx.closePath();ctx.fill();for(const e of m.enemies){const x=ox+e.x*cell+26,y=oy+e.y*cell+26;ctx.fillStyle=m.powered>0?'#315980':e.c;ctx.beginPath();ctx.arc(x,y-3,17,Math.PI,0);ctx.lineTo(x+17,y+16);ctx.lineTo(x+9,y+9);ctx.lineTo(x,y+16);ctx.lineTo(x-9,y+9);ctx.lineTo(x-17,y+16);ctx.closePath();ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(x-6,y-4,5,0,Math.PI*2);ctx.arc(x+6,y-4,5,0,Math.PI*2);ctx.fill();ctx.fillStyle='#111';ctx.fillRect(x-7,y-5,3,3);ctx.fillRect(x+5,y-5,3,3);}text(`DOTS ${m.collected}/${m.target}   POWER ${m.powered.toFixed(1)}   LIVES ${S.lives}`,800,92,19,'#fff','center');
}

function particlesDraw(){for(const p of S.particles){if(p.kind==='dot'){ctx.globalAlpha=clamp(p.life/.6,0,1);ctx.fillStyle=p.c;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();}else{ctx.globalAlpha=clamp(p.life,0,1);text(p.t,p.x,p.y,16,p.c,'center');}ctx.globalAlpha=1;}}
function particlesUpdate(dt){for(const p of S.particles){p.life-=dt;if(p.kind==='dot'){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=300*dt;}else p.y-=35*dt;}S.particles=S.particles.filter(p=>p.life>0);}
function button(x,y,w,h,label,fn,danger=false){S.buttons.push({x,y,w,h,fn});ctx.fillStyle=danger?'rgba(86,18,31,.92)':'rgba(9,16,31,.94)';ctx.strokeStyle=danger?'#ff7183':'#6eeaff';ctx.lineWidth=3;rr(x,y,w,h,12,true,true);text(label,x+w/2,y+h/2+7,18,danger?'#ffd3d8':'#fff','center',900);}
function title(){bg('bedroom');ctx.fillStyle='rgba(3,5,12,.58)';ctx.fillRect(0,0,Q.W,Q.H);text("CHEEKY'S",800,170,38,'#fff','center',900);text('COMMODORE QUEST',800,245,70,'#6eeaff','center',900);text('QUEST 3.0 REBUILD',800,300,24,'#ffe66c','center',900);text('Fairer attacks, rebuilt sprite timing, real stage identity and less blocky nonsense.',800,347,17,'#d9e4f2','center',700);S.buttons=[];button(585,405,430,64,'START QUEST',startQuest);button(585,490,430,60,'LEVEL SELECT',()=>mode('levels'));button(585,570,430,60,'ACHIEVEMENTS',()=>mode('achievements'));text('MOVE: ARROWS / WASD     JUMP: SPACE     FIRE/PUNCH: Z / CTRL     KICK: X / C',800,688,15,'#fff','center');text('Danger is telegraphed. Losing a life keeps you at the current section.',800,721,14,'#7dffb4','center');text(`BEST ${Q.fmt(S.best)}   •   ${ACH.rank()}   •   ${ACH.profile.xp} XP`,800,795,16,'#ffe66c','center');}
function levels(){bg('amiga');ctx.fillStyle='rgba(3,5,12,.74)';ctx.fillRect(0,0,Q.W,Q.H);text('LEVEL SELECT',800,110,46,'#70e8ff','center');text('Practice does not submit the run score.',800,145,14,'#c8d3e1','center');S.buttons=[];Q.LEVELS.forEach((l,i)=>{const col=i%3,row=Math.floor(i/3),x=220+col*395,y=205+row*150;button(x,y,330,78,`${i+1}. ${l[1].toUpperCase()}`,()=>practice(l[0]));});button(625,710,350,58,'BACK',()=>mode('title'));}
function achievementScreen(){bg('guru');ctx.fillStyle='rgba(3,5,12,.8)';ctx.fillRect(0,0,Q.W,Q.H);text('ACHIEVEMENTS',800,80,42,'#ffe66c','center');text(`${ACH.rank()} • ${ACH.profile.xp} XP`,800,115,16,'#fff','center');const entries=ACH.entries();for(let i=0;i<entries.length;i++){const a=entries[i],col=i%2,row=Math.floor(i/2),x=95+col*760,y=150+row*50;if(y>800)break;ctx.fillStyle=a.done?'rgba(26,70,46,.74)':'rgba(10,15,27,.78)';rr(x,y,700,40,8);text(a.done?'✓':'•',x+16,y+26,15,a.done?'#72ff91':'#7f8ca3');text(a.name,x+42,y+25,13,'#fff');text(`${Math.min(a.value,a.target)}/${a.target}`,x+675,y+25,12,a.done?'#72ff91':'#ffe66c','right');}S.buttons=[];button(625,825,350,52,'BACK',()=>mode('title'));}
function overlay(){if(S.mode==='transition'){ctx.fillStyle='rgba(0,0,0,.7)';ctx.fillRect(0,0,Q.W,Q.H);text(S.transition.title,800,410,48,'#72eaff','center');text(S.transition.sub,800,464,18,'#ffe66c','center');}else if(S.mode==='pause'||S.mode==='quit'){S.buttons=[];ctx.fillStyle='rgba(0,0,0,.74)';ctx.fillRect(0,0,Q.W,Q.H);text(S.mode==='pause'?'PAUSED':'ABANDON THIS RUN?',800,300,50,S.mode==='pause'?'#72eaff':'#ff7183','center');button(590,375,420,58,'RESUME',()=>mode(S.returnMode));if(S.mode==='pause')button(590,450,420,58,'LEVEL SELECT',()=>mode('levels'));button(590,S.mode==='pause'?525:460,420,58,'QUIT TO TITLE',quit,true);}else if(S.mode==='over'||S.mode==='won'){S.buttons=[];ctx.fillStyle='rgba(0,0,0,.78)';ctx.fillRect(0,0,Q.W,Q.H);text(S.mode==='won'?'COMMODORE QUEST COMPLETE':'GAME OVER',800,280,54,S.mode==='won'?'#7df0a5':'#ff7183','center');text(`SCORE ${Q.fmt(S.score)}`,800,350,30,'#fff','center');button(535,420,250,60,'PLAY AGAIN',startQuest);button(815,420,250,60,'LEVEL SELECT',()=>mode('levels'));button(675,505,250,54,'TITLE',quit);}}
function debugDraw(){if(!S.debug)return;ctx.save();ctx.strokeStyle='#00ff66';ctx.lineWidth=2;const b=playerBox();ctx.strokeRect(b.x,b.y,b.w,b.h);ctx.fillStyle='#00ff66';ctx.fillRect(playerAnchorX()-3,playerGround()-3,6,6);for(const e of S.entities){const r=entityBox(e);ctx.strokeStyle=e.response?'#ffdd00':'#00aaff';ctx.strokeRect(r.x,r.y,r.w,r.h);}if(S.fighter){ctx.strokeStyle='#ff66ff';const r=fighterEnemyBox(S.fighter);ctx.strokeRect(r.x,r.y,r.w,r.h);}ctx.restore();}
function draw(){
  ctx.setTransform(1,0,0,1,0,0);ctx.globalAlpha=1;ctx.shadowBlur=0;ctx.fillStyle='#05040b';ctx.fillRect(0,0,Q.W,Q.H);
  ctx.save();const sh=S.shake;ctx.translate(sh?rand(-sh,sh):0,sh?rand(-sh,sh):0);
  if(S.mode==='title')title();else if(S.mode==='levels')levels();else if(S.mode==='achievements')achievementScreen();else if(S.mode==='stage'||S.mode==='boss')drawStage();else if(S.mode==='beads')drawBeads();else if(S.mode==='fighter')drawFighter();else if(S.mode==='invaders')drawInvaders();else if(S.mode==='maze')drawMaze();else if(S.mode==='transition'){const next=S.transition?.next;if(next==='stage'||next==='boss')drawStage();else if(next==='beads')drawBeads();else if(next==='fighter')drawFighter();else if(next==='invaders')drawInvaders();else if(next==='maze')drawMaze();else title();}
  particlesDraw();debugDraw();if(S.toast&&now()<S.toast.until){ctx.fillStyle='rgba(4,8,15,.94)';ctx.strokeStyle='#ffd45d';ctx.lineWidth=3;rr(1080,760,470,105,12,true,true);text('ACHIEVEMENT UNLOCKED',1100,790,13,'#ffd45d');text(S.toast.text,1100,820,19);text('+'+S.toast.xp+' CCG XP',1100,846,13,'#7ff0a4');}overlay();ctx.restore();
  if(S.flash>0){ctx.globalAlpha=S.flash;ctx.fillStyle='#ff4964';ctx.fillRect(0,0,Q.W,Q.H);ctx.globalAlpha=1;}ctx.globalAlpha=.045;ctx.fillStyle='#000';for(let y=0;y<Q.H;y+=4)ctx.fillRect(0,y,Q.W,1);ctx.globalAlpha=1;
}
function gameOver(){mode('over');if(!S.practice)ACH.save();}
function win(){if(!S.practice){ACH.flag('won');if(S.lives===3)ACH.flag('oneCredit');}mode('won');}
function quit(){audio.setTheme(0,false,'title');resetRun();mode('title');}
function pause(){if(['title','levels','achievements','over','won','loading','transition'].includes(S.mode))return;if(S.mode==='pause'){mode(S.returnMode);return;}S.returnMode=S.mode;mode('pause');}
function pointer(ev){const r=canvas.getBoundingClientRect();return{x:(ev.clientX-r.left)*Q.W/r.width,y:(ev.clientY-r.top)*Q.H/r.height};}
canvas.addEventListener('pointerdown',ev=>{const p=pointer(ev);for(const b of [...S.buttons].reverse()){if(p.x>=b.x&&p.x<=b.x+b.w&&p.y>=b.y&&p.y<=b.y+b.h){b.fn();break;}}});
document.getElementById('btn-pause').onclick=pause;
document.getElementById('btn-level').onclick=()=>mode('levels');
document.getElementById('btn-quit').onclick=()=>{if(S.mode==='title'){window.location.assign('/games/ccg-games/');return;}S.returnMode=S.mode;mode('quit');};
document.getElementById('btn-fullscreen').onclick=()=>{const shell=document.getElementById('game-shell');document.fullscreenElement?document.exitFullscreen?.():shell.requestFullscreen?.();focus();};
document.querySelectorAll('[data-touch]').forEach(b=>{const n=b.dataset.touch;['pointerdown','touchstart'].forEach(ev=>b.addEventListener(ev,e=>{e.preventDefault();input.setVirtual(n,true);}));['pointerup','pointercancel','pointerleave','touchend'].forEach(ev=>b.addEventListener(ev,e=>{e.preventDefault();input.setVirtual(n,false);}));});
addEventListener('keydown',e=>{if(e.code==='Escape')pause();if(e.code==='F2'){S.debug=!S.debug;e.preventDefault();}});
function loop(t){const dt=Math.min(.033,(t-S.last)/1000||0);S.last=t;if(!['title','levels','achievements','pause','quit','over','won','loading'].includes(S.mode))update(dt);particlesUpdate(dt);draw();input.clear();requestAnimationFrame(loop);}
window.CCGQuestDebug={
  startQuest,practice,toggleHitboxes:()=>{S.debug=!S.debug;return S.debug;},
  forceFighterAttack:type=>{if(S.mode==='fighter')enemyAttack(type==='kick'?'kick':'punch');},
  getState:()=>({mode:S.mode,stage:S.stage,score:S.score,objective:S.objective,lives:S.lives,director:{...S.director},checkpoint:S.checkpoint,entities:S.entities.map(e=>({kind:e.kind,variant:e.variant||null,response:e.response||null,wait:e.wait||0,x:e.x,y:e.y})),player:{x:P.x,y:P.y,hp:P.hp,duck:P.duck,state:playerSpriteState(),animTime:P.anim.time,box:playerBox()},boss:S.boss&&{x:S.boss.x,y:S.boss.y,hp:S.boss.hp,phase:S.boss.phase},fighter:S.fighter&&{x:S.fighter.x,hp:S.fighter.hp,ai:S.fighter.ai,attack:S.fighter.attack&&{type:S.fighter.attack.type,phase:S.fighter.attack.phase,t:S.fighter.attack.t}},invaders:S.inv&&{alive:S.inv.aliens.filter(a=>a.alive).length,shield:S.inv.shield},maze:S.maze&&{dots:S.maze.collected,target:S.maze.target,powered:S.maze.powered}})
};
Promise.resolve(Q.hydrateRemoteAssets?.()).catch(()=>false).then(load).then(()=>{loading.classList.add('is-hidden');audio.setTheme(0,false,'title');mode('title');requestAnimationFrame(loop);}).catch(e=>{loading.textContent='LOAD ERROR: '+e.message;console.error(e);});
