window.CCG_CONFIG=Object.freeze({
  tile:42,
  worldWidth:128,
  worldHeight:84,
  keyTarget:3,
  maxPlayers:4,
  maxFloors:15,
  levelCaps:[5,10,15,20,25,30,35,40,45,50,55,60,65,70,75],
  logoAsset:"assets/ccgamer-logo-fallback.svg",
  logoFallback:"assets/ccgamer-logo-fallback.svg",
  player:{
    maxHealth:8,maxMana:240,moveDelay:138,fireDelay:175,dashDelay:510,maxProjectiles:5,
    sightRadius:6,torchRadius:22.5,torchMs:56000,startingInventorySlots:3,inventorySlots:6,
    emergencyAmmo:15,emergencyRechargeMs:3500,ammoFlashMs:1150,hitStunMs:180
  },
  enemy:{
    thinkDelay:90,lineOfSightRange:14,torchSightRange:20,contactRange:1,
    alertMemory:{spider:1800,skeleton:2300,knight:4800,scout:2300,hunter:4200,ambusher:3000,guard:2400,charger:3200,ranger:3200,root:3500,cook:3100,firebreather:3200,ghost:2600,guardian:5200,champion:4300,treasure:1200},
    searchTime:5000,idleStepMin:2220,idleStepMax:4070,followerLightRadius:10,namedAttackMultiplier:.70,
    namedHpPerLevel:.13,namedArmorPerLevel:.09,namedDamagePerLevel:.075,namedPotionPerLevel:.45,namedCadencePerLevel:.025,hitStunMs:1000,
    chaseStep:{spider:720,skeleton:820,knight:980,scout:940,hunter:780,ambusher:765,guard:999999,charger:530,ranger:940,root:1010,cook:1060,firebreather:840,ghost:890,guardian:690,champion:765,treasure:640}
  },
  stalker:{
    enabled:true,name:"Count Loadula",startFloor:2,moveMs:850,nearDistance:18,attackDistance:1.25,drainDistance:6,drainPerSecond:10,
    hitDamage:3,stunOnShotMs:500,spawnDelayMs:90000,musicKey:"count-loadula-default",
    banishVulnerableMs:12000,banishHpBase:8,flaskArtefacts:3,essenceRequired:3,banishedRespawnMs:30000,banishPromptDistance:8
  },
  camping:{graceMs:60000,warningMs:650,blastIntervalMs:650,resetDistance:6,zoneRadius:3,blastRadius:.35,damage:1,directBlastEvery:2},
  dungeon:{minLeaf:18,maxLeaf:32,roomMargin:3,targetRooms:34,maxLockedBranches:8,chestCount:10,secretRooms:3,secretPassages:2,sanctuaryRooms:2,wallTorchRooms:5,trapCount:20,generatorCount:3,generatorSpawnCap:3,sigilDefendersMin:3,standardEnemyTarget:44,ammoPacks:12,furnitureMin:5,furnitureMax:9,grandHallCount:1,boulderFloor:4,clueFloor:2,memoryPuzzleFloor:3,memoryPuzzleHardFloor:12,torchPuzzleFloor:4,weightBridgeFloor:5},
  proceduralDungeon:{
    enabled:true,
    version:"V10.42",
    name:"C64 Dungeon Carnage — Fifteen Floors",
    targetRunMinutesMin:135,
    targetRunMinutesMax:190,
    gamePickupCount:26,
    pickupDistribution:[2,2,2,2,2,2,2,2,2,2,2,1,1,1,1],
    essenceRequired:3,
    escapeAlert:82,
    campaignFloors:[
      {floor:1,id:"threshold",name:"THE THRESHOLD",objective:"explore_guardian",challenge:"survey",challengeTitle:"SURVEY THE ARCHIVE",challengeDesc:"Explore at least half the floor before confronting the Guardian.",targetMinutes:8,hpScale:.82,tempo:.88,ammoTarget:12,stalkerDelayMs:999999,deathStalkerSpeed:1.25,theme:"C64_ARCHIVE",domain:null},
      {floor:2,id:"driveworks",name:"1541 DRIVEWORKS",objective:"generators",challenge:"bloodClue",challengeTitle:"READ THE WRITING ON THE WALL",challengeDesc:"Find and inspect the faded blood clue. The sequence may matter deeper in the dungeon.",targetMinutes:9,hpScale:.86,tempo:.91,ammoTarget:12,stalkerDelayMs:120000,deathStalkerSpeed:1.20,theme:"1541_WORKSHOP",domain:null},
      {floor:3,id:"iron",name:"IRON KEEP",objective:"keys",challenge:"memory5",challengeTitle:"MEMORY VAULT",challengeDesc:"Complete the five-pad memory chamber and secure the Key of Iron.",targetMinutes:9,hpScale:.90,tempo:.94,ammoTarget:11,stalkerDelayMs:110000,deathStalkerSpeed:1.15,theme:"IRON_KEEP",domain:"iron"},
      {floor:4,id:"budget",name:"BUDGET VAULTS",objective:"rescue",challenge:"torch4",challengeTitle:"BLOOD & FLAME",challengeDesc:"Decode the Floor 2 clue and complete the four-torch sequence.",targetMinutes:9,hpScale:.94,tempo:.97,ammoTarget:11,stalkerDelayMs:100000,deathStalkerSpeed:1.10,theme:"BUDGET_BIN",domain:null},
      {floor:5,id:"cartridge",name:"CARTRIDGE CATACOMBS",objective:"generators",challenge:"bridge",challengeTitle:"TRICKSTER'S CROSSING",challengeDesc:"Cross the rotten bridge, rebuild it, hunt the thief and recover the stolen stash.",targetMinutes:10,hpScale:.98,tempo:1.00,ammoTarget:10,stalkerDelayMs:90000,deathStalkerSpeed:1.05,theme:"CARTRIDGE_BAY",domain:null},
      {floor:6,id:"tapes",name:"TAPE LABYRINTH",objective:"explore_guardian",challenge:"arena",challengeTitle:"ARENA OF TAPE",challengeDesc:"Find and clear the floor arena.",targetMinutes:10,hpScale:1.02,tempo:1.03,ammoTarget:10,stalkerDelayMs:85000,deathStalkerSpeed:1.00,theme:"TAPE_STORE",domain:null},
      {floor:7,id:"bone",name:"MOSS CRYPT",objective:"keys",challenge:"horde",challengeTitle:"BREAK THE BONE HORDE",challengeDesc:"Destroy the floor's skeleton horde before leaving with the Key of Bone.",targetMinutes:10,hpScale:1.06,tempo:1.06,ammoTarget:10,stalkerDelayMs:80000,deathStalkerSpeed:.96,theme:"MOSS_CRYPT",domain:"bone"},
      {floor:8,id:"demo",name:"DEMO UNDERCROFT",objective:"rescue",challenge:"timed",challengeTitle:"THIRTY-SECOND LOCKDOWN",challengeDesc:"Enter and survive the timed chamber.",targetMinutes:10,hpScale:1.10,tempo:1.09,ammoTarget:9,stalkerDelayMs:75000,deathStalkerSpeed:.92,theme:"DEMO_LOUNGE",domain:null},
      {floor:9,id:"modem",name:"MODEM WARRENS",objective:"generators",challenge:"goblin",challengeTitle:"CATCH THE RUNNER",challengeDesc:"Find and kill the Treasure Goblin before it escapes.",targetMinutes:11,hpScale:1.14,tempo:1.12,ammoTarget:9,stalkerDelayMs:70000,deathStalkerSpeed:.88,theme:"MODEM_EXCHANGE",domain:null},
      {floor:10,id:"sid",name:"SID FURNACE",objective:"explore_guardian",challenge:"boss",challengeTitle:"THE SID ABOMINATION",challengeDesc:"Defeat the grotesque boss guarding the descent.",targetMinutes:11,hpScale:1.18,tempo:1.15,ammoTarget:9,stalkerDelayMs:65000,deathStalkerSpeed:.84,theme:"SID_REACTOR",domain:null},
      {floor:11,id:"ash",name:"EMBER DEPTHS",objective:"keys",challenge:"timed",challengeTitle:"ASH LOCKDOWN",challengeDesc:"Survive the timed chamber and escape with the Key of Ash.",targetMinutes:11,hpScale:1.22,tempo:1.18,ammoTarget:8,stalkerDelayMs:60000,deathStalkerSpeed:.80,theme:"EMBER_DUNGEON",domain:"ash"},
      {floor:12,id:"foundry",name:"PIXEL FOUNDRY",objective:"generators",challenge:"memory7",challengeTitle:"SEVEN-PAD VAULT",challengeDesc:"Complete all seven memory pads to release the chamber.",targetMinutes:12,hpScale:1.28,tempo:1.20,ammoTarget:8,stalkerDelayMs:55000,deathStalkerSpeed:.76,theme:"PIXEL_FOUNDRY",domain:null},
      {floor:13,id:"scores",name:"HIGH SCORE CRYPT",objective:"rescue",challenge:"rescueArena",challengeTitle:"NO ONE LEFT BEHIND",challengeDesc:"Rescue the trapped CCG Scout and clear the floor arena.",targetMinutes:12,hpScale:1.34,tempo:1.22,ammoTarget:8,stalkerDelayMs:50000,deathStalkerSpeed:.72,theme:"HIGH_SCORE_CRYPT",domain:null},
      {floor:14,id:"crt",name:"CRT MAZE",objective:"explore_guardian",challenge:"arenaTimed",challengeTitle:"DOUBLE JEOPARDY",challengeDesc:"Clear both the arena and timed chamber before descending.",targetMinutes:13,hpScale:1.42,tempo:1.24,ammoTarget:7,stalkerDelayMs:45000,deathStalkerSpeed:.69,theme:"CRT_MAZE",domain:null},
      {floor:15,id:"citadel",name:"BLOOD CITADEL",objective:"guardian",challenge:"boss",challengeTitle:"THE BLOOD ARCHIVIST",challengeDesc:"Defeat the final grotesque keeper and complete the Citadel escape.",targetMinutes:14,hpScale:1.50,tempo:1.25,ammoTarget:7,stalkerDelayMs:40000,deathStalkerSpeed:.66,theme:"BLOOD_CITADEL",domain:null}
    ],
    keyDomains:[
      {id:"iron",floor:3,name:"KEY OF IRON",guardian:"Iron Warden",theme:"IRON_KEEP",weakness:"shock",sigilPower:"REVEAL"},
      {id:"bone",floor:7,name:"KEY OF BONE",guardian:"Bone Keeper",theme:"MOSS_CRYPT",weakness:"fire",sigilPower:"WARD"},
      {id:"ash",floor:11,name:"KEY OF ASH",guardian:"Ash Castellan",theme:"EMBER_DUNGEON",weakness:"energy",sigilPower:"BIND"}
    ],
    sigilPowers:[
      {id:"reveal",name:"REVEAL",desc:"The Sigil extends normal sight and exposes more of the dungeon around you."},
      {id:"ward",name:"WARD",desc:"The Sigil periodically absorbs one point of incoming damage."},
      {id:"bind",name:"BIND",desc:"The Sigil suppresses supernatural pursuers and slows their immediate pressure."},
      {id:"banish",name:"BANISH",desc:"Completing the Sigil grants one final Banishment charge for the escape."}
    ],
    relicChoices:3,
    developmentCopy:"Descend through fifteen generated floors. Build your character, recover the Keys of Iron, Bone and Ash across the campaign, complete the Sigil and survive the final Blood Citadel escape."
  },
  loot:{rarities:["COMMON","UNCOMMON","SIZZLER","GOLD MEDAL","ZZAP! 97%"]},
  difficulty:{
    CASUAL:{enemyHp:.68,enemyDamage:.55,enemyTempo:.72,enemyPopulation:.70,damageGraceMs:1350,loot:1.25,ammo:1.4,stalker:.68},
    ARCADE:{enemyHp:1,enemyDamage:1,enemyTempo:1,enemyPopulation:1,damageGraceMs:800,loot:1,ammo:1,stalker:1},
    SIZZLER:{enemyHp:1.2,enemyDamage:1.15,enemyTempo:1,enemyPopulation:1,damageGraceMs:800,loot:1.12,ammo:.92,stalker:1.12},
    "GOLD MEDAL":{enemyHp:1.45,enemyDamage:1.35,enemyTempo:1,enemyPopulation:1,damageGraceMs:800,loot:1.28,ammo:.82,stalker:1.28}
  },
  floors:[
    {name:"The Threshold",objective:"explore_guardian",theme:"C64_ARCHIVE"},
    {name:"1541 Driveworks",objective:"generators",theme:"1541_WORKSHOP"},
    {name:"Iron Keep",objective:"keys",theme:"IRON_KEEP"},
    {name:"Budget Vaults",objective:"rescue",theme:"BUDGET_BIN"},
    {name:"Cartridge Catacombs",objective:"generators",theme:"CARTRIDGE_BAY"},
    {name:"Tape Labyrinth",objective:"explore_guardian",theme:"TAPE_STORE"},
    {name:"Moss Crypt",objective:"keys",theme:"MOSS_CRYPT"},
    {name:"Demo Undercroft",objective:"rescue",theme:"DEMO_LOUNGE"},
    {name:"Modem Warrens",objective:"generators",theme:"MODEM_EXCHANGE"},
    {name:"SID Furnace",objective:"explore_guardian",theme:"SID_REACTOR"},
    {name:"Ember Depths",objective:"keys",theme:"EMBER_DUNGEON"},
    {name:"Pixel Foundry",objective:"generators",theme:"PIXEL_FOUNDRY"},
    {name:"High Score Crypt",objective:"rescue",theme:"HIGH_SCORE_CRYPT"},
    {name:"CRT Maze",objective:"explore_guardian",theme:"CRT_MAZE"},
    {name:"Blood Citadel",objective:"guardian",theme:"BLOOD_CITADEL"}
  ],
  followerElites:[
    {name:"Peter Cortens",initials:"PC",kind:"hunter",hp:8,armor:4,avatar:"assets/peter-cortens.png",musicKey:"peter-cortens",strength:"Relentless close-range pressure and flanking.",weakness:"Short reach — kite him through cover and fire from range."},
    {name:"Swanh8ter",initials:"SH",kind:"charger",hp:6,armor:3,avatar:"assets/swanh8ter.png",musicKey:"swanh8ter",strength:"A telegraphed charge can close ground very quickly.",weakness:"The wind-up reveals the line — sidestep or put an obstacle between you."},
    {name:"Syragar",initials:"SY",kind:"ranger",hp:6,armor:3,avatar:"assets/syragar.png",musicKey:"syragar",strength:"Accurate long-range fire with clever use of cover.",weakness:"Break line of sight, use corners, then close the distance."},
    {name:"AZALEA",initials:"AZ",kind:"root",hp:7,armor:4,avatar:"assets/parsnip-celery.png",musicKey:"parsnip-celery",strength:"Root projectiles pin down open lanes while AZALEA keeps pressure from range.",weakness:"Walls stop the shots; break line of sight and close from cover."},
    {name:"CPU",initials:"CPU",kind:"cook",hp:9,armor:5,avatar:"assets/cpu.png",musicKey:"cpu",strength:"Heals nearby enemies while throwing damaging food.",weakness:"Isolate and focus CPU first so the healing cannot sustain the room."},
    {name:"Yoshi Yoshi",initials:"YY",kind:"firebreather",hp:7,armor:4,avatar:"assets/yoshi-yoshi.png",musicKey:"yoshi-yoshi",strength:"Powerful fire breath dominates a long, straight lane.",weakness:"Move sideways or use walls — the flame cannot pass solid cover."},
    {name:"CCG",initials:"CCG",kind:"hunter",hp:18,armor:4,avatar:"",musicKey:"ccg",ccgBoss:true,moveSpeedScale:1.35,namedDamageScale:2,strength:"Heavy armour, high health and double named-enemy damage.",weakness:"Deliberately slow — maintain range and keep moving around cover."}
  ],
  c64LootByLetter:{
    A:["Airborne Ranger","Archon","Armalyte","Auf Wiedersehen Monty"],
    B:["Bard's Tale","Boulder Dash","Bruce Lee","Bubble Bobble"],
    C:["California Games","Commando","Creatures","Cybernoid"],
    D:["Defender of the Crown","Delta","Dizzy","Dropzone"],
    E:["Elite","Emlyn Hughes International Soccer","Exile"],
    F:["Fantasy World Dizzy","Firelord","Flimbo's Quest","Fort Apocalypse"],
    G:["Gauntlet","Ghosts 'n Goblins","Ghouls 'n Ghosts","Great Giana Sisters"],
    H:["Hawkeye","Head Over Heels","Hunter's Moon","Hyper Sports"],
    I:["IK+","Impossible Mission","International Karate","IO"],
    J:["Jet Set Willy","Jumpman","Jupiter Lander"],
    K:["Katakis","Kikstart II","Krakout"],
    L:["Leaderboard","Last Ninja","Last Ninja 2","Lode Runner"],
    M:["Maniac Mansion","Mayhem in Monsterland","Monty on the Run","Myth"],
    N:["Nebulus","Netherworld","New Zealand Story","North & South"],
    O:["Ocean Ranger","Oids","Operation Wolf","Out Run"],
    P:["Paradroid","Pirates!","Pitstop II","Project Firestart"],
    Q:["Q-Bert","Qix","Quake Minus One","Quedex"],
    R:["R-Type","Raid Over Moscow","Rainbow Islands","Rick Dangerous"],
    S:["Sam's Journey","Sentinel","Spy vs Spy","Summer Games II"],
    T:["Turrican","Turrican II","Tusker","Turbo Outrun"],
    U:["Ultima IV","Underwurlde","Uridium","Usagi Yojimbo"],
    V:["Vendetta","Vigilante","Volfied"],
    W:["Winter Games","Wizball","World Games","Wonder Boy"],
    X:["X-Out","Xenon","Xenon Ranger"],
    Y:["Yie Ar Kung-Fu","Yie Ar Kung-Fu II","Yogi's Great Escape"],
    Z:["Zak McKracken and the Alien Mindbenders","Zamzara","Zaxxon","Zynaps"]
  },
  c64Loot:[
    "Airborne Ranger","Archon","Armalyte","Auf Wiedersehen Monty","Bard's Tale","Boulder Dash","Bruce Lee","Bubble Bobble",
    "California Games","Commando","Creatures","Cybernoid","Defender of the Crown","Delta","Dizzy","Dropzone","Elite","Emlyn Hughes International Soccer","Exile",
    "Fantasy World Dizzy","Firelord","Flimbo's Quest","Fort Apocalypse","Gauntlet","Ghosts 'n Goblins","Ghouls 'n Ghosts","Great Giana Sisters","Hawkeye","Head Over Heels","Hunter's Moon","Hyper Sports",
    "IK+","Impossible Mission","International Karate","IO","Jet Set Willy","Jumpman","Jupiter Lander","Katakis","Kikstart II","Krakout","Leaderboard","Last Ninja","Last Ninja 2","Lode Runner",
    "Maniac Mansion","Mayhem in Monsterland","Monty on the Run","Myth","Nebulus","Netherworld","New Zealand Story","North & South","Ocean Ranger","Oids","Operation Wolf","Out Run",
    "Paradroid","Pirates!","Pitstop II","Project Firestart","Q-Bert","Qix","Quake Minus One","Quedex","R-Type","Raid Over Moscow","Rainbow Islands","Rick Dangerous",
    "Sam's Journey","Sentinel","Spy vs Spy","Summer Games II","Turrican","Turrican II","Tusker","Turbo Outrun","Ultima IV","Underwurlde","Uridium","Usagi Yojimbo",
    "Vendetta","Vigilante","Volfied","Winter Games","Wizball","World Games","Wonder Boy","X-Out","Xenon","Xenon Ranger","Yie Ar Kung-Fu","Yie Ar Kung-Fu II","Yogi's Great Escape",
    "Zak McKracken and the Alien Mindbenders","Zamzara","Zaxxon","Zynaps"
  ],
  roomThemes:["C64_ARCHIVE","1541_WORKSHOP","BUDGET_BIN","DEMO_LOUNGE","ARMOURY","CPU_KITCHEN","SID_REACTOR","WARP_GALLERY","ZZAP_LIBRARY","TAPE_STORE","CARTRIDGE_BAY","CRACKED_INTRO","PIXEL_FOUNDRY","MODEM_EXCHANGE","HIGH_SCORE_CRYPT","CRT_MAZE","IRON_KEEP","MOSS_CRYPT","EMBER_DUNGEON","BLOOD_CITADEL"],
  adminAudio:{stalker:null,dangerRoom:null,sanctuary:null,namedEnemies:{}}
});