window.CCGNetwork=(()=>{"use strict";
const C=window.CCG_CONFIG;const alphabet="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
const ROOM_MODES=Object.freeze({
 dungeon:Object.freeze({id:"dungeon",label:"Dungeon Multiplayer",maxPlayers:Math.max(1,Number(C.maxPlayers||4))}),
 "horde-survivor":Object.freeze({id:"horde-survivor",label:"Horde Multiplayer",maxPlayers:Math.max(1,Number(C.maxPlayers||4))}),
 "sizzler-saboteurs":Object.freeze({id:"sizzler-saboteurs",label:"Spy Vs Spy Multiplayer",maxPlayers:2})
});
function roomMode(v){const key=String(v||"").toLowerCase();return key==="horde"?"horde-survivor":/spy|saboteur/.test(key)?"sizzler-saboteurs":ROOM_MODES[key]?key:"dungeon"}
function id(n=10){const b=new Uint8Array(n);crypto.getRandomValues(b);return Array.from(b,x=>alphabet[x%alphabet.length]).join("")}
function code(v){return String(v||"").toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6)}
function sleep(ms){return new Promise(resolve=>setTimeout(resolve,ms))}
function localDev(){return /^(localhost|127\.0\.0\.1|0\.0\.0\.0)$/i.test(location.hostname)}
function memberOrder(a,b){const ar=a?.roomRole==="create"?0:1,br=b?.roomRole==="create"?0:1;if(ar!==br)return ar-br;return(Number(a?.joinedAt||0)-Number(b?.joinedAt||0))||String(a?.id||"").localeCompare(String(b?.id||""))}
class RoomNetwork{
 constructor(cb={}){this.cb=cb;this.sessionId=id(12);this.name="CCG Player";this.roomCode="";this.mode="solo";this.roomMode="dungeon";this.roomCapacity=ROOM_MODES.dungeon.maxPlayers;this.transport="solo";this.isHost=true;this.connected=false;this.members=new Map();this.joinedAt=Date.now();this.bc=null;this.client=null;this.channel=null;this.heartbeat=null;this.roomIntent="join";this.connectionError="";this.lastPacketAt=0;this._capacityRejected=false;this._lastMemberSignature="";this._publishedRoomMode="";this.runtimeStarted=false;this.runtimeStartMeta=null}
 createCode(){return id(5)}
 configureRoomMode(value){if(this.connected)throw new Error("Room mode cannot change after the lobby has connected.");this.roomMode=roomMode(value);this.roomCapacity=ROOM_MODES[this.roomMode].maxPlayers;return ROOM_MODES[this.roomMode]}
 getRoomMode(){return ROOM_MODES[this.roomMode]||ROOM_MODES.dungeon}
 getCapacity(){return this.getRoomMode().maxPlayers}
 presenceMember(){return{id:this.sessionId,name:this.name,joinedAt:this.joinedAt,roomRole:this.roomIntent,roomMode:this.roomMode,roomCapacity:this.getCapacity(),build:"V10.41",runtimeStarted:Boolean(this.runtimeStarted),runtimeStartMeta:this.runtimeStarted&&this.runtimeStartMeta?this.runtimeStartMeta:null}}
 setRuntimePresence(started,startMeta=null){this.runtimeStarted=Boolean(started);this.runtimeStartMeta=this.runtimeStarted&&startMeta?{...startMeta}:null;if(this.connected)return this.publishPresence();return Promise.resolve()}
 getHostRuntimePresence(){const host=this.getMembers()[0];return{started:Boolean(host?.runtimeStarted),startMeta:host?.runtimeStartMeta&&typeof host.runtimeStartMeta==="object"?{...host.runtimeStartMeta}:null,hostId:String(host?.id||"")}}
 setSolo(name){this.leave();this.runtimeStarted=false;this.runtimeStartMeta=null;this.mode="solo";this.transport="solo";this.name=name||"CCG Player";this.isHost=true;this.connected=false;this.roomCode="";this.members.set(this.sessionId,{id:this.sessionId,name:this.name,joinedAt:this.joinedAt,lastSeen:Date.now(),roomRole:"solo"});this.syncMembers()}
 async getSupabase(){if(window.ccgSupabase?.getClient)return window.ccgSupabase.getClient();if(/cheekycommodoregamer\.co\.uk$/i.test(location.hostname)){await this.load("/js/ccg-supabase-config.js");await this.load("/js/ccg-supabase-client.js");if(window.ccgSupabase?.getClient)return window.ccgSupabase.getClient()}return null}
 load(src){return new Promise((res,rej)=>{const ex=document.querySelector(`script[src="${src}"]`);if(ex){if(window.ccgSupabase?.getClient){res();return}ex.addEventListener("load",res,{once:true});setTimeout(()=>window.ccgSupabase?.getClient&&res(),0);return}const s=document.createElement("script");s.src=src;s.onload=res;s.onerror=rej;document.head.appendChild(s)})}
 async join(room,name,options={}){await this.leave();if(options.mode)this.configureRoomMode(options.mode);this.roomCode=code(room);if(this.roomCode.length<4)throw new Error("Room code must be at least four characters.");this.name=String(name||"CCG Player").trim().slice(0,18)||"CCG Player";this.joinedAt=Date.now();this.mode="coop";this.roomIntent=options.intent==="create"?"create":"join";this.runtimeStarted=false;this.runtimeStartMeta=null;this._capacityRejected=false;let supabase=null;try{supabase=await this.getSupabase()}catch(error){console.error("Lost Sizzler Realtime client failed",error)}if(!supabase){if(localDev()&&options.allowLocalDev===true){this.joinLocal();return{code:this.roomCode,transport:this.transport,members:this.getMembers(),roomMode:this.getRoomMode(),runtime:this.getHostRuntimePresence()}}throw new Error("Online multiplayer could not connect to CCG Realtime. This room has not been created.")}await this.joinSupabase(supabase);if(this.roomIntent==="create")await this.verifyFreshRoom();else await this.verifyExistingRoom();if(this._capacityRejected){const definition=this.getRoomMode();await this.leave();throw new Error(`Room is full. ${definition.label} supports a maximum of ${definition.maxPlayers} online players.`)}await this.sendRequired("hello",{id:this.sessionId,name:this.name,joinedAt:this.joinedAt,roomCode:this.roomCode,roomMode:this.roomMode});return{code:this.roomCode,transport:this.transport,members:this.getMembers(),roomMode:this.getRoomMode(),runtime:this.getHostRuntimePresence()}}
 createOnlineRoom(room,name,options={}){return this.join(room,name,{...options,intent:"create"})}
 joinExistingRoom(room,name){return this.join(room,name,{intent:"join"})}
 joinLocal(){this.transport="local";this.connected=true;this.bc=new BroadcastChannel(`ccg-quest:${this.roomCode}`);this.bc.onmessage=e=>this.receiveLocal(e.data);const member=this.presenceMember();this.touchMember(member);this.postLocal({type:"hello",member});this.heartbeat=setInterval(()=>{this.postLocal({type:"heartbeat",member:this.presenceMember()});this.prune()},1000);this.syncMembers()}
 receiveLocal(m){if(!m||m.sender===this.sessionId)return;if(m.type==="hello"||m.type==="heartbeat"){this.touchMember(m.member);if(m.type==="hello")this.postLocal({type:"heartbeat",member:this.presenceMember()});this.syncMembers();return}if(m.type==="bye"){this.members.delete(m.memberId);this.syncMembers();return}if(m.type==="packet")this.cb.onPacket?.(m.event,m.payload)}
 postLocal(obj){this.bc?.postMessage({...obj,sender:this.sessionId})}
 touchMember(m){if(m?.id)this.members.set(m.id,{...m,lastSeen:Date.now()})}
 prune(){const now=Date.now();for(const [k,m] of this.members)if(k!==this.sessionId&&now-m.lastSeen>3500)this.members.delete(k);this.syncMembers()}
 async publishPresence(){if(!this.channel||!this.connected)return;this._publishedRoomMode=this.roomMode;try{await this.channel.track(this.presenceMember())}catch(error){console.warn("Lost Sizzler room presence update failed",error)}}
 async joinSupabase(client){this.transport="supabase";this.client=client;this.connectionError="";const activeChannel=this.channel=client.channel(`ccg-quest:${this.roomCode}`,{config:{private:false,presence:{key:this.sessionId},broadcast:{self:false,ack:true}}});activeChannel.on("presence",{event:"sync"},()=>this.syncSupabasePresence()).on("presence",{event:"join"},()=>this.syncSupabasePresence()).on("presence",{event:"leave"},()=>this.syncSupabasePresence()).on("broadcast",{event:"ccg_packet"},({payload})=>{this.lastPacketAt=Date.now();this.cb.onPacket?.(payload?.event,payload?.payload)});await new Promise((res,rej)=>{let settled=false,finishError=message=>{if(this.channel!==activeChannel)return;if(settled){this.connected=false;this.connectionError=message;this.cb.onConnection?.(false,message);return}settled=true;clearTimeout(t);rej(new Error(message))},register=async()=>{if(this.channel!==activeChannel)return;try{const tracked=await activeChannel.track(this.presenceMember());this._publishedRoomMode=this.roomMode;if(tracked&&tracked!=="ok"&&tracked.status&&tracked.status!=="ok")throw new Error("Presence tracking failed");this.connected=true;this.connectionError="";this.syncSupabasePresence();this.cb.onConnection?.(true,"");if(!settled){settled=true;clearTimeout(t);res()}}catch(error){finishError(error?.message||"Could not register in the online room.")}},t=setTimeout(()=>finishError("Timed out connecting to CCG Realtime."),10000);activeChannel.subscribe(status=>{if(status==="SUBSCRIBED"){register();return}if(status==="CHANNEL_ERROR")finishError("Could not join the CCG Realtime room.");else if(status==="TIMED_OUT")finishError("CCG Realtime timed out while joining the room.");else if(status==="CLOSED")finishError("The CCG Realtime room connection closed.")})})}
 syncSupabasePresence(){if(!this.channel)return;this.members.clear();const raw=this.channel.presenceState();for(const arr of Object.values(raw))for(const p of arr)this.touchMember(p);this.touchMember(this.presenceMember());this.syncMembers()}
 async verifyFreshRoom(){for(let i=0;i<5;i++){this.syncSupabasePresence();const others=[...this.members.values()].filter(member=>member.id!==this.sessionId);if(others.length){await this.leave();throw new Error("That randomly generated room code is already in use. Create another room.")}await sleep(120)}return true}
 async verifyExistingRoom(){for(let i=0;i<40;i++){this.syncSupabasePresence();if(this._capacityRejected)return false;const peers=[...this.members.values()].filter(member=>member.id!==this.sessionId);if(peers.length){const host=[...this.members.values()].sort(memberOrder)[0];if(host&&host.id!==this.sessionId)return true}await sleep(125)}await this.leave();throw new Error("Room not found or the host is no longer online. Check the room code and try again.")}
 syncMembers(){const all=[...this.members.values()].sort(memberOrder),leader=all[0],was=this.isHost,announced=leader?.roomMode;this.roomMode=roomMode(announced||this.roomMode);this.roomCapacity=ROOM_MODES[this.roomMode].maxPlayers;const admitted=all.slice(0,this.roomCapacity);this._capacityRejected=all.length>this.roomCapacity&&!admitted.some(member=>member.id===this.sessionId);this.isHost=(admitted[0]?.id||this.sessionId)===this.sessionId;this._lastMemberSignature=admitted.map(member=>member.id).join("|");if(this.connected&&admitted.some(member=>member.id===this.sessionId)&&this._publishedRoomMode!==this.roomMode)Promise.resolve().then(()=>this.publishPresence());this.cb.onMembers?.(admitted,this.isHost,was!==this.isHost)}
 async send(event,payload){if(this.mode!=="coop"||!this.connected)return"disconnected";if(this.transport==="local"){this.postLocal({type:"packet",event,payload});return"ok"}try{const result=await this.channel?.send({type:"broadcast",event:"ccg_packet",payload:{event,payload}}),status=typeof result==="string"?result:result?.status||"error";if(status!=="ok"){this.connectionError=`Realtime broadcast ${status}.`;return status}this.connectionError="";return"ok"}catch(error){this.connectionError=String(error?.message||error||"Realtime broadcast failed.");return"error"}}
 async sendRequired(event,payload){const status=await this.send(event,payload);if(status!=="ok")throw new Error(status==="disconnected"?"Online room is not connected.":this.connectionError||`Realtime broadcast ${status}.`);return status}
 async leave(){const heartbeat=this.heartbeat,bc=this.bc,channel=this.channel,client=this.client;if(heartbeat)clearInterval(heartbeat);if(bc){try{bc.postMessage({type:"bye",memberId:this.sessionId,sender:this.sessionId});bc.close()}catch(_){}}this.heartbeat=null;this.bc=null;this.channel=null;this.client=null;this.members.clear();this.connected=false;this.connectionError="";this.isHost=true;this.runtimeStarted=false;this.runtimeStartMeta=null;this._capacityRejected=false;this._lastMemberSignature="";this._publishedRoomMode="";if(channel){try{await channel.untrack()}catch(_){}try{await client?.removeChannel(channel)}catch(_){}}}
 getMembers(){return[...this.members.values()].sort(memberOrder).slice(0,this.getCapacity())}
 getDiagnostics(){return{connected:this.connected,transport:this.transport,roomCode:this.roomCode,roomMode:this.roomMode,roomCapacity:this.getCapacity(),isHost:this.isHost,connectionError:this.connectionError,lastPacketAt:this.lastPacketAt,memberCount:this.getMembers().length,runtimeStarted:this.getHostRuntimePresence().started,members:this.getMembers().map(member=>({id:member.id,name:member.name,role:member.roomRole||"peer",runtimeStarted:Boolean(member.runtimeStarted)}))}}
}
RoomNetwork.prototype.__v104CapacityPatched=true;
return{RoomNetwork,ROOM_MODES,cleanCode:code};})();