-- CCG Commodore Quest live asset manager
-- Public game reads enabled asset metadata; only admin/superadmin can mutate.

CREATE TABLE IF NOT EXISTS public.arcade_assets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asset_group text NOT NULL,
  asset_key text NOT NULL,
  file_path text NOT NULL,
  public_url text NOT NULL,
  mime_type text,
  size_bytes bigint NOT NULL DEFAULT 0 CHECK (size_bytes >= 0),
  enabled boolean NOT NULL DEFAULT true,
  notes text,
  asset_meta jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_by uuid REFERENCES auth.users(id) ON DELETE SET NULL DEFAULT auth.uid(),
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  UNIQUE(asset_group, asset_key)
);

-- Safe if an earlier draft of this table was ever applied.
ALTER TABLE public.arcade_assets
  ADD COLUMN IF NOT EXISTS asset_meta jsonb NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE public.arcade_assets
  DROP CONSTRAINT IF EXISTS arcade_assets_asset_group_check;
ALTER TABLE public.arcade_assets
  ADD CONSTRAINT arcade_assets_asset_group_check CHECK (asset_group IN (
    'backgrounds','layers','bosses','hazards','collectibles','powers',
    'fighter','invaders','player','spritesheets','music','sfx'
  ));

ALTER TABLE public.arcade_assets ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can read enabled arcade assets" ON public.arcade_assets;
CREATE POLICY "Public can read enabled arcade assets"
ON public.arcade_assets FOR SELECT TO anon, authenticated
USING (enabled = true);

DROP POLICY IF EXISTS "Admins can read all arcade assets" ON public.arcade_assets;
CREATE POLICY "Admins can read all arcade assets"
ON public.arcade_assets FOR SELECT TO authenticated
USING (public.current_user_role() IN ('admin','superadmin'));

DROP POLICY IF EXISTS "Admins can manage arcade assets" ON public.arcade_assets;
CREATE POLICY "Admins can manage arcade assets"
ON public.arcade_assets FOR ALL TO authenticated
USING (public.current_user_role() IN ('admin','superadmin'))
WITH CHECK (public.current_user_role() IN ('admin','superadmin'));

GRANT SELECT ON public.arcade_assets TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.arcade_assets TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.arcade_assets_id_seq TO authenticated;

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'ccg-arcade-assets',
  'ccg-arcade-assets',
  true,
  26214400,
  ARRAY[
    'image/png','image/jpeg','image/webp','image/gif','image/svg+xml',
    'audio/mpeg','audio/ogg','audio/wav','audio/x-wav'
  ]::text[]
)
ON CONFLICT (id) DO UPDATE
SET public = EXCLUDED.public,
    file_size_limit = EXCLUDED.file_size_limit,
    allowed_mime_types = EXCLUDED.allowed_mime_types;

DROP POLICY IF EXISTS "Public can read arcade storage" ON storage.objects;
CREATE POLICY "Public can read arcade storage"
ON storage.objects FOR SELECT TO anon, authenticated
USING (bucket_id='ccg-arcade-assets');

DROP POLICY IF EXISTS "Admins can upload arcade storage" ON storage.objects;
CREATE POLICY "Admins can upload arcade storage"
ON storage.objects FOR INSERT TO authenticated
WITH CHECK (
  bucket_id='ccg-arcade-assets'
  AND public.current_user_role() IN ('admin','superadmin')
);

DROP POLICY IF EXISTS "Admins can update arcade storage" ON storage.objects;
CREATE POLICY "Admins can update arcade storage"
ON storage.objects FOR UPDATE TO authenticated
USING (
  bucket_id='ccg-arcade-assets'
  AND public.current_user_role() IN ('admin','superadmin')
)
WITH CHECK (
  bucket_id='ccg-arcade-assets'
  AND public.current_user_role() IN ('admin','superadmin')
);

DROP POLICY IF EXISTS "Admins can delete arcade storage" ON storage.objects;
CREATE POLICY "Admins can delete arcade storage"
ON storage.objects FOR DELETE TO authenticated
USING (
  bucket_id='ccg-arcade-assets'
  AND public.current_user_role() IN ('admin','superadmin')
);