create table if not exists public.game_feedback (
  id bigint generated by default as identity primary key,
  game_slug text not null default 'the-lost-sizzler',
  feedback_type text not null check (feedback_type in ('bug','suggestion')),
  message text not null check (char_length(message) >= 10 and char_length(message) <= 3000),
  contact_email text,
  page_url text,
  build text,
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.game_feedback enable row level security;
