insert into public.lost_sizzler_collectible_effects (match_type,match_value,effect_type,duration_ms,config,enabled) values
('genre','action-adventure','explorer_sight',10000,'{"popup":"ADVENTURE VISION!","bonus":2.5}'::jsonb,true),
('genre','adventure','map_ping',0,'{"popup":"MAP CLUE FOUND!","rooms":3}'::jsonb,true),
('genre','arcade','arcade_frenzy',8000,'{"popup":"ARCADE FRENZY!","ammo":15}'::jsonb,true),
('genre','casino','casino_roll',0,'{"popup":"PLACE YOUR BET..."}'::jsonb,true),
('genre','fighting','combat_focus',10000,'{"popup":"FIGHT MODE!","dash_bonus":2}'::jsonb,true),
('genre','miscellaneous','wildcard',0,'{"popup":"ANYTHING COULD HAPPEN..."}'::jsonb,true),
('genre','platform','nimble',10000,'{"popup":"NIMBLE FEET!","move_scale":0.76}'::jsonb,true),
('genre','puzzle','secret_scan',0,'{"popup":"SECRET SCAN!","doors":2}'::jsonb,true),
('genre','racing','turbo',10000,'{"popup":"TURBO!","move_scale":0.58}'::jsonb,true),
('genre','role-playing','xp_boon',0,'{"popup":"RPG XP BOOST!","xp":300}'::jsonb,true),
('genre','quiz','brain_boost',9000,'{"popup":"BRAIN BOOST!","xp":150,"sight":2}'::jsonb,true),
('genre','shooting','weapon_overdrive',10000,'{"popup":"WEAPON OVERDRIVE!","ammo":25}'::jsonb,true),
('genre','sports','athlete',10000,'{"popup":"SPORTS MODE!","move_scale":0.82,"heal":1}'::jsonb,true),
('genre','strategy','tactical_freeze',6500,'{"popup":"TACTICAL ADVANTAGE!","enemy_time_scale":0.55}'::jsonb,true),
('title','Ghostbusters','ghostbuster_kit',0,'{"popup":"WHO YOU GONNA CALL?"}'::jsonb,true),
('title','Ghostbusters II','ghostbuster_kit',0,'{"popup":"BUSTIN’ MAKES YOU FEEL GOOD"}'::jsonb,true),
('title','The Real Ghostbusters','ghostbuster_kit',0,'{"popup":"PROTON PACK READY"}'::jsonb,true),
('title','Bubble Bobble','bubble_shield',8000,'{"popup":"BUBBLE SHIELD!"}'::jsonb,true),
('title','The Last Ninja','ninja_step',10000,'{"popup":"NINJA FEET!","move_scale":0.65}'::jsonb,true),
('title','Turrican','turbo_blaster',12000,'{"popup":"TURRICAN MODE!","move_scale":0.68,"ammo":35}'::jsonb,true),
('title','Turrican II: The Final Fight','turbo_blaster',12000,'{"popup":"TURRICAN MODE!","move_scale":0.68,"ammo":35}'::jsonb,true),
('title','Elite','elite_bounty',0,'{"popup":"ELITE BOUNTY!","score":2000}'::jsonb,true),
('title','Frogger','frog_hop',0,'{"popup":"RIBBIT!"}'::jsonb,true),
('title','Ghosts ''n Goblins','underpants_mode',10000,'{"popup":"ARMOUR GONE!"}'::jsonb,true),
('title','Ghouls ''n Ghosts','underpants_mode',10000,'{"popup":"ARMOUR GONE!"}'::jsonb,true),
('title','Boulder Dash','boulder_skin',0,'{"popup":"BOULDER TOUGH!","armor":3}'::jsonb,true),
('title','Impossible Mission','secret_scan',0,'{"popup":"MISSION INTELLIGENCE!","doors":3}'::jsonb,true),
('title','Wizball','colour_burst',0,'{"popup":"WIZBALL COLOUR BURST!"}'::jsonb,true),
('title','Commando','weapon_overdrive',12000,'{"popup":"COMMANDO FIREPOWER!","ammo":35}'::jsonb,true),
('title','Bruce Lee','combat_focus',12000,'{"popup":"BRUCE LEE MODE!","dash_bonus":3}'::jsonb,true),
('title','International Karate','combat_focus',12000,'{"popup":"KARATE MODE!","dash_bonus":3}'::jsonb,true),
('title','IK+','combat_focus',12000,'{"popup":"IK+ MODE!","dash_bonus":3}'::jsonb,true),
('title','Monty on the Run','turbo',12000,'{"popup":"MONTY — RUN!","move_scale":0.55}'::jsonb,true),
('title','Uridium','turbo_blaster',10000,'{"popup":"URIDIUM ATTACK!","move_scale":0.65,"ammo":30}'::jsonb,true),
('title','Pac-Man','score_feast',0,'{"popup":"WAKKA WAKKA!","score":1000}'::jsonb,true),
('title','Prince Of Persia','time_slow',8000,'{"popup":"TIME SLOWS...","enemy_time_scale":0.5}'::jsonb,true),
('title','The Secret Of Monkey Island','tactical_freeze',7000,'{"popup":"INSULT CONFUSION!","enemy_time_scale":0.5}'::jsonb,true),
('title','Lemmings','map_ping',0,'{"popup":"LEMMINGS KNOW THE WAY!","rooms":5}'::jsonb,true),
('title','Dungeon Master','xp_boon',0,'{"popup":"DUNGEON MASTER!","xp":500}'::jsonb,true),
('title','Eye Of The Beholder II: The Legend Of Darkmoon','explorer_sight',12000,'{"popup":"BEHOLDER VISION!","bonus":4}'::jsonb,true),
('title','Stunt Car Racer','turbo',12000,'{"popup":"STUNT CAR TURBO!","move_scale":0.54}'::jsonb,true),
('title','California Games','athlete',12000,'{"popup":"CALIFORNIA MODE!","move_scale":0.76,"heal":1}'::jsonb,true),
('title','Summer Games','athlete',12000,'{"popup":"SUMMER GAMES MODE!","move_scale":0.76,"heal":1}'::jsonb,true),
('title','Summer Games II','athlete',12000,'{"popup":"SUMMER GAMES II!","move_scale":0.76,"heal":1}'::jsonb,true),
('title','World Games','athlete',12000,'{"popup":"WORLD GAMES MODE!","move_scale":0.76,"heal":1}'::jsonb,true),
('title','Spy Vs Spy','tactical_freeze',6500,'{"popup":"SPY SABOTAGE!","enemy_time_scale":0.5}'::jsonb,true),
('title','Mayhem in Monsterland','wildcard',0,'{"popup":"MAYHEM!"}'::jsonb,true)
on conflict (match_type,match_value,effect_type) do update
set duration_ms=excluded.duration_ms,config=excluded.config,enabled=true,updated_at=now();
