create table if not exists public.ccg_products (
  slug text primary key,
  name text not null,
  currency text not null default 'gbp',
  amount_pence integer not null check (amount_pence > 0),
  download_bucket text not null,
  download_path text,
  download_ready boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ccg_product_entitlements (
  user_id uuid not null references auth.users(id) on delete cascade,
  product_slug text not null references public.ccg_products(slug) on delete restrict,
  status text not null default 'active' check (status in ('active','revoked','refunded','disputed')),
  source text not null default 'stripe',
  stripe_customer_id text,
  stripe_checkout_session_id text,
  stripe_payment_intent_id text,
  purchased_at timestamptz not null default now(),
  revoked_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (user_id, product_slug)
);

create unique index if not exists ccg_product_entitlements_checkout_session_key
  on public.ccg_product_entitlements(stripe_checkout_session_id)
  where stripe_checkout_session_id is not null;

create index if not exists ccg_product_entitlements_payment_intent_idx
  on public.ccg_product_entitlements(stripe_payment_intent_id)
  where stripe_payment_intent_id is not null;

create table if not exists public.ccg_checkout_sessions (
  session_id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_slug text not null references public.ccg_products(slug) on delete restrict,
  stripe_payment_intent_id text,
  status text not null default 'created' check (status in ('created','complete','expired','failed','refunded','disputed')),
  amount_total integer,
  currency text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ccg_checkout_sessions_user_product_idx
  on public.ccg_checkout_sessions(user_id, product_slug, created_at desc);

create table if not exists public.ccg_stripe_webhook_events (
  event_id text primary key,
  event_type text not null,
  object_id text,
  livemode boolean not null default false,
  processed_at timestamptz not null default now()
);

create table if not exists public.ccg_download_audit (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_slug text not null references public.ccg_products(slug) on delete restrict,
  requested_at timestamptz not null default now()
);

alter table public.ccg_products enable row level security;
alter table public.ccg_product_entitlements enable row level security;
alter table public.ccg_checkout_sessions enable row level security;
alter table public.ccg_stripe_webhook_events enable row level security;
alter table public.ccg_download_audit enable row level security;

revoke all on table public.ccg_products from anon, authenticated;
revoke all on table public.ccg_product_entitlements from anon, authenticated;
revoke all on table public.ccg_checkout_sessions from anon, authenticated;
revoke all on table public.ccg_stripe_webhook_events from anon, authenticated;
revoke all on table public.ccg_download_audit from anon, authenticated;

insert into public.ccg_products(slug,name,currency,amount_pence,download_bucket,download_path,download_ready,active)
values ('c64-dungeon-carnage','C64 Dungeon Carnage','gbp',199,'ccg-paid-downloads','c64-dungeon-carnage/c64-dungeon-carnage.zip',false,true)
on conflict (slug) do update set
  name=excluded.name,
  currency=excluded.currency,
  amount_pence=excluded.amount_pence,
  download_bucket=excluded.download_bucket,
  download_path=excluded.download_path,
  active=excluded.active,
  updated_at=now();

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values ('ccg-paid-downloads','ccg-paid-downloads',false,104857600,array['application/zip','application/octet-stream']::text[])
on conflict (id) do update set
  public=false,
  file_size_limit=excluded.file_size_limit,
  allowed_mime_types=excluded.allowed_mime_types;
