create table if not exists public.game_play_events (
  id bigint generated by default as identity primary key,
  game_slug text not null default 'the-lost-sizzler',
  event_type text not null check (event_type in ('start_click','mobile_pc_notice_accept','rating_submitted','rating_dismissed')),
  player_name text,
  play_mode text,
  device_type text not null check (device_type in ('desktop','mobile','tablet','unknown')) default 'unknown',
  rating smallint check (rating between 1 and 5),
  session_token text,
  auth_user_id uuid references auth.users(id) on delete set null,
  build text,
  page_url text,
  user_agent text,
  created_at timestamptz not null default now()
);

create index if not exists game_play_events_created_at_idx on public.game_play_events (created_at desc);
create index if not exists game_play_events_event_type_idx on public.game_play_events (event_type, created_at desc);
create index if not exists game_play_events_session_idx on public.game_play_events (session_token, created_at desc);

alter table public.game_play_events enable row level security;

drop policy if exists "Admins can read Lost Sizzler play events" on public.game_play_events;
create policy "Admins can read Lost Sizzler play events"
on public.game_play_events for select to authenticated
using (public.current_user_role() in ('admin','superadmin'));

grant select on public.game_play_events to authenticated;

drop policy if exists "Admins can read Lost Sizzler feedback" on public.game_feedback;
create policy "Admins can read Lost Sizzler feedback"
on public.game_feedback for select to authenticated
using (public.current_user_role() in ('admin','superadmin'));

grant select on public.game_feedback to authenticated;
