alter table public.game_feedback
  add column if not exists feedback_status text not null default 'open',
  add column if not exists last_replied_at timestamptz;

alter table public.game_feedback
  drop constraint if exists game_feedback_feedback_status_check;

alter table public.game_feedback
  add constraint game_feedback_feedback_status_check
  check (feedback_status in ('open','replied','closed'));

create index if not exists game_feedback_status_created_at_idx
  on public.game_feedback (feedback_status, created_at desc);

create table if not exists public.game_feedback_replies (
  id bigint generated by default as identity primary key,
  feedback_id bigint not null references public.game_feedback(id) on delete cascade,
  admin_user_id uuid references auth.users(id) on delete set null,
  reply_text text not null check (char_length(reply_text) between 2 and 4000),
  recipient_email text,
  email_status text not null default 'pending' check (email_status in ('pending','sent','failed')),
  email_error text,
  created_at timestamptz not null default now()
);

create index if not exists game_feedback_replies_feedback_created_at_idx
  on public.game_feedback_replies (feedback_id, created_at);
create index if not exists game_feedback_replies_admin_user_id_idx
  on public.game_feedback_replies (admin_user_id);

alter table public.game_feedback_replies enable row level security;

revoke all on table public.game_feedback_replies from anon, authenticated;
grant select on table public.game_feedback_replies to authenticated;
revoke all on sequence public.game_feedback_replies_id_seq from anon, authenticated;

drop policy if exists "Admins can read Lost Sizzler feedback replies" on public.game_feedback_replies;
create policy "Admins can read Lost Sizzler feedback replies"
  on public.game_feedback_replies
  for select
  to authenticated
  using (public.current_user_role() in ('admin','superadmin'));
