-- Omega Pass Option A: notifications/newsletter profile fields + secure RLS
create extension if not exists pgcrypto;

alter table public.profiles
  add column if not exists newsletter_opt_in boolean not null default false,
  add column if not exists notify_new_games_opt_in boolean not null default false,
  add column if not exists notify_platform_c64 boolean not null default true,
  add column if not exists notify_platform_amiga boolean not null default true,
  add column if not exists unsub_token text,
  add column if not exists email_confirmed boolean,
  add column if not exists last_newsletter_sent_at timestamptz,
  add column if not exists last_notify_sent_at timestamptz;

update public.profiles
set unsub_token = encode(gen_random_bytes(24), 'hex')
where unsub_token is null or length(trim(unsub_token)) < 24;

alter table public.profiles
  alter column unsub_token set not null;

create unique index if not exists profiles_unsub_token_key on public.profiles(unsub_token);

-- remove broad public-read policy and enforce owner-only access
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'profiles' AND policyname = 'profiles_public_read'
  ) THEN
    DROP POLICY profiles_public_read ON public.profiles;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'profiles' AND policyname = 'profiles_owner_select'
  ) THEN
    CREATE POLICY profiles_owner_select ON public.profiles
      FOR SELECT TO authenticated
      USING (id = auth.uid());
  END IF;
END $$;

create or replace function public.handle_new_user_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (
    id,
    display_name,
    avatar_url,
    unsub_token,
    newsletter_opt_in,
    notify_new_games_opt_in,
    notify_platform_c64,
    notify_platform_amiga,
    email_confirmed
  )
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data->>'avatar_url', ''),
    encode(gen_random_bytes(24), 'hex'),
    false,
    false,
    true,
    true,
    (new.email_confirmed_at is not null)
  )
  on conflict (id) do update
  set email_confirmed = excluded.email_confirmed;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created_profile on auth.users;
create trigger on_auth_user_created_profile
  after insert on auth.users
  for each row execute function public.handle_new_user_profile();

create table if not exists public.email_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  email_type text not null,
  game_slug text,
  sent_at timestamptz not null default now()
);

create unique index if not exists email_log_dedupe_idx
  on public.email_log (user_id, email_type, coalesce(game_slug, ''));

