create table if not exists public.lost_sizzler_collectible_effects (
  id bigint generated by default as identity primary key,
  match_type text not null check (match_type in ('title','genre')),
  match_value text not null,
  effect_type text not null,
  duration_ms integer not null default 0 check (duration_ms >= 0),
  config jsonb not null default '{}'::jsonb,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(match_type, match_value, effect_type)
);

alter table public.lost_sizzler_collectible_effects enable row level security;

drop policy if exists "public can read lost sizzler collectible effects" on public.lost_sizzler_collectible_effects;
create policy "public can read lost sizzler collectible effects"
on public.lost_sizzler_collectible_effects
for select
to anon, authenticated
using (enabled = true);

insert into public.lost_sizzler_collectible_effects(match_type,match_value,effect_type,duration_ms,config)
values
('genre','horror','spawn_horror_creature',0,'{"creature":"archive_wraith","hp":50,"armor":0,"music":"horror"}'::jsonb),
('title','Winter Games','slippery',10000,'{"popup":"Woahhh slidy"}'::jsonb),
('title','Bozo''s Night Out','reverse_controls',10000,'{"popup":"Controls reversed!"}'::jsonb),
('title','How To Be A Complete Bastard','teleport_far_side',0,'{"popup":"BASTARD! TELEPORTED!"}'::jsonb),
('title','Everyone''s A Wally','spin',10000,'{"popup":"WALLY SPIN!"}'::jsonb),
('title','Paradroid','transform',10000,'{"transform":"paradroid_001","popup":"001 DROID MODE"}'::jsonb)
on conflict (match_type,match_value,effect_type)
do update set duration_ms=excluded.duration_ms, config=excluded.config, enabled=true, updated_at=now();
